cni: deploy a fallback `loopback` CNI configuration
scality/metalk8s pull request #1089
Opened 2019-05-06 15:33 UTC by NicolasT

When setting up a *master* and/or *etcd* node, we don't deploy Calico
(and its configuration) on the server, because such node is not
required to be part of the overlay network (it's not running any
non-`hostNetwork` Pods, and shouldn't connect to any other
non-`hostNetwork` Pods).

However, as long as no CNI configuration is present, `kubelet`
complains and the Node remains in `NotReady` state.

We can work-around this by either

- explaining this in documentation
- unnecessarily deploying Calico on the node
- providing another valid CNI configuration, e.g. for `localhost`

The latter seem the right approach here: it'll still require
documentation ('Why is my Pod not working on a non-node/infra node after
I removed the taints?'), but doesn't unnecessarily impact the networking
on a control-plane node, and doesn't keep Nodes in `NotReady` state even
though they kind-of are.

Fixes: #1087
Fixes: https://github.com/scality/metalk8s/issues/1087

2019-05-06 15:33 UTC, bert-e commented
# Hello nicolast,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/metalk8s/bert-e/doc/user).





*Status report is not available.*

2019-05-06 15:33 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `improvement/1087-loopback-cni` into
`development/2.0`
* [w/2.1/improvement/1087-loopback-cni](https://github.com/scality/metalk8s/compare/development/2.1...w/2.1/improvement/1087-loopback-cni) will be merged into `development/2.1` 
* [w/2.2/improvement/1087-loopback-cni](https://github.com/scality/metalk8s/compare/development/2.2...w/2.2/improvement/1087-loopback-cni) will be merged into `development/2.2` 



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`




You can set option `create_pull_requests` if you need me to create
**integration pull requests** in addition to integration branches, with:

```
@bert-e create_pull_requests
```

2019-05-06 15:33 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @cmonfort

* @alexandre-allard-scality

* @gdemonet

* @slaperche-scality

* @ramanduh

* @ballot-scality

* @teddyandrieux

* @tcarmet

* @lucieleonard

* @zempashi

* @sayf-eddine-scality

* @carlito-scality

* @jbertran

* @thomasdanan

* @monpote

* @nootal

* @nicolast

* @alxf

2019-05-06 15:41 UTC, bert-e commented
# History mismatch



Merge commit #1987303f7499bb075977ddd98ef88eba9fa92a13 on the integration branch
`w/2.1/improvement/1087-loopback-cni` is merging a branch which is neither the current
branch `improvement/1087-loopback-cni` nor the development branch
`development/2.1`.

It is likely due to a rebase of the branch `improvement/1087-loopback-cni` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**

2019-05-06 15:41 UTC, NicolasT commented
@bert-e reset

2019-05-06 15:41 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.

2019-05-06 15:42 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `improvement/1087-loopback-cni` into
`development/2.0`
* [w/2.1/improvement/1087-loopback-cni](https://github.com/scality/metalk8s/compare/development/2.1...w/2.1/improvement/1087-loopback-cni) will be merged into `development/2.1` 
* [w/2.2/improvement/1087-loopback-cni](https://github.com/scality/metalk8s/compare/development/2.2...w/2.2/improvement/1087-loopback-cni) will be merged into `development/2.2` 



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`




You can set option `create_pull_requests` if you need me to create
**integration pull requests** in addition to integration branches, with:

```
@bert-e create_pull_requests
```

2019-05-06 15:42 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @cmonfort

* @alexandre-allard-scality

* @gdemonet

* @slaperche-scality

* @ramanduh

* @ballot-scality

* @teddyandrieux

* @tcarmet

* @lucieleonard

* @zempashi

* @sayf-eddine-scality

* @carlito-scality

* @jbertran

* @thomasdanan

* @monpote

* @nootal

* @nicolast

* @alxf

2019-05-06 16:21 UTC, NicolasT commented
I guess @xaf-scality could approve this as well ;-)

2019-05-07 06:30 UTC, gdemonet requested changes
A few minor comments on the code itself.

I tried deploying a control-plane node starting from this branch, but the `deploy_new_node` orchestrate probably isn't up-to-date, which got my etcd cluster out of shape (new node expects a different cluster ID than the first one is using). Will investigate further, though it's probably not related to this changeset.

2019-05-07 06:30 UTC, gdemonet commented on salt/metalk8s/kubernetes/cni/loopback/installed.sls
> +{%- from "metalk8s/map.jinja" import repo with context %}
This `repo` variable is unused, right?

2019-05-07 06:30 UTC, gdemonet commented on salt/metalk8s/kubernetes/cni/loopback/init.sls
> +include:
Could we have some really basic documentation in this file? Just to explain the rationale and expected usage of the formula (mostly an alternative to Calico for `hostNetwork`-only nodes IIUC). A later reference to this comment in a "Troubleshooting guide" would be easy to add.

2019-05-07 06:30 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @cmonfort

* @alexandre-allard-scality

* @gdemonet

* @slaperche-scality

* @ramanduh

* @ballot-scality

* @teddyandrieux

* @tcarmet

* @lucieleonard

* @zempashi

* @sayf-eddine-scality

* @carlito-scality

* @jbertran

* @thomasdanan

* @monpote

* @nootal

* @nicolast

* @alxf





The following reviewers are expecting changes from the author, or must review again:

* @gdemonet

2019-05-07 09:27 UTC, NicolasT commented on salt/metalk8s/kubernetes/cni/loopback/installed.sls
> +{%- from "metalk8s/map.jinja" import repo with context %}
Removed

2019-05-07 09:28 UTC, bert-e commented
# History mismatch



Merge commit #30bc45a3498a3aa5feb1a87dc453ca91add8cd0e on the integration branch
`w/2.1/improvement/1087-loopback-cni` is merging a branch which is neither the current
branch `improvement/1087-loopback-cni` nor the development branch
`development/2.1`.

It is likely due to a rebase of the branch `improvement/1087-loopback-cni` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**

2019-05-07 09:28 UTC, NicolasT commented on salt/metalk8s/kubernetes/cni/loopback/init.sls
> +include:
I added the commit-message as a 'docstring' in the SLS.

2019-05-07 09:28 UTC, NicolasT commented
@bert-e reset

2019-05-07 09:28 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.

2019-05-07 09:28 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `improvement/1087-loopback-cni` into
`development/2.0`
* [w/2.1/improvement/1087-loopback-cni](https://github.com/scality/metalk8s/compare/development/2.1...w/2.1/improvement/1087-loopback-cni) will be merged into `development/2.1` 
* [w/2.2/improvement/1087-loopback-cni](https://github.com/scality/metalk8s/compare/development/2.2...w/2.2/improvement/1087-loopback-cni) will be merged into `development/2.2` 



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`




You can set option `create_pull_requests` if you need me to create
**integration pull requests** in addition to integration branches, with:

```
@bert-e create_pull_requests
```

2019-05-07 09:28 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @cmonfort

* @alexandre-allard-scality

* @gdemonet

* @slaperche-scality

* @ramanduh

* @ballot-scality

* @teddyandrieux

* @tcarmet

* @lucieleonard

* @zempashi

* @sayf-eddine-scality

* @carlito-scality

* @jbertran

* @thomasdanan

* @monpote

* @nootal

* @nicolast

* @alxf





The following reviewers are expecting changes from the author, or must review again:

* @gdemonet

2019-05-09 08:35 UTC, gdemonet approved these changes

2019-05-09 08:35 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @cmonfort

* @jbertran

* @monpote

* @alxf

* @gdemonet

* @lucieleonard

* @zempashi

* @carlito-scality

* @alexandre-allard-scality

* @nootal

* @nicolast

* @thomasdanan

* @tcarmet

* @slaperche-scality

* @teddyandrieux

* @sayf-eddine-scality

* @ramanduh

2019-05-09 08:50 UTC, NicolasT commented
@bert-e approve

2019-05-09 08:50 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/2.0`

* :heavy_check_mark: `development/2.1`

* :heavy_check_mark: `development/2.2`



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2019-05-09 09:16 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/2.0`

* :heavy_check_mark: `development/2.1`

* :heavy_check_mark: `development/2.2`



The following branches have **NOT** changed:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`



Please check the status of the associated issue None.

Goodbye nicolast.

2019-05-09 09:16 UTC, merged