Add documentation about changing cluster node hostname
scality/metalk8s pull request #1163
Opened 2019-05-28 13:14 UTC by ycointe

Issue: GH-1162

**Component**:

**Context**: Add documentation

**Summary**: How to change a node hostname in a cluster

**Acceptance criteria**: 

---

Closes: #1162

2019-05-31 09:20 UTC, slaperche-scality requested changes

2019-05-31 09:20 UTC, slaperche-scality commented on docs/changenodehostname.rst
> +Change the hostname of one of a cluster node:
No `:` in a title

And could be written as `Change the hostname of a cluster node`

2019-05-31 09:20 UTC, slaperche-scality commented on docs/changenodehostname.rst
> +On the node:
ditto, no `:`

2019-05-31 09:20 UTC, slaperche-scality commented on docs/changenodehostname.rst
> +        $ systemctl restart systemd-hostnamed
Do we really need to restart the service?

2019-05-31 09:20 UTC, slaperche-scality commented on docs/changenodehostname.rst
> +On the bootstrap:
`On the bootstrap node` (and no `:`)

2019-05-31 09:20 UTC, slaperche-scality commented on docs/changenodehostname.rst
> +Change the name of the node in the yaml file used to created it
s/yaml/YAML/

2019-05-31 09:20 UTC, slaperche-scality commented on docs/changenodehostname.rst
> +          name: controlplane2
maybe using `<NEW HOSTNAME>` would make more visible which place needs to be updated.

2019-05-31 09:20 UTC, slaperche-scality commented on docs/changenodehostname.rst
> +Delete the hold node (here node2.novalocal):
s/hold/old/, and use quote around the hostname ` ``node2.novalocal`` `

2019-05-31 09:20 UTC, slaperche-scality commented on docs/changenodehostname.rst
> +On the Control Plane node delete the certificates :
No space before `:`

2019-05-31 09:20 UTC, slaperche-scality commented on docs/changenodehostname.rst
> +Verify the hostname change occur a status change on the bootstrap:
What do you mean here?

2019-05-31 09:20 UTC, slaperche-scality commented on docs/changenodehostname.rst
> +Verify if the change is done:
`Check that the hostname has changed`?

2019-06-04 11:17 UTC, ycointe commented on docs/changenodehostname.rst
> +        $ systemctl restart systemd-hostnamed
According the documentation I read, yes, it's necessary for the persistence, especially in case of reboot.

2019-06-04 12:51 UTC, ycointe commented
Changes and corrections done.

2019-06-04 13:11 UTC, slaperche-scality approved these changes

2019-06-04 14:08 UTC, ycointe commented
Decline due to the wrong branch name.

2019-06-04 14:08 UTC, closed without merging