Archive containerd-supported images tarballs
scality/metalk8s pull request #1253
Opened 2019-06-18 14:42 UTC by sayf-eddine-scality

Fixes: #1250

**Component**:
build

**Context**: 
container image build
**Summary**:
Skopeo produces incompatible tarballs with containerd thus we re
replacing it with docker in that step, the normal image (no tarballs
should stay the same)
**Acceptance criteria**: 
containerd should be able to import the produced images (nginx and pause)

---

Closes: #1250 

See: #942

2019-06-18 14:42 UTC, bert-e commented
# Hello sayf-eddine-scality,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/metalk8s/bert-e/doc/user).





*Status report is not available.*

2019-06-18 14:42 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `bugfix/1250-tar-container-image-support-containerd` into
`development/2.0`
* [w/2.1/bugfix/1250-tar-container-image-support-containerd](https://github.com/scality/metalk8s/compare/development/2.1...w/2.1/bugfix/1250-tar-container-image-support-containerd) will be merged into `development/2.1` 
* [w/2.2/bugfix/1250-tar-container-image-support-containerd](https://github.com/scality/metalk8s/compare/development/2.2...w/2.2/bugfix/1250-tar-container-image-support-containerd) will be merged into `development/2.2` 



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`




You can set option `create_pull_requests` if you need me to create
**integration pull requests** in addition to integration branches, with:

```
@bert-e create_pull_requests
```

2019-06-18 14:42 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @jbertran

* @nootal

* @cmonfort

* @lucieleonard

* @alxf

* @carlito-scality

* @alexandre-allard-scality

* @teddyandrieux

* @slaperche-scality

* @thomasdanan

* @zempashi

* @nicolast

* @sayf-eddine-scality

* @monpote

* @gdemonet

* @tcarmet

2019-06-18 14:50 UTC, TeddyAndrieux submitted a review, later dismissed

2019-06-18 14:57 UTC, slaperche-scality requested changes

2019-06-18 14:57 UTC, slaperche-scality commented on buildchain/buildchain/targets/remote_image.py
> +    def _docker_pull(self) -> List[str]:
No, we don't want to use `docker` directly anymore.

We should use the API, @jbertran did the work.

You can restore the code that was removed from my PR.

2019-06-18 14:57 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @jbertran

* @nootal

* @cmonfort

* @lucieleonard

* @alxf

* @carlito-scality

* @alexandre-allard-scality

* @teddyandrieux

* @slaperche-scality

* @thomasdanan

* @zempashi

* @nicolast

* @sayf-eddine-scality

* @monpote

* @gdemonet

* @tcarmet





The following reviewers are expecting changes from the author, or must review again:

* @slaperche-scality

2019-06-18 14:57 UTC, slaperche-scality commented on buildchain/buildchain/targets/remote_image.py
> +    def _docker_pull(self) -> List[str]:
See 396d60824825b9fb7792d1e18e8be3504fc2c24e

2019-06-18 14:59 UTC, slaperche-scality commented on buildchain/buildchain/targets/remote_image.py
> +                'actions': [self._docker_pull(), self._docker_save()],
IIRC, we need a `tag` between the `pull` and the `save`.

2019-06-18 15:17 UTC, bert-e commented
# History mismatch



Merge commit #7d017abd6f0241d3c320cc150e1e0c070ab588f3 on the integration branch
`w/2.1/bugfix/1250-tar-container-image-support-containerd` is merging a branch which is neither the current
branch `bugfix/1250-tar-container-image-support-containerd` nor the development branch
`development/2.1`.

It is likely due to a rebase of the branch `bugfix/1250-tar-container-image-support-containerd` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**

2019-06-18 17:04 UTC, NicolasT commented
So, I assume `skopeo`s `oci-archive` output doesn't cut it? :disappointed: (CC @rhatdan)

2019-06-18 19:04 UTC, sayf-eddine-scality commented
Yes the image tarball is made and ctr doesnt complain about any error but it says `unpacking 0 images` ...

2019-06-19 12:42 UTC, sayf-eddine-scality commented
@bert-e reset

2019-06-19 12:42 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.

2019-06-19 12:42 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `bugfix/1250-tar-container-image-support-containerd` into
`development/2.0`
* [w/2.1/bugfix/1250-tar-container-image-support-containerd](https://github.com/scality/metalk8s/compare/development/2.1...w/2.1/bugfix/1250-tar-container-image-support-containerd) will be merged into `development/2.1` 
* [w/2.2/bugfix/1250-tar-container-image-support-containerd](https://github.com/scality/metalk8s/compare/development/2.2...w/2.2/bugfix/1250-tar-container-image-support-containerd) will be merged into `development/2.2` 



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`




You can set option `create_pull_requests` if you need me to create
**integration pull requests** in addition to integration branches, with:

```
@bert-e create_pull_requests
```

2019-06-19 12:42 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @jbertran

* @nootal

* @cmonfort

* @lucieleonard

* @alxf

* @carlito-scality

* @alexandre-allard-scality

* @teddyandrieux

* @slaperche-scality

* @thomasdanan

* @zempashi

* @nicolast

* @sayf-eddine-scality

* @monpote

* @gdemonet

* @tcarmet





The following reviewers are expecting changes from the author, or must review again:

* @slaperche-scality

2019-06-19 12:42 UTC, sayf-eddine-scality commented
@bert-e approve

2019-06-19 12:42 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @jbertran

* @nootal

* @cmonfort

* @lucieleonard

* @alxf

* @carlito-scality

* @alexandre-allard-scality

* @teddyandrieux

* @slaperche-scality

* @thomasdanan

* @zempashi

* @nicolast

* @sayf-eddine-scality

* @monpote

* @gdemonet

* @tcarmet





The following reviewers are expecting changes from the author, or must review again:

* @slaperche-scality







*The following options are set:* **approve**

2019-06-19 12:52 UTC, bert-e commented
# History mismatch



Merge commit #06c28bc22f8eb2c09997e3a71044e69d89690265 on the integration branch
`w/2.1/bugfix/1250-tar-container-image-support-containerd` is merging a branch which is neither the current
branch `bugfix/1250-tar-container-image-support-containerd` nor the development branch
`development/2.1`.

It is likely due to a rebase of the branch `bugfix/1250-tar-container-image-support-containerd` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**





*The following options are set:* **approve**

2019-06-19 12:52 UTC, sayf-eddine-scality commented
@bert-e reset

2019-06-19 12:52 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.






*The following options are set:* **approve**

2019-06-19 12:52 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `bugfix/1250-tar-container-image-support-containerd` into
`development/2.0`
* [w/2.1/bugfix/1250-tar-container-image-support-containerd](https://github.com/scality/metalk8s/compare/development/2.1...w/2.1/bugfix/1250-tar-container-image-support-containerd) will be merged into `development/2.1` 
* [w/2.2/bugfix/1250-tar-container-image-support-containerd](https://github.com/scality/metalk8s/compare/development/2.2...w/2.2/bugfix/1250-tar-container-image-support-containerd) will be merged into `development/2.2` 



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`




You can set option `create_pull_requests` if you need me to create
**integration pull requests** in addition to integration branches, with:

```
@bert-e create_pull_requests
```







*The following options are set:* **approve**

2019-06-19 12:52 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @jbertran

* @nootal

* @cmonfort

* @lucieleonard

* @alxf

* @carlito-scality

* @alexandre-allard-scality

* @teddyandrieux

* @slaperche-scality

* @thomasdanan

* @zempashi

* @nicolast

* @sayf-eddine-scality

* @monpote

* @gdemonet

* @tcarmet





The following reviewers are expecting changes from the author, or must review again:

* @slaperche-scality







*The following options are set:* **approve**

2019-06-19 12:59 UTC, bert-e commented
# History mismatch



Merge commit #6d737e9fb516a3ef2257bdf698080697eeb3b0d8 on the integration branch
`w/2.1/bugfix/1250-tar-container-image-support-containerd` is merging a branch which is neither the current
branch `bugfix/1250-tar-container-image-support-containerd` nor the development branch
`development/2.1`.

It is likely due to a rebase of the branch `bugfix/1250-tar-container-image-support-containerd` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**





*The following options are set:* **approve**

2019-06-19 13:01 UTC, sayf-eddine-scality commented
@bert-e reset

2019-06-19 13:01 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.






*The following options are set:* **approve**

2019-06-19 13:01 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `bugfix/1250-tar-container-image-support-containerd` into
`development/2.0`
* [w/2.1/bugfix/1250-tar-container-image-support-containerd](https://github.com/scality/metalk8s/compare/development/2.1...w/2.1/bugfix/1250-tar-container-image-support-containerd) will be merged into `development/2.1` 
* [w/2.2/bugfix/1250-tar-container-image-support-containerd](https://github.com/scality/metalk8s/compare/development/2.2...w/2.2/bugfix/1250-tar-container-image-support-containerd) will be merged into `development/2.2` 



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`




You can set option `create_pull_requests` if you need me to create
**integration pull requests** in addition to integration branches, with:

```
@bert-e create_pull_requests
```







*The following options are set:* **approve**

2019-06-19 13:01 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @jbertran

* @nootal

* @cmonfort

* @lucieleonard

* @alxf

* @carlito-scality

* @alexandre-allard-scality

* @teddyandrieux

* @slaperche-scality

* @thomasdanan

* @zempashi

* @nicolast

* @sayf-eddine-scality

* @monpote

* @gdemonet

* @tcarmet





The following reviewers are expecting changes from the author, or must review again:

* @slaperche-scality







*The following options are set:* **approve**

2019-06-19 13:03 UTC, slaperche-scality submitted a review, later dismissed

2019-06-19 13:03 UTC, slaperche-scality commented on buildchain/buildchain/docker_command.py
> +# The call method is not counted as a public method
Skip two lines between `DockerRun` and `DockerTag`.

2019-06-19 13:03 UTC, slaperche-scality commented on buildchain/buildchain/docker_command.py
> +# pylint: disable=too-few-public-methods
To disable the warning only for the class, the correct syntax is:

```
class DockerTag:
    # pylint: disable=too-few-public-methods
    """A class to expose the `docker tag` command through the API client."""
```

(yeah it was wrong before, we noticed later in another Jordi's PR).

2019-06-19 14:44 UTC, bert-e commented
# History mismatch



Merge commit #87946f06102e7935789678f84066916d958f38a5 on the integration branch
`w/2.1/bugfix/1250-tar-container-image-support-containerd` is merging a branch which is neither the current
branch `bugfix/1250-tar-container-image-support-containerd` nor the development branch
`development/2.1`.

It is likely due to a rebase of the branch `bugfix/1250-tar-container-image-support-containerd` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**





*The following options are set:* **approve**

2019-06-19 14:48 UTC, sayf-eddine-scality commented
@bert-e reset

2019-06-19 14:48 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.






*The following options are set:* **approve**

2019-06-19 14:48 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `bugfix/1250-tar-container-image-support-containerd` into
`development/2.0`
* [w/2.1/bugfix/1250-tar-container-image-support-containerd](https://github.com/scality/metalk8s/compare/development/2.1...w/2.1/bugfix/1250-tar-container-image-support-containerd) will be merged into `development/2.1` 
* [w/2.2/bugfix/1250-tar-container-image-support-containerd](https://github.com/scality/metalk8s/compare/development/2.2...w/2.2/bugfix/1250-tar-container-image-support-containerd) will be merged into `development/2.2` 



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`




You can set option `create_pull_requests` if you need me to create
**integration pull requests** in addition to integration branches, with:

```
@bert-e create_pull_requests
```







*The following options are set:* **approve**

2019-06-19 14:48 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @jbertran

* @nootal

* @cmonfort

* @lucieleonard

* @alxf

* @carlito-scality

* @alexandre-allard-scality

* @teddyandrieux

* @slaperche-scality

* @thomasdanan

* @zempashi

* @nicolast

* @sayf-eddine-scality

* @monpote

* @gdemonet

* @tcarmet





The following reviewers are expecting changes from the author, or must review again:

* @slaperche-scality







*The following options are set:* **approve**

2019-06-19 14:54 UTC, bert-e commented
# History mismatch



Merge commit #f6e8dfb688b2bf15f8011687b54c9a5c88d2215c on the integration branch
`w/2.1/bugfix/1250-tar-container-image-support-containerd` is merging a branch which is neither the current
branch `bugfix/1250-tar-container-image-support-containerd` nor the development branch
`development/2.1`.

It is likely due to a rebase of the branch `bugfix/1250-tar-container-image-support-containerd` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**





*The following options are set:* **approve**

2019-06-19 14:56 UTC, sayf-eddine-scality commented
@bert-e reset

2019-06-19 14:56 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.






*The following options are set:* **approve**

2019-06-19 14:56 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `bugfix/1250-tar-container-image-support-containerd` into
`development/2.0`
* [w/2.1/bugfix/1250-tar-container-image-support-containerd](https://github.com/scality/metalk8s/compare/development/2.1...w/2.1/bugfix/1250-tar-container-image-support-containerd) will be merged into `development/2.1` 
* [w/2.2/bugfix/1250-tar-container-image-support-containerd](https://github.com/scality/metalk8s/compare/development/2.2...w/2.2/bugfix/1250-tar-container-image-support-containerd) will be merged into `development/2.2` 



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`




You can set option `create_pull_requests` if you need me to create
**integration pull requests** in addition to integration branches, with:

```
@bert-e create_pull_requests
```







*The following options are set:* **approve**

2019-06-19 14:56 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @jbertran

* @nootal

* @cmonfort

* @lucieleonard

* @alxf

* @carlito-scality

* @alexandre-allard-scality

* @teddyandrieux

* @slaperche-scality

* @thomasdanan

* @zempashi

* @nicolast

* @sayf-eddine-scality

* @monpote

* @gdemonet

* @tcarmet





The following reviewers are expecting changes from the author, or must review again:

* @slaperche-scality







*The following options are set:* **approve**

2019-06-20 09:59 UTC, bert-e commented
# History mismatch



Merge commit #37073346b89b7350b7b7991166b8ebac484e4061 on the integration branch
`w/2.1/bugfix/1250-tar-container-image-support-containerd` is merging a branch which is neither the current
branch `bugfix/1250-tar-container-image-support-containerd` nor the development branch
`development/2.1`.

It is likely due to a rebase of the branch `bugfix/1250-tar-container-image-support-containerd` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**

2019-06-20 10:32 UTC, sayf-eddine-scality commented
@bert-e reset

2019-06-20 10:32 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.

2019-06-20 10:32 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `bugfix/1250-tar-container-image-support-containerd` into
`development/2.0`
* [w/2.1/bugfix/1250-tar-container-image-support-containerd](https://github.com/scality/metalk8s/compare/development/2.1...w/2.1/bugfix/1250-tar-container-image-support-containerd) will be merged into `development/2.1` 
* [w/2.2/bugfix/1250-tar-container-image-support-containerd](https://github.com/scality/metalk8s/compare/development/2.2...w/2.2/bugfix/1250-tar-container-image-support-containerd) will be merged into `development/2.2` 



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`




You can set option `create_pull_requests` if you need me to create
**integration pull requests** in addition to integration branches, with:

```
@bert-e create_pull_requests
```

2019-06-20 10:32 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @jbertran

* @nootal

* @cmonfort

* @lucieleonard

* @alxf

* @carlito-scality

* @alexandre-allard-scality

* @teddyandrieux

* @slaperche-scality

* @thomasdanan

* @zempashi

* @nicolast

* @sayf-eddine-scality

* @monpote

* @gdemonet

* @tcarmet





The following reviewers are expecting changes from the author, or must review again:

* @slaperche-scality

2019-06-20 10:32 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @jbertran

* @nootal

* @cmonfort

* @lucieleonard

* @alxf

* @carlito-scality

* @alexandre-allard-scality

* @teddyandrieux

* @slaperche-scality

* @thomasdanan

* @zempashi

* @nicolast

* @sayf-eddine-scality

* @monpote

* @gdemonet

* @tcarmet

2019-06-20 10:57 UTC, slaperche-scality approved these changes

2019-06-20 11:18 UTC, sayf-eddine-scality commented
@bert-e approve

2019-06-20 11:19 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/2.0`

* :heavy_check_mark: `development/2.1`

* :heavy_check_mark: `development/2.2`



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2019-06-20 11:52 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/2.0`

* :heavy_check_mark: `development/2.1`

* :heavy_check_mark: `development/2.2`



The following branches have **NOT** changed:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`



Please check the status of the associated issue None.

Goodbye sayf-eddine-scality.

2019-06-20 11:52 UTC, merged