buildchain: provide more error output in container run/build crashes
scality/metalk8s pull request #1264
Opened 2019-06-20 15:44 UTC by jbertran

**Component**:

buildchain

**Context**: 

More verbose docker errors.

**Summary**:

* More verbose `ContainerError` (`docker run`)
* More verbose `BuildError` (`docker build`)

**Acceptance criteria**: 

More verbose errors.

---

Closes: #1263

2019-06-20 15:44 UTC, bert-e commented
# Hello jbertran,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/metalk8s/bert-e/doc/user).





*Status report is not available.*

2019-06-20 15:44 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `improvement/1263-more-error-output-in-container-run-build` into
`development/2.0`
* [w/2.1/improvement/1263-more-error-output-in-container-run-build](https://github.com/scality/metalk8s/compare/development/2.1...w/2.1/improvement/1263-more-error-output-in-container-run-build) will be merged into `development/2.1` 
* [w/2.2/improvement/1263-more-error-output-in-container-run-build](https://github.com/scality/metalk8s/compare/development/2.2...w/2.2/improvement/1263-more-error-output-in-container-run-build) will be merged into `development/2.2` 



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`




You can set option `create_pull_requests` if you need me to create
**integration pull requests** in addition to integration branches, with:

```
@bert-e create_pull_requests
```

2019-06-20 15:45 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @jbertran

* @nootal

* @cmonfort

* @lucieleonard

* @alxf

* @carlito-scality

* @alexandre-allard-scality

* @teddyandrieux

* @slaperche-scality

* @thomasdanan

* @zempashi

* @nicolast

* @sayf-eddine-scality

* @monpote

* @gdemonet

* @tcarmet

2019-06-24 11:04 UTC, bert-e commented
# History mismatch



Merge commit #3d83fae986ef00f7ad258f95ffda2da5c9415730 on the integration branch
`w/2.1/improvement/1263-more-error-output-in-container-run-build` is merging a branch which is neither the current
branch `improvement/1263-more-error-output-in-container-run-build` nor the development branch
`development/2.1`.

It is likely due to a rebase of the branch `improvement/1263-more-error-output-in-container-run-build` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**

2019-06-24 15:35 UTC, jbertran commented
@bert-e reset

2019-06-24 15:35 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.

2019-06-24 15:35 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `improvement/1263-more-error-output-in-container-run-build` into
`development/2.0`
* [w/2.1/improvement/1263-more-error-output-in-container-run-build](https://github.com/scality/metalk8s/compare/development/2.1...w/2.1/improvement/1263-more-error-output-in-container-run-build) will be merged into `development/2.1` 
* [w/2.2/improvement/1263-more-error-output-in-container-run-build](https://github.com/scality/metalk8s/compare/development/2.2...w/2.2/improvement/1263-more-error-output-in-container-run-build) will be merged into `development/2.2` 



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`




You can set option `create_pull_requests` if you need me to create
**integration pull requests** in addition to integration branches, with:

```
@bert-e create_pull_requests
```

2019-06-24 15:35 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @jbertran

* @nootal

* @cmonfort

* @lucieleonard

* @alxf

* @carlito-scality

* @alexandre-allard-scality

* @teddyandrieux

* @slaperche-scality

* @thomasdanan

* @zempashi

* @nicolast

* @sayf-eddine-scality

* @monpote

* @gdemonet

* @tcarmet

2019-06-26 12:52 UTC, bert-e commented
# History mismatch



Merge commit #24491731fb2bd37efa962c6ba868abd0162ad606 on the integration branch
`w/2.1/improvement/1263-more-error-output-in-container-run-build` is merging a branch which is neither the current
branch `improvement/1263-more-error-output-in-container-run-build` nor the development branch
`development/2.1`.

It is likely due to a rebase of the branch `improvement/1263-more-error-output-in-container-run-build` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**

2019-06-26 13:02 UTC, gdemonet submitted a review, later dismissed
LGTM - may want to refactor this when we move to `buildah`

2019-06-26 13:35 UTC, gdemonet submitted a review, later dismissed
Perfect!

2019-06-26 15:56 UTC, jbertran commented
@bert-e reset

2019-06-26 15:56 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.

2019-06-26 15:56 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `improvement/1263-more-error-output-in-container-run-build` into
`development/2.0`
* [w/2.1/improvement/1263-more-error-output-in-container-run-build](https://github.com/scality/metalk8s/compare/development/2.1...w/2.1/improvement/1263-more-error-output-in-container-run-build) will be merged into `development/2.1` 
* [w/2.2/improvement/1263-more-error-output-in-container-run-build](https://github.com/scality/metalk8s/compare/development/2.2...w/2.2/improvement/1263-more-error-output-in-container-run-build) will be merged into `development/2.2` 



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`




You can set option `create_pull_requests` if you need me to create
**integration pull requests** in addition to integration branches, with:

```
@bert-e create_pull_requests
```

2019-06-26 15:56 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @jbertran

* @nootal

* @cmonfort

* @lucieleonard

* @alxf

* @carlito-scality

* @alexandre-allard-scality

* @teddyandrieux

* @slaperche-scality

* @thomasdanan

* @zempashi

* @nicolast

* @sayf-eddine-scality

* @monpote

* @gdemonet

* @tcarmet

2019-06-27 07:21 UTC, slaperche-scality requested changes
Your last commit really make the code more legible :)

2019-06-27 07:21 UTC, slaperche-scality commented on buildchain/buildchain/docker_command.py
> +                    err_msg = '{}. Build log:\n{}'.format(str(err), log)
Why not `err_msg = '{}:\n{}'.format(str(err), log)` to be consistent with `ContainerError`?
Or use sth like `err_msg = '{}. Exec error:\n{}'.format(str(err), err.stderr)` for `ContainerError`

2019-06-27 07:21 UTC, slaperche-scality commented on buildchain/buildchain/docker_command.py
> +        expected_exn: Type[Exception],
minor: continuation line are usually indented by four spaces in this file.

2019-06-27 07:21 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @jbertran

* @nootal

* @cmonfort

* @lucieleonard

* @alxf

* @carlito-scality

* @alexandre-allard-scality

* @teddyandrieux

* @slaperche-scality

* @thomasdanan

* @zempashi

* @nicolast

* @sayf-eddine-scality

* @monpote

* @gdemonet

* @tcarmet





The following reviewers are expecting changes from the author, or must review again:

* @slaperche-scality

2019-06-27 09:59 UTC, bert-e commented
# History mismatch



Merge commit #57fc681f8687ad6e57bcb9ffcac2cf21426c70fd on the integration branch
`w/2.1/improvement/1263-more-error-output-in-container-run-build` is merging a branch which is neither the current
branch `improvement/1263-more-error-output-in-container-run-build` nor the development branch
`development/2.1`.

It is likely due to a rebase of the branch `improvement/1263-more-error-output-in-container-run-build` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**

2019-06-27 10:00 UTC, jbertran commented
@bert-e reset

2019-06-27 10:00 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.

2019-06-27 10:00 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `improvement/1263-more-error-output-in-container-run-build` into
`development/2.0`
* [w/2.1/improvement/1263-more-error-output-in-container-run-build](https://github.com/scality/metalk8s/compare/development/2.1...w/2.1/improvement/1263-more-error-output-in-container-run-build) will be merged into `development/2.1` 
* [w/2.2/improvement/1263-more-error-output-in-container-run-build](https://github.com/scality/metalk8s/compare/development/2.2...w/2.2/improvement/1263-more-error-output-in-container-run-build) will be merged into `development/2.2` 



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`




You can set option `create_pull_requests` if you need me to create
**integration pull requests** in addition to integration branches, with:

```
@bert-e create_pull_requests
```

2019-06-27 10:00 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @jbertran

* @nootal

* @cmonfort

* @lucieleonard

* @alxf

* @carlito-scality

* @alexandre-allard-scality

* @teddyandrieux

* @slaperche-scality

* @thomasdanan

* @zempashi

* @nicolast

* @sayf-eddine-scality

* @monpote

* @gdemonet

* @tcarmet





The following reviewers are expecting changes from the author, or must review again:

* @slaperche-scality

2019-06-27 11:52 UTC, bert-e commented
# History mismatch



Merge commit #e57a87118a5aa870655c3654571bb237c35b9702 on the integration branch
`w/2.1/improvement/1263-more-error-output-in-container-run-build` is merging a branch which is neither the current
branch `improvement/1263-more-error-output-in-container-run-build` nor the development branch
`development/2.1`.

It is likely due to a rebase of the branch `improvement/1263-more-error-output-in-container-run-build` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**

2019-06-27 11:58 UTC, slaperche-scality approved these changes

2019-06-27 11:59 UTC, jbertran commented
@bert-e reset

2019-06-27 11:59 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.

2019-06-27 11:59 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `improvement/1263-more-error-output-in-container-run-build` into
`development/2.0`
* [w/2.1/improvement/1263-more-error-output-in-container-run-build](https://github.com/scality/metalk8s/compare/development/2.1...w/2.1/improvement/1263-more-error-output-in-container-run-build) will be merged into `development/2.1` 
* [w/2.2/improvement/1263-more-error-output-in-container-run-build](https://github.com/scality/metalk8s/compare/development/2.2...w/2.2/improvement/1263-more-error-output-in-container-run-build) will be merged into `development/2.2` 



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`




You can set option `create_pull_requests` if you need me to create
**integration pull requests** in addition to integration branches, with:

```
@bert-e create_pull_requests
```

2019-06-27 11:59 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @jbertran

* @nootal

* @cmonfort

* @lucieleonard

* @alxf

* @carlito-scality

* @alexandre-allard-scality

* @teddyandrieux

* @slaperche-scality

* @thomasdanan

* @zempashi

* @nicolast

* @sayf-eddine-scality

* @monpote

* @gdemonet

* @tcarmet

2019-06-27 12:00 UTC, jbertran commented
@bert-e approve

2019-06-27 12:20 UTC, bert-e commented
# Build failed



The build for [commit](https://github.com/scality/metalk8s/commit/eeaf06c9e2b0b4235cb5909bce55e734f3531a85) did not succeed in branch improvement/1263-more-error-output-in-container-run-build.




*The following options are set:* **approve**

2019-06-27 13:39 UTC, bert-e commented
# Build failed



The build for [commit](https://github.com/scality/metalk8s/commit/9ef87dfbc9390737a15ec8b100860ac64930c0f0) did not succeed in branch w/2.2/improvement/1263-more-error-output-in-container-run-build.




*The following options are set:* **approve**

2019-06-27 14:18 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/2.0`

* :heavy_check_mark: `development/2.1`

* :heavy_check_mark: `development/2.2`



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2019-06-27 15:00 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/2.0`

* :heavy_check_mark: `development/2.1`

* :heavy_check_mark: `development/2.2`



The following branches have **NOT** changed:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`



Please check the status of the associated issue None.

Goodbye jbertran.

2019-06-27 15:00 UTC, merged