ci: split IP reporting and debug `sleep` command
scality/metalk8s pull request #1315
Opened 2019-06-26 16:26 UTC by jbertran

Issue: #1308

**Component**: CI

**Context**: 

The SSH key deployment step/IP reporting can be useful to always have, in case the build hangs.

**Summary**:

* Split debug step into SSH key installation/IP report and actual debug sleep step.
* Make SSH/IP step referenceable.

**Acceptance criteria**: 

Single- and multi-node deployments both report the IP of their Openstack worker at the beginning of their stage.

Debug steps are positioned __before__ any resource destruction.

---

Closes: #1308

2019-06-26 16:26 UTC, bert-e commented
# Hello jbertran,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/metalk8s/bert-e/doc/user).





*Status report is not available.*

2019-06-26 16:27 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `improvement/1308-ip-ssh-step-always-runs` into
`development/2.0`
* [w/2.1/improvement/1308-ip-ssh-step-always-runs](https://github.com/scality/metalk8s/compare/development/2.1...w/2.1/improvement/1308-ip-ssh-step-always-runs) will be merged into `development/2.1` 
* [w/2.2/improvement/1308-ip-ssh-step-always-runs](https://github.com/scality/metalk8s/compare/development/2.2...w/2.2/improvement/1308-ip-ssh-step-always-runs) will be merged into `development/2.2` 



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`




You can set option `create_pull_requests` if you need me to create
**integration pull requests** in addition to integration branches, with:

```
@bert-e create_pull_requests
```

2019-06-26 16:27 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @jbertran

* @nootal

* @cmonfort

* @lucieleonard

* @alxf

* @carlito-scality

* @alexandre-allard-scality

* @teddyandrieux

* @slaperche-scality

* @thomasdanan

* @zempashi

* @nicolast

* @sayf-eddine-scality

* @monpote

* @gdemonet

* @tcarmet

2019-06-27 06:49 UTC, slaperche-scality requested changes
Missing commit message explaining what/why we're doing that

2019-06-27 06:50 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @jbertran

* @nootal

* @cmonfort

* @lucieleonard

* @alxf

* @carlito-scality

* @alexandre-allard-scality

* @teddyandrieux

* @slaperche-scality

* @thomasdanan

* @zempashi

* @nicolast

* @sayf-eddine-scality

* @monpote

* @gdemonet

* @tcarmet





The following reviewers are expecting changes from the author, or must review again:

* @slaperche-scality

2019-06-27 08:08 UTC, gdemonet submitted a review, later dismissed

2019-06-27 08:30 UTC, bert-e commented
# History mismatch



Merge commit #cc68a21ce14b74cfd8ef0d43f1470a3a7230c9c7 on the integration branch
`w/2.1/improvement/1308-ip-ssh-step-always-runs` is merging a branch which is neither the current
branch `improvement/1308-ip-ssh-step-always-runs` nor the development branch
`development/2.1`.

It is likely due to a rebase of the branch `improvement/1308-ip-ssh-step-always-runs` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**

2019-06-27 08:58 UTC, slaperche-scality submitted a review, later dismissed

2019-06-27 09:00 UTC, jbertran commented
@bert-e approve

2019-06-27 09:01 UTC, bert-e commented
# History mismatch



Merge commit #cc68a21ce14b74cfd8ef0d43f1470a3a7230c9c7 on the integration branch
`w/2.1/improvement/1308-ip-ssh-step-always-runs` is merging a branch which is neither the current
branch `improvement/1308-ip-ssh-step-always-runs` nor the development branch
`development/2.1`.

It is likely due to a rebase of the branch `improvement/1308-ip-ssh-step-always-runs` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**





*The following options are set:* **approve**

2019-06-27 09:01 UTC, jbertran commented
@bert-e reset

2019-06-27 09:01 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.






*The following options are set:* **approve**

2019-06-27 09:01 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `improvement/1308-ip-ssh-step-always-runs` into
`development/2.0`
* [w/2.1/improvement/1308-ip-ssh-step-always-runs](https://github.com/scality/metalk8s/compare/development/2.1...w/2.1/improvement/1308-ip-ssh-step-always-runs) will be merged into `development/2.1` 
* [w/2.2/improvement/1308-ip-ssh-step-always-runs](https://github.com/scality/metalk8s/compare/development/2.2...w/2.2/improvement/1308-ip-ssh-step-always-runs) will be merged into `development/2.2` 



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`




You can set option `create_pull_requests` if you need me to create
**integration pull requests** in addition to integration branches, with:

```
@bert-e create_pull_requests
```







*The following options are set:* **approve**

2019-06-27 09:31 UTC, bert-e commented
# Build failed



The build for [commit](https://github.com/scality/metalk8s/commit/09a8263307623d50b28fde68cd6a3071669b0aba) did not succeed in branch w/2.1/improvement/1308-ip-ssh-step-always-runs.




*The following options are set:* **approve**

2019-06-27 12:06 UTC, bert-e commented
# History mismatch



Merge commit #c925cd0271a9ae792672f6131fa8446f19439bbc on the integration branch
`w/2.1/improvement/1308-ip-ssh-step-always-runs` is merging a branch which is neither the current
branch `improvement/1308-ip-ssh-step-always-runs` nor the development branch
`development/2.1`.

It is likely due to a rebase of the branch `improvement/1308-ip-ssh-step-always-runs` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**





*The following options are set:* **approve**

2019-06-27 12:06 UTC, jbertran commented
@bert-e reset

2019-06-27 12:06 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.






*The following options are set:* **approve**

2019-06-27 12:06 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `improvement/1308-ip-ssh-step-always-runs` into
`development/2.0`
* [w/2.1/improvement/1308-ip-ssh-step-always-runs](https://github.com/scality/metalk8s/compare/development/2.1...w/2.1/improvement/1308-ip-ssh-step-always-runs) will be merged into `development/2.1` 
* [w/2.2/improvement/1308-ip-ssh-step-always-runs](https://github.com/scality/metalk8s/compare/development/2.2...w/2.2/improvement/1308-ip-ssh-step-always-runs) will be merged into `development/2.2` 



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`




You can set option `create_pull_requests` if you need me to create
**integration pull requests** in addition to integration branches, with:

```
@bert-e create_pull_requests
```







*The following options are set:* **approve**

2019-06-27 12:06 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @jbertran

* @nootal

* @cmonfort

* @lucieleonard

* @alxf

* @carlito-scality

* @alexandre-allard-scality

* @teddyandrieux

* @slaperche-scality

* @thomasdanan

* @zempashi

* @nicolast

* @sayf-eddine-scality

* @monpote

* @gdemonet

* @tcarmet










*The following options are set:* **approve**

2019-06-27 13:30 UTC, charlesprost approved these changes

2019-06-27 13:30 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/2.0`

* :heavy_check_mark: `development/2.1`

* :heavy_check_mark: `development/2.2`



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2019-06-27 14:08 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/2.0`

* :heavy_check_mark: `development/2.1`

* :heavy_check_mark: `development/2.2`



The following branches have **NOT** changed:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`



Please check the status of the associated issue None.

Goodbye jbertran.

2019-06-27 14:08 UTC, merged