Feature/1240 edit languages
scality/metalk8s pull request #1381
Opened 2019-07-08 14:43 UTC by ChengYanJin

**Component**:

UI

**Context**: 

The users should be able to select their language preference. 

**Summary**:
![image](https://user-images.githubusercontent.com/18453133/60723396-cc39cf80-9f33-11e9-88fe-0fc14f62274c.png)

**Acceptance criteria**: 

By default, the language is selected based on the browser setting.  Any other language except French will be in English.

You can see the current language in the Navbar. Once you chose your preference, next time you launch the application this language will be showed as default.

2019-07-08 14:43 UTC, bert-e commented
# Hello chengyanjin,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/metalk8s/bert-e/doc/user).





*Status report is not available.*

2019-07-08 14:43 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `feature/1240-Edit-languages` into
`development/2.0`
* [w/2.1/feature/1240-Edit-languages](https://github.com/scality/metalk8s/compare/development/2.1...w/2.1/feature/1240-Edit-languages) will be merged into `development/2.1` 
* [w/2.2/feature/1240-Edit-languages](https://github.com/scality/metalk8s/compare/development/2.2...w/2.2/feature/1240-Edit-languages) will be merged into `development/2.2` 



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`




You can set option `create_pull_requests` if you need me to create
**integration pull requests** in addition to integration branches, with:

```
@bert-e create_pull_requests
```

2019-07-08 14:43 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @jbertran

* @nootal

* @cmonfort

* @lucieleonard

* @alxf

* @carlito-scality

* @alexandre-allard-scality

* @teddyandrieux

* @slaperche-scality

* @thomasdanan

* @zempashi

* @nicolast

* @sayf-eddine-scality

* @monpote

* @gdemonet

* @tcarmet

2019-07-08 15:06 UTC, bert-e commented
# Conflict




There is a conflict between your branch `feature/1240-Edit-languages` and the
destination branch `development/2.0`.

Please resolve the conflict on **the feature branch** (`feature/1240-Edit-languages`).

```bash
 $ git fetch
 $ git checkout origin/feature/1240-Edit-languages
 $ git merge origin/development/2.0
 $ # <intense conflict resolution>
 $ git commit
 $ git push origin HEAD:feature/1240-Edit-languages
```

2019-07-08 16:49 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @jbertran

* @nootal

* @cmonfort

* @lucieleonard

* @alxf

* @carlito-scality

* @alexandre-allard-scality

* @teddyandrieux

* @slaperche-scality

* @thomasdanan

* @zempashi

* @nicolast

* @sayf-eddine-scality

* @monpote

* @gdemonet

* @tcarmet

2019-07-09 08:42 UTC, carlito-scality requested changes

2019-07-09 08:42 UTC, carlito-scality commented on ui/public/config.json
> +    "url": "https://172.21.254.14:6443",
Do not commit it please.

2019-07-09 08:42 UTC, carlito-scality commented on ui/src/containers/Layout.js
> +          this.props.setLang('fr');
You should create a new saga to handle setLang and localStorage because localStorage should be managed in saga like setInitialLanguage

2019-07-09 08:42 UTC, carlito-scality commented on ui/src/containers/Layout.js
> +    let currentLanguage = this.props.language === 'fr' ? 'FR' : 'EN';
You do not need anymore?

2019-07-09 08:42 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @jbertran

* @nootal

* @cmonfort

* @lucieleonard

* @alxf

* @carlito-scality

* @alexandre-allard-scality

* @teddyandrieux

* @slaperche-scality

* @thomasdanan

* @zempashi

* @nicolast

* @sayf-eddine-scality

* @monpote

* @gdemonet

* @tcarmet





The following reviewers are expecting changes from the author, or must review again:

* @carlito-scality

2019-07-09 08:52 UTC, carlito-scality commented on ui/src/ducks/config.js
> +export function* setInitialLanguage() {
need add units tests please

2019-07-09 11:33 UTC, carlito-scality submitted a review, later dismissed

2019-07-09 11:33 UTC, carlito-scality commented on ui/src/ducks/config.js
> +    case SET_LS_LANGUAGE:
We should have one action per reducer. Just call ```yield put(SET_LANG) ``` in setLSLanguage

2019-07-09 11:33 UTC, carlito-scality commented on ui/src/ducks/config.js
> +  localStorage.setItem(
Call ```yield put(SET_LANG)``` to update language and rename the saga  ```updateLanguage```

2019-07-09 11:40 UTC, carlito-scality commented on ui/src/ducks/config.js
> +  const languageLocalStorage = localStorage.getItem('language');
You should create a constant for the key ```language``` since it is duplicated several times

2019-07-09 12:28 UTC, bert-e commented
# History mismatch



Merge commit #c869462d69ead6e29f1c210813d908976d109b83 on the integration branch
`w/2.1/feature/1240-Edit-languages` is merging a branch which is neither the current
branch `feature/1240-Edit-languages` nor the development branch
`development/2.1`.

It is likely due to a rebase of the branch `feature/1240-Edit-languages` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**

2019-07-09 12:32 UTC, bert-e commented
# History mismatch



Merge commit #47a143679a5d23bbf2371b1e79be09064bcc5532 on the integration branch
`w/2.1/feature/1240-Edit-languages` is merging a branch which is neither the current
branch `feature/1240-Edit-languages` nor the development branch
`development/2.1`.

It is likely due to a rebase of the branch `feature/1240-Edit-languages` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**

2019-07-09 13:12 UTC, MonPote commented on ui/src/ducks/config.js
> +export function* setInitialLanguage() {
Let's do that in the next PR. #1387

2019-07-09 13:13 UTC, MonPote submitted a review, later dismissed
LGTM, thx for the review @carlito-scality

2019-07-09 13:18 UTC, ChengYanJin commented
@scality_bert-e approve

2019-07-09 13:19 UTC, ChengYanJin commented
@bert-e approve

2019-07-09 13:19 UTC, bert-e commented
# History mismatch



Merge commit #47a143679a5d23bbf2371b1e79be09064bcc5532 on the integration branch
`w/2.1/feature/1240-Edit-languages` is merging a branch which is neither the current
branch `feature/1240-Edit-languages` nor the development branch
`development/2.1`.

It is likely due to a rebase of the branch `feature/1240-Edit-languages` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**





*The following options are set:* **approve**

2019-07-09 13:20 UTC, ChengYanJin commented
@bert-e reset

2019-07-09 13:20 UTC, bert-e commented
# Lossy reset warning



There seems to be *manual* commits on integration branches (e.g. conflict
resolutions) that will be lost if you chose to *reset*.

**You can use the `force_reset` command if you still want me
to delete those branches.**





*The following options are set:* **approve**

2019-07-09 13:20 UTC, bert-e commented
# History mismatch



Merge commit #47a143679a5d23bbf2371b1e79be09064bcc5532 on the integration branch
`w/2.1/feature/1240-Edit-languages` is merging a branch which is neither the current
branch `feature/1240-Edit-languages` nor the development branch
`development/2.1`.

It is likely due to a rebase of the branch `feature/1240-Edit-languages` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**





*The following options are set:* **approve**

2019-07-09 13:21 UTC, MonPote commented
@bert-e force_reset

2019-07-09 13:21 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.






*The following options are set:* **approve**

2019-07-09 13:21 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `feature/1240-Edit-languages` into
`development/2.0`
* [w/2.1/feature/1240-Edit-languages](https://github.com/scality/metalk8s/compare/development/2.1...w/2.1/feature/1240-Edit-languages) will be merged into `development/2.1` 
* [w/2.2/feature/1240-Edit-languages](https://github.com/scality/metalk8s/compare/development/2.2...w/2.2/feature/1240-Edit-languages) will be merged into `development/2.2` 



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`




You can set option `create_pull_requests` if you need me to create
**integration pull requests** in addition to integration branches, with:

```
@bert-e create_pull_requests
```







*The following options are set:* **approve**

2019-07-09 13:21 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @jbertran

* @nootal

* @cmonfort

* @lucieleonard

* @alxf

* @carlito-scality

* @alexandre-allard-scality

* @teddyandrieux

* @slaperche-scality

* @thomasdanan

* @zempashi

* @nicolast

* @sayf-eddine-scality

* @monpote

* @gdemonet

* @tcarmet





The following reviewers are expecting changes from the author, or must review again:

* @carlito-scality







*The following options are set:* **approve**

2019-07-09 15:19 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @jbertran

* @nootal

* @cmonfort

* @lucieleonard

* @alxf

* @carlito-scality

* @alexandre-allard-scality

* @teddyandrieux

* @slaperche-scality

* @thomasdanan

* @zempashi

* @nicolast

* @sayf-eddine-scality

* @monpote

* @gdemonet

* @tcarmet










*The following options are set:* **approve**

2019-07-09 15:19 UTC, MonPote approved these changes

2019-07-09 15:19 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/2.0`

* :heavy_check_mark: `development/2.1`

* :heavy_check_mark: `development/2.2`



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2019-07-09 15:59 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/2.0`

* :heavy_check_mark: `development/2.1`

* :heavy_check_mark: `development/2.2`



The following branches have **NOT** changed:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`



Please check the status of the associated issue None.

Goodbye chengyanjin.

2019-07-09 16:00 UTC, merged