Correction of the vagrantfile
scality/metalk8s pull request #1414
Opened 2019-07-11 15:39 UTC by ycointe

Permit to install Python2.7 on Ubuntu node
during the VM deployment.

Issue: GH-1413

**Component**:

**Context**: Need python2.7 on Ubuntu nodes for salt minion installation

**Summary**: Permits to have some Ubuntu nodes on Vagrant with python 2.7 installed

**Acceptance criteria**: Have python 2.7 already installed on Ubuntu nodes.

---

Closes: #1413

2019-07-11 15:39 UTC, bert-e commented
# Hello ycointe,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/metalk8s/bert-e/doc/user).





*Status report is not available.*

2019-07-11 15:39 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `bugfix/1413-fix-python-install` into
`development/2.0`
* [w/2.1/bugfix/1413-fix-python-install](https://github.com/scality/metalk8s/compare/development/2.1...w/2.1/bugfix/1413-fix-python-install) will be merged into `development/2.1` 
* [w/2.2/bugfix/1413-fix-python-install](https://github.com/scality/metalk8s/compare/development/2.2...w/2.2/bugfix/1413-fix-python-install) will be merged into `development/2.2` 



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`




You can set option `create_pull_requests` if you need me to create
**integration pull requests** in addition to integration branches, with:

```
@bert-e create_pull_requests
```

2019-07-11 15:39 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @jbertran

* @nootal

* @cmonfort

* @lucieleonard

* @alxf

* @carlito-scality

* @alexandre-allard-scality

* @teddyandrieux

* @slaperche-scality

* @thomasdanan

* @zempashi

* @nicolast

* @sayf-eddine-scality

* @monpote

* @gdemonet

* @tcarmet

2019-07-11 15:54 UTC, jbertran submitted a review, later dismissed

2019-07-11 15:55 UTC, ycointe commented
@bert-e approve

2019-07-11 15:55 UTC, bert-e commented
# Build failed



The build for [commit](https://github.com/scality/metalk8s/commit/a3e6c4539533c14f268de8cb9e1f46340a8d4938) did not succeed in branch w/2.2/bugfix/1413-fix-python-install.




*The following options are set:* **approve**

2019-07-11 17:24 UTC, bert-e commented
# Build failed



The build for [commit](https://github.com/scality/metalk8s/commit/95d7feba73ea0dae54e53d075517f4899a7db54b) did not succeed in branch bugfix/1413-fix-python-install.




*The following options are set:* **approve**

2019-07-11 18:20 UTC, ycointe commented
@bert-e approve

2019-07-11 19:34 UTC, slaperche-scality requested changes
Code LGTM, but commit message could be improved to mention what was the problem (and how we solve it).
Especially since people are not very familiar with Ruby, that can be helpful.

I would suggest something like:

```
vagrant: fix OS comparison

During the review of the previous PR, we replaced the hash keys that
were strings by symbols, which is more idiomatic in Ruby (it's also more
efficient, but we don't care in this specific use case) We updated the
code accordingly (hash lookup) but forgot to fix the comparison.

As a consequence, the condition was always false (because we were
comparing a symbol against a string) and Python was never installed,
even on Ubuntu.

Using a symbol literal instead of a string literal is enough to fix the
issue.
```

2019-07-11 19:34 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @jbertran

* @nootal

* @cmonfort

* @lucieleonard

* @alxf

* @carlito-scality

* @alexandre-allard-scality

* @teddyandrieux

* @slaperche-scality

* @thomasdanan

* @zempashi

* @nicolast

* @sayf-eddine-scality

* @monpote

* @gdemonet

* @tcarmet





The following reviewers are expecting changes from the author, or must review again:

* @slaperche-scality







*The following options are set:* **approve**

2019-07-12 07:16 UTC, ycointe commented
@bert-e reset

2019-07-12 07:16 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.






*The following options are set:* **approve**

2019-07-12 07:16 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `bugfix/1413-fix-python-install` into
`development/2.0`
* [w/2.1/bugfix/1413-fix-python-install](https://github.com/scality/metalk8s/compare/development/2.1...w/2.1/bugfix/1413-fix-python-install) will be merged into `development/2.1` 
* [w/2.2/bugfix/1413-fix-python-install](https://github.com/scality/metalk8s/compare/development/2.2...w/2.2/bugfix/1413-fix-python-install) will be merged into `development/2.2` 



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`




You can set option `create_pull_requests` if you need me to create
**integration pull requests** in addition to integration branches, with:

```
@bert-e create_pull_requests
```







*The following options are set:* **approve**

2019-07-12 07:16 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @jbertran

* @nootal

* @cmonfort

* @lucieleonard

* @alxf

* @carlito-scality

* @alexandre-allard-scality

* @teddyandrieux

* @slaperche-scality

* @thomasdanan

* @zempashi

* @nicolast

* @sayf-eddine-scality

* @monpote

* @gdemonet

* @tcarmet





The following reviewers are expecting changes from the author, or must review again:

* @slaperche-scality







*The following options are set:* **approve**

2019-07-12 07:28 UTC, bert-e commented
# History mismatch



Merge commit #95d7feba73ea0dae54e53d075517f4899a7db54b on the integration branch
`w/2.1/bugfix/1413-fix-python-install` is merging a branch which is neither the current
branch `bugfix/1413-fix-python-install` nor the development branch
`development/2.1`.

It is likely due to a rebase of the branch `bugfix/1413-fix-python-install` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**





*The following options are set:* **approve**

2019-07-12 07:29 UTC, ycointe commented
@bert-e reset

2019-07-12 07:29 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.






*The following options are set:* **approve**

2019-07-12 07:29 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `bugfix/1413-fix-python-install` into
`development/2.0`
* [w/2.1/bugfix/1413-fix-python-install](https://github.com/scality/metalk8s/compare/development/2.1...w/2.1/bugfix/1413-fix-python-install) will be merged into `development/2.1` 
* [w/2.2/bugfix/1413-fix-python-install](https://github.com/scality/metalk8s/compare/development/2.2...w/2.2/bugfix/1413-fix-python-install) will be merged into `development/2.2` 



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`




You can set option `create_pull_requests` if you need me to create
**integration pull requests** in addition to integration branches, with:

```
@bert-e create_pull_requests
```







*The following options are set:* **approve**

2019-07-12 07:29 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @jbertran

* @nootal

* @cmonfort

* @lucieleonard

* @alxf

* @carlito-scality

* @alexandre-allard-scality

* @teddyandrieux

* @slaperche-scality

* @thomasdanan

* @zempashi

* @nicolast

* @sayf-eddine-scality

* @monpote

* @gdemonet

* @tcarmet





The following reviewers are expecting changes from the author, or must review again:

* @slaperche-scality







*The following options are set:* **approve**

2019-07-12 07:29 UTC, slaperche-scality submitted a review, later dismissed

2019-07-12 08:16 UTC, bert-e commented
# Build failed



The build for [commit](https://github.com/scality/metalk8s/commit/52065d0b8813920c988b4f6c6979226a8dee1454) did not succeed in branch bugfix/1413-fix-python-install.




*The following options are set:* **approve**

2019-07-22 07:49 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `bugfix/1413-fix-python-install` into
`development/2.0`
* [w/2.1/bugfix/1413-fix-python-install](https://github.com/scality/metalk8s/compare/development/2.1...w/2.1/bugfix/1413-fix-python-install) will be merged into `development/2.1` 
* [w/2.2/bugfix/1413-fix-python-install](https://github.com/scality/metalk8s/compare/development/2.2...w/2.2/bugfix/1413-fix-python-install) will be merged into `development/2.2` 
* [w/2.3/bugfix/1413-fix-python-install](https://github.com/scality/metalk8s/compare/development/2.3...w/2.3/bugfix/1413-fix-python-install) will be merged into `development/2.3` 
* [w/2.4/bugfix/1413-fix-python-install](https://github.com/scality/metalk8s/compare/development/2.4...w/2.4/bugfix/1413-fix-python-install) will be merged into `development/2.4` 



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`




You can set option `create_pull_requests` if you need me to create
**integration pull requests** in addition to integration branches, with:

```
@bert-e create_pull_requests
```







*The following options are set:* **approve**

2019-07-22 08:19 UTC, bert-e commented
# Build failed



The build for [commit](https://github.com/scality/metalk8s/commit/bf0f8c54eb34c1e9f06731705400834f9d0bf484) did not succeed in branch bugfix/1413-fix-python-install.




*The following options are set:* **approve**

2019-07-22 09:16 UTC, bert-e commented
# Branches have diverged



This pull request's source branch `bugfix/1413-fix-python-install` has diverged from
`development/2.4` by more than 50 commits.

To avoid any integration risks, please re-synchronize them using one of the
following solutions:

* Merge `origin/development/2.4` into `bugfix/1413-fix-python-install`
* Rebase `bugfix/1413-fix-python-install` onto `origin/development/2.4`

Note: If you choose to rebase, you may have to ask me to rebuild
integration branches using the `reset` command.




*The following options are set:* **approve**

2019-07-22 09:18 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @jbertran

* @nootal

* @cmonfort

* @lucieleonard

* @alxf

* @carlito-scality

* @alexandre-allard-scality

* @teddyandrieux

* @slaperche-scality

* @thomasdanan

* @zempashi

* @nicolast

* @sayf-eddine-scality

* @monpote

* @gdemonet

* @tcarmet










*The following options are set:* **approve**

2019-07-22 09:24 UTC, jbertran approved these changes
LGTM!

2019-07-22 09:52 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/2.4`



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`
* `development/2.0`
* `development/2.1`
* `development/2.2`
* `development/2.3`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2019-07-22 19:34 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/2.4`



The following branches have **NOT** changed:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`
* `development/2.0`
* `development/2.1`
* `development/2.2`
* `development/2.3`



Please check the status of the associated issue None.

Goodbye ycointe.

2019-07-22 19:34 UTC, merged