add E2E test to change language feature
scality/metalk8s pull request #1415
Opened 2019-07-12 08:09 UTC by ChengYanJin

**Component**:
ui

**Context**: 
Add E2E test to change the language.

**Summary**:

**Acceptance criteria**: 
`./node_modules/cypress/bin/cypress run -b chrome -s cypress/integration/EditLanguage.feature -e userName=admin,password=admin,delay_after=5000`

In this test, we first set the language of localstorage as English.
And then change the language into French.

2019-07-12 08:09 UTC, bert-e commented
# Hello chengyanjin,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/metalk8s/bert-e/doc/user).





*Status report is not available.*

2019-07-12 08:09 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `improvement/1386-add-E2E-test-for-changing-language` into
`development/2.0`
* [w/2.1/improvement/1386-add-E2E-test-for-changing-language](https://github.com/scality/metalk8s/compare/development/2.1...w/2.1/improvement/1386-add-E2E-test-for-changing-language) will be merged into `development/2.1` 
* [w/2.2/improvement/1386-add-E2E-test-for-changing-language](https://github.com/scality/metalk8s/compare/development/2.2...w/2.2/improvement/1386-add-E2E-test-for-changing-language) will be merged into `development/2.2` 



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`




You can set option `create_pull_requests` if you need me to create
**integration pull requests** in addition to integration branches, with:

```
@bert-e create_pull_requests
```

2019-07-12 08:09 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @jbertran

* @nootal

* @cmonfort

* @lucieleonard

* @alxf

* @carlito-scality

* @alexandre-allard-scality

* @teddyandrieux

* @slaperche-scality

* @thomasdanan

* @zempashi

* @nicolast

* @sayf-eddine-scality

* @monpote

* @gdemonet

* @tcarmet

2019-07-14 12:18 UTC, carlito-scality commented on ui/cypress/integration/common/login.js
> +  cy.wait(delayAfter);
Why do you need a delay?

2019-07-14 12:26 UTC, carlito-scality requested changes

2019-07-14 12:26 UTC, carlito-scality commented on ui/src/containers/Layout.js
> +        'data-cy': 'fr'
use FR_LANG instead of 'fr'

2019-07-14 12:26 UTC, carlito-scality commented on ui/src/containers/Layout.js
> +        'data-cy': 'en'
use EN_LANG instead of 'en'

2019-07-14 12:26 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @jbertran

* @nootal

* @cmonfort

* @lucieleonard

* @alxf

* @carlito-scality

* @alexandre-allard-scality

* @teddyandrieux

* @slaperche-scality

* @thomasdanan

* @zempashi

* @nicolast

* @sayf-eddine-scality

* @monpote

* @gdemonet

* @tcarmet





The following reviewers are expecting changes from the author, or must review again:

* @carlito-scality

2019-07-14 12:35 UTC, carlito-scality commented on ui/cypress/integration/common/editLanguage.js
> +  cy.get('.sc-trigger-text').should('contain', 'FR');
should use ``` cy.get('.sc-dropdown').eq(0).get('.sc-trigger-text')``` instead to be more precise.

2019-07-15 14:06 UTC, bert-e commented
# History mismatch



Merge commit #1cb73871d75810fec609e1a3c2b378977138b5e7 on the integration branch
`w/2.1/improvement/1386-add-E2E-test-for-changing-language` is merging a branch which is neither the current
branch `improvement/1386-add-E2E-test-for-changing-language` nor the development branch
`development/2.1`.

It is likely due to a rebase of the branch `improvement/1386-add-E2E-test-for-changing-language` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**

2019-07-15 14:12 UTC, carlito-scality commented
@bert-e reset

2019-07-15 14:12 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.

2019-07-15 14:12 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `improvement/1386-add-E2E-test-for-changing-language` into
`development/2.0`
* [w/2.1/improvement/1386-add-E2E-test-for-changing-language](https://github.com/scality/metalk8s/compare/development/2.1...w/2.1/improvement/1386-add-E2E-test-for-changing-language) will be merged into `development/2.1` 
* [w/2.2/improvement/1386-add-E2E-test-for-changing-language](https://github.com/scality/metalk8s/compare/development/2.2...w/2.2/improvement/1386-add-E2E-test-for-changing-language) will be merged into `development/2.2` 



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`




You can set option `create_pull_requests` if you need me to create
**integration pull requests** in addition to integration branches, with:

```
@bert-e create_pull_requests
```

2019-07-15 14:12 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @jbertran

* @nootal

* @cmonfort

* @lucieleonard

* @alxf

* @carlito-scality

* @alexandre-allard-scality

* @teddyandrieux

* @slaperche-scality

* @thomasdanan

* @zempashi

* @nicolast

* @sayf-eddine-scality

* @monpote

* @gdemonet

* @tcarmet





The following reviewers are expecting changes from the author, or must review again:

* @carlito-scality

2019-07-15 14:59 UTC, ChengYanJin commented
@bert-e approve

2019-07-15 14:59 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @jbertran

* @nootal

* @cmonfort

* @lucieleonard

* @alxf

* @carlito-scality

* @alexandre-allard-scality

* @teddyandrieux

* @slaperche-scality

* @thomasdanan

* @zempashi

* @nicolast

* @sayf-eddine-scality

* @monpote

* @gdemonet

* @tcarmet





The following reviewers are expecting changes from the author, or must review again:

* @carlito-scality







*The following options are set:* **approve**

2019-07-15 15:36 UTC, carlito-scality approved these changes
LGTM

2019-07-15 16:21 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/2.0`

* :heavy_check_mark: `development/2.1`

* :heavy_check_mark: `development/2.2`



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2019-07-15 17:13 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/2.0`

* :heavy_check_mark: `development/2.1`

* :heavy_check_mark: `development/2.2`



The following branches have **NOT** changed:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`



Please check the status of the associated issue None.

Goodbye chengyanjin.

2019-07-15 17:13 UTC, merged