Add a script to automate product addition and configuration
scality/metalk8s pull request #1430
Opened 2019-07-15 12:31 UTC by sayf-eddine-scality

Fixes: #1401

**Component**: salt, upgrade, downgrade

**Context**: 
The steps to add a product and configure it is very manual, we need a script to automate it
**Summary**:
A script has been added that automate product configurations
**Acceptance criteria**: 
Check the script help and use it to configure a new metalk8s iso

---

Closes: #1401

2019-07-15 12:31 UTC, bert-e commented
# Hello sayf-eddine-scality,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/metalk8s/bert-e/doc/user).





*Status report is not available.*

2019-07-15 12:31 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `improvement/1401-add-script-for-product-management` into
`development/2.0`
* [w/2.1/improvement/1401-add-script-for-product-management](https://github.com/scality/metalk8s/compare/development/2.1...w/2.1/improvement/1401-add-script-for-product-management) will be merged into `development/2.1` 
* [w/2.2/improvement/1401-add-script-for-product-management](https://github.com/scality/metalk8s/compare/development/2.2...w/2.2/improvement/1401-add-script-for-product-management) will be merged into `development/2.2` 



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`




You can set option `create_pull_requests` if you need me to create
**integration pull requests** in addition to integration branches, with:

```
@bert-e create_pull_requests
```

2019-07-15 12:31 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @jbertran

* @nootal

* @cmonfort

* @lucieleonard

* @alxf

* @carlito-scality

* @alexandre-allard-scality

* @teddyandrieux

* @slaperche-scality

* @thomasdanan

* @zempashi

* @nicolast

* @sayf-eddine-scality

* @monpote

* @gdemonet

* @tcarmet

2019-07-15 12:31 UTC, bert-e commented
# History mismatch



Merge commit #2da8fb7d888bbc84606925a8de520efda1c76a20 on the integration branch
`w/2.1/improvement/1401-add-script-for-product-management` is merging a branch which is neither the current
branch `improvement/1401-add-script-for-product-management` nor the development branch
`development/2.1`.

It is likely due to a rebase of the branch `improvement/1401-add-script-for-product-management` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**

2019-07-15 12:32 UTC, sayf-eddine-scality commented
@bert-e reset

2019-07-15 12:32 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.

2019-07-15 12:32 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `improvement/1401-add-script-for-product-management` into
`development/2.0`
* [w/2.1/improvement/1401-add-script-for-product-management](https://github.com/scality/metalk8s/compare/development/2.1...w/2.1/improvement/1401-add-script-for-product-management) will be merged into `development/2.1` 
* [w/2.2/improvement/1401-add-script-for-product-management](https://github.com/scality/metalk8s/compare/development/2.2...w/2.2/improvement/1401-add-script-for-product-management) will be merged into `development/2.2` 



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`




You can set option `create_pull_requests` if you need me to create
**integration pull requests** in addition to integration branches, with:

```
@bert-e create_pull_requests
```

2019-07-15 12:32 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @jbertran

* @nootal

* @cmonfort

* @lucieleonard

* @alxf

* @carlito-scality

* @alexandre-allard-scality

* @teddyandrieux

* @slaperche-scality

* @thomasdanan

* @zempashi

* @nicolast

* @sayf-eddine-scality

* @monpote

* @gdemonet

* @tcarmet

2019-07-15 12:41 UTC, bert-e commented
# History mismatch



Merge commit #fcbd5c5040aaba47c2694d671c9228475bae1534 on the integration branch
`w/2.1/improvement/1401-add-script-for-product-management` is merging a branch which is neither the current
branch `improvement/1401-add-script-for-product-management` nor the development branch
`development/2.1`.

It is likely due to a rebase of the branch `improvement/1401-add-script-for-product-management` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**

2019-07-15 12:43 UTC, sayf-eddine-scality commented
@bert-e reset

2019-07-15 12:43 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.

2019-07-15 12:43 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `improvement/1401-add-script-for-product-management` into
`development/2.0`
* [w/2.1/improvement/1401-add-script-for-product-management](https://github.com/scality/metalk8s/compare/development/2.1...w/2.1/improvement/1401-add-script-for-product-management) will be merged into `development/2.1` 
* [w/2.2/improvement/1401-add-script-for-product-management](https://github.com/scality/metalk8s/compare/development/2.2...w/2.2/improvement/1401-add-script-for-product-management) will be merged into `development/2.2` 



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`




You can set option `create_pull_requests` if you need me to create
**integration pull requests** in addition to integration branches, with:

```
@bert-e create_pull_requests
```

2019-07-15 12:43 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @jbertran

* @nootal

* @cmonfort

* @lucieleonard

* @alxf

* @carlito-scality

* @alexandre-allard-scality

* @teddyandrieux

* @slaperche-scality

* @thomasdanan

* @zempashi

* @nicolast

* @sayf-eddine-scality

* @monpote

* @gdemonet

* @tcarmet

2019-07-15 12:53 UTC, slaperche-scality submitted a review, later dismissed
I'm not a Shell guru, so if someone else could take a look that would be great.

2019-07-15 12:53 UTC, slaperche-scality commented on scripts/iso-manager.sh
> +echo "iso-manager.sh [options]"
The function body should be indented.

2019-07-15 12:53 UTC, slaperche-scality commented on scripts/iso-manager.sh
> +echo "--d/--dry-run:    Run actions in dry run mode"
single hyphen for short option `-d` not `--d`

2019-07-15 12:53 UTC, slaperche-scality commented on scripts/iso-manager.sh
> +        if [ -n "$LOGFILE" ]; then
l.35 to 39 could be replace by a call to `_log`, no?

2019-07-15 12:53 UTC, slaperche-scality commented on scripts/iso-manager.sh
> +        --out txt | cut -d' ' -f2- | tr -d '[],'))
Having an output example in comment would help to understand the "parsing" done.

2019-07-15 12:53 UTC, slaperche-scality commented on scripts/iso-manager.sh
> +    for p in "$@"; do
`product` instead of `p`

2019-07-15 12:53 UTC, slaperche-scality commented on scripts/iso-manager.sh
> +  local e match="$1"
`item`, `element`, … instead of `e`

2019-07-15 12:53 UTC, slaperche-scality commented on scripts/iso-manager.sh
> +#!/bin/bash
A little more info in the commit message would be welcome (what the script is doing for instance: by reading the code it seems to auto-mount stuff and doing things after)

2019-07-15 12:53 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @jbertran

* @nootal

* @cmonfort

* @lucieleonard

* @alxf

* @carlito-scality

* @alexandre-allard-scality

* @teddyandrieux

* @slaperche-scality

* @thomasdanan

* @zempashi

* @nicolast

* @sayf-eddine-scality

* @monpote

* @gdemonet

* @tcarmet





The following reviewers are expecting changes from the author, or must review again:

* @slaperche-scality

2019-07-15 13:22 UTC, TeddyAndrieux submitted a review, later dismissed

2019-07-15 13:22 UTC, TeddyAndrieux commented on scripts/iso-manager.sh
> +echo "-l/--log-file:    path to log file"
To be consistent use `verbose` instead of `DEBUG` and add an option to change it

2019-07-15 13:22 UTC, TeddyAndrieux commented on scripts/iso-manager.sh
> +[ $# -lt 1 ] && _usage
Like described in the ticket, this script should support no argument and will basically just skip `add_products`

2019-07-15 13:22 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @jbertran

* @nootal

* @cmonfort

* @lucieleonard

* @alxf

* @carlito-scality

* @alexandre-allard-scality

* @teddyandrieux

* @slaperche-scality

* @thomasdanan

* @zempashi

* @nicolast

* @sayf-eddine-scality

* @monpote

* @gdemonet

* @tcarmet





The following reviewers are expecting changes from the author, or must review again:

* @slaperche-scality

* @teddyandrieux

2019-07-15 13:54 UTC, bert-e commented
# History mismatch



Merge commit #9b507e3f7a5aab6cd491243d8d419da7c124904a on the integration branch
`w/2.1/improvement/1401-add-script-for-product-management` is merging a branch which is neither the current
branch `improvement/1401-add-script-for-product-management` nor the development branch
`development/2.1`.

It is likely due to a rebase of the branch `improvement/1401-add-script-for-product-management` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**

2019-07-15 13:55 UTC, sayf-eddine-scality commented
@bert-e reset

2019-07-15 13:56 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.

2019-07-15 13:56 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `improvement/1401-add-script-for-product-management` into
`development/2.0`
* [w/2.1/improvement/1401-add-script-for-product-management](https://github.com/scality/metalk8s/compare/development/2.1...w/2.1/improvement/1401-add-script-for-product-management) will be merged into `development/2.1` 
* [w/2.2/improvement/1401-add-script-for-product-management](https://github.com/scality/metalk8s/compare/development/2.2...w/2.2/improvement/1401-add-script-for-product-management) will be merged into `development/2.2` 



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`




You can set option `create_pull_requests` if you need me to create
**integration pull requests** in addition to integration branches, with:

```
@bert-e create_pull_requests
```

2019-07-15 13:56 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @jbertran

* @nootal

* @cmonfort

* @lucieleonard

* @alxf

* @carlito-scality

* @alexandre-allard-scality

* @teddyandrieux

* @slaperche-scality

* @thomasdanan

* @zempashi

* @nicolast

* @sayf-eddine-scality

* @monpote

* @gdemonet

* @tcarmet





The following reviewers are expecting changes from the author, or must review again:

* @slaperche-scality

* @teddyandrieux

2019-07-16 08:03 UTC, TeddyAndrieux reviewed
The script is not included in the ISO :(

Also you need to update the doc according to the process change

2019-07-16 09:56 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @jbertran

* @nootal

* @cmonfort

* @lucieleonard

* @alxf

* @carlito-scality

* @alexandre-allard-scality

* @teddyandrieux

* @slaperche-scality

* @thomasdanan

* @zempashi

* @nicolast

* @sayf-eddine-scality

* @monpote

* @gdemonet

* @tcarmet





The following reviewers are expecting changes from the author, or must review again:

* @slaperche-scality

2019-07-16 09:57 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @jbertran

* @nootal

* @cmonfort

* @lucieleonard

* @alxf

* @carlito-scality

* @alexandre-allard-scality

* @teddyandrieux

* @slaperche-scality

* @thomasdanan

* @zempashi

* @nicolast

* @sayf-eddine-scality

* @monpote

* @gdemonet

* @tcarmet

2019-07-16 09:58 UTC, bert-e commented
# History mismatch



Merge commit #a2ddec3c0afcc043327380a74eb3f7e750e887a3 on the integration branch
`w/2.1/improvement/1401-add-script-for-product-management` is merging a branch which is neither the current
branch `improvement/1401-add-script-for-product-management` nor the development branch
`development/2.1`.

It is likely due to a rebase of the branch `improvement/1401-add-script-for-product-management` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**

2019-07-16 09:59 UTC, sayf-eddine-scality commented
@bert-e reset

2019-07-16 09:59 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.

2019-07-16 09:59 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `improvement/1401-add-script-for-product-management` into
`development/2.0`
* [w/2.1/improvement/1401-add-script-for-product-management](https://github.com/scality/metalk8s/compare/development/2.1...w/2.1/improvement/1401-add-script-for-product-management) will be merged into `development/2.1` 
* [w/2.2/improvement/1401-add-script-for-product-management](https://github.com/scality/metalk8s/compare/development/2.2...w/2.2/improvement/1401-add-script-for-product-management) will be merged into `development/2.2` 



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`




You can set option `create_pull_requests` if you need me to create
**integration pull requests** in addition to integration branches, with:

```
@bert-e create_pull_requests
```

2019-07-16 09:59 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @jbertran

* @nootal

* @cmonfort

* @lucieleonard

* @alxf

* @carlito-scality

* @alexandre-allard-scality

* @teddyandrieux

* @slaperche-scality

* @thomasdanan

* @zempashi

* @nicolast

* @sayf-eddine-scality

* @monpote

* @gdemonet

* @tcarmet

2019-07-16 09:59 UTC, sayf-eddine-scality commented
@bert-e approve

2019-07-16 09:59 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @jbertran

* @nootal

* @cmonfort

* @lucieleonard

* @alxf

* @carlito-scality

* @alexandre-allard-scality

* @teddyandrieux

* @slaperche-scality

* @thomasdanan

* @zempashi

* @nicolast

* @sayf-eddine-scality

* @monpote

* @gdemonet

* @tcarmet










*The following options are set:* **approve**

2019-07-16 10:08 UTC, slaperche-scality requested changes

2019-07-16 10:08 UTC, slaperche-scality commented on buildchain/buildchain/iso.py
> +            'uptodate': [True],
Nope.
Why do you want it to be always true?

If the script is modified, you want to copy it again.
You should have `constants.ROOT/'scripts'/'iso-manager.sh'` as `file_dep`.

2019-07-16 10:08 UTC, slaperche-scality commented on buildchain/buildchain/iso.py
> +            'title': lambda task: utils.title_with_target1('GENERATE', task),
You're not generating anything, just copying a file, so "COPY" sounds better.

2019-07-16 10:08 UTC, slaperche-scality commented on buildchain/buildchain/iso.py
> +            'uptodate': [True],
And looking at the code, it seems like `task__iso_add_node_manifest` was wrong as well and should be fixed (in another commit/PR, not here).

2019-07-16 10:08 UTC, slaperche-scality commented on buildchain/buildchain/iso.py
> +    iso_manager = [
Weird layout.

Should be:

```
iso_manager = [
    constants.ROOT/'scripts'/'iso-manager.sh',
    dest
]
````

2019-07-16 10:08 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @jbertran

* @nootal

* @cmonfort

* @lucieleonard

* @alxf

* @carlito-scality

* @alexandre-allard-scality

* @teddyandrieux

* @slaperche-scality

* @thomasdanan

* @zempashi

* @nicolast

* @sayf-eddine-scality

* @monpote

* @gdemonet

* @tcarmet





The following reviewers are expecting changes from the author, or must review again:

* @slaperche-scality







*The following options are set:* **approve**

2019-07-16 10:11 UTC, bert-e commented
# History mismatch



Merge commit #9aff73fbbb59e02d85b739e908316f1e14e22d5c on the integration branch
`w/2.1/improvement/1401-add-script-for-product-management` is merging a branch which is neither the current
branch `improvement/1401-add-script-for-product-management` nor the development branch
`development/2.1`.

It is likely due to a rebase of the branch `improvement/1401-add-script-for-product-management` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**





*The following options are set:* **approve**

2019-07-16 11:33 UTC, slaperche-scality submitted a review, later dismissed

2019-07-16 11:33 UTC, slaperche-scality commented on docs/operation/preparation.rst
> +To provision a new **Metalk8s** ISO you need to run the according utility
remove `accordingly`

2019-07-16 11:43 UTC, sayf-eddine-scality commented
@bert-e reset

2019-07-16 11:43 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.






*The following options are set:* **approve**

2019-07-16 11:43 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `improvement/1401-add-script-for-product-management` into
`development/2.0`
* [w/2.1/improvement/1401-add-script-for-product-management](https://github.com/scality/metalk8s/compare/development/2.1...w/2.1/improvement/1401-add-script-for-product-management) will be merged into `development/2.1` 
* [w/2.2/improvement/1401-add-script-for-product-management](https://github.com/scality/metalk8s/compare/development/2.2...w/2.2/improvement/1401-add-script-for-product-management) will be merged into `development/2.2` 



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`




You can set option `create_pull_requests` if you need me to create
**integration pull requests** in addition to integration branches, with:

```
@bert-e create_pull_requests
```







*The following options are set:* **approve**

2019-07-16 11:43 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @jbertran

* @nootal

* @cmonfort

* @lucieleonard

* @alxf

* @carlito-scality

* @alexandre-allard-scality

* @teddyandrieux

* @slaperche-scality

* @thomasdanan

* @zempashi

* @nicolast

* @sayf-eddine-scality

* @monpote

* @gdemonet

* @tcarmet










*The following options are set:* **approve**

2019-07-16 12:21 UTC, slaperche-scality submitted a review, later dismissed

2019-07-16 12:21 UTC, bert-e commented
# Build failed



The build for [commit](https://github.com/scality/metalk8s/commit/91e66617f11c9b7e1c19ebc3bd7299fb1f318859) did not succeed in branch improvement/1401-add-script-for-product-management.




*The following options are set:* **approve**

2019-07-16 12:24 UTC, bert-e commented
# History mismatch



Merge commit #301cd33595e162dc83ae62f8c22fbd47be3d31de on the integration branch
`w/2.1/improvement/1401-add-script-for-product-management` is merging a branch which is neither the current
branch `improvement/1401-add-script-for-product-management` nor the development branch
`development/2.1`.

It is likely due to a rebase of the branch `improvement/1401-add-script-for-product-management` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**





*The following options are set:* **approve**

2019-07-16 12:38 UTC, sayf-eddine-scality commented
@bert-e reset

2019-07-16 12:38 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.






*The following options are set:* **approve**

2019-07-16 12:38 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `improvement/1401-add-script-for-product-management` into
`development/2.0`
* [w/2.1/improvement/1401-add-script-for-product-management](https://github.com/scality/metalk8s/compare/development/2.1...w/2.1/improvement/1401-add-script-for-product-management) will be merged into `development/2.1` 
* [w/2.2/improvement/1401-add-script-for-product-management](https://github.com/scality/metalk8s/compare/development/2.2...w/2.2/improvement/1401-add-script-for-product-management) will be merged into `development/2.2` 



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`




You can set option `create_pull_requests` if you need me to create
**integration pull requests** in addition to integration branches, with:

```
@bert-e create_pull_requests
```







*The following options are set:* **approve**

2019-07-16 12:38 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @jbertran

* @nootal

* @cmonfort

* @lucieleonard

* @alxf

* @carlito-scality

* @alexandre-allard-scality

* @teddyandrieux

* @slaperche-scality

* @thomasdanan

* @zempashi

* @nicolast

* @sayf-eddine-scality

* @monpote

* @gdemonet

* @tcarmet










*The following options are set:* **approve**

2019-07-16 13:07 UTC, slaperche-scality approved these changes

2019-07-16 13:08 UTC, bert-e commented
# Build failed



The build for [commit](https://github.com/scality/metalk8s/commit/6d52800fe366272b81110eecd1247e59f1a8e65f) did not succeed in branch improvement/1401-add-script-for-product-management.




*The following options are set:* **approve**

2019-07-16 15:48 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/2.0`

* :heavy_check_mark: `development/2.1`

* :heavy_check_mark: `development/2.2`



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2019-07-16 16:28 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/2.0`

* :heavy_check_mark: `development/2.1`

* :heavy_check_mark: `development/2.2`



The following branches have **NOT** changed:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`



Please check the status of the associated issue None.

Goodbye sayf-eddine-scality.

2019-07-16 16:28 UTC, merged