Bump K8s version to 1.14
scality/metalk8s pull request #1443
Opened 2019-07-17 13:08 UTC by gdemonet

**Component**: kubernetes

**Context**: Creation of the `development/2.3` branch

**Acceptance criteria**: Green build

---

See: #1394

2019-07-17 13:11 UTC, bert-e commented
# Hello gdemonet,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/metalk8s/bert-e/doc/user).





*Status report is not available.*

2019-07-17 13:12 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `improvement/1394-bump-k8s-to-1.14` into
`development/2.2`
* [w/2.3/improvement/1394-bump-k8s-to-1.14](https://github.com/scality/metalk8s/compare/development/2.3...w/2.3/improvement/1394-bump-k8s-to-1.14) will be merged into `development/2.3` 



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`
* `development/2.0`
* `development/2.1`




You can set option `create_pull_requests` if you need me to create
**integration pull requests** in addition to integration branches, with:

```
@bert-e create_pull_requests
```

2019-07-17 13:12 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @jbertran

* @nootal

* @cmonfort

* @lucieleonard

* @alxf

* @carlito-scality

* @alexandre-allard-scality

* @teddyandrieux

* @slaperche-scality

* @thomasdanan

* @zempashi

* @nicolast

* @sayf-eddine-scality

* @monpote

* @gdemonet

* @tcarmet

2019-07-17 13:12 UTC, slaperche-scality commented
You only need to bump k8s, not the others images (prometheus, etcd, …)?

Also commit message is missing (you can simply put "Creation of the development/2.3 branch" as body)

2019-07-17 13:16 UTC, TeddyAndrieux commented
Hmm here you bump version for `development/2.2`

2019-07-17 13:16 UTC, Ebaneck commented
> You only need to bump k8s, not the others images (prometheus, etcd, …)?
> 
> Also commit message is missing (you can simply put "Creation of the development/2.3 branch" as body)

@gdemonet just like @slaperche-scality mentioned... I think you will need to update the images in ` buildchain/buildchain/image.py`

2019-07-17 13:30 UTC, NicolasT requested changes
- Need fix of target branch as @TeddyAndrieux mentioned
- Image hashes need to be updated as @Ebaneck mentioned
- `etcd` version to be checked with what `kubeadm` does in 1.14

2019-07-17 13:30 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @jbertran

* @nootal

* @cmonfort

* @lucieleonard

* @alxf

* @carlito-scality

* @alexandre-allard-scality

* @teddyandrieux

* @slaperche-scality

* @thomasdanan

* @zempashi

* @nicolast

* @sayf-eddine-scality

* @monpote

* @gdemonet

* @tcarmet





The following reviewers are expecting changes from the author, or must review again:

* @nicolast

2019-07-17 13:31 UTC, gdemonet commented
@slaperche-scality @Ebaneck  I'll have a look at `etcd`, but no need to bump Prometheus/Calico etc. for now
@NicolasT @TeddyAndrieux yes I misclicked apparently, fixed it

2019-07-17 13:34 UTC, gdemonet commented
@NicolasT `etcd` version was bumped in 1.13, not 1.14: https://github.com/kubernetes/kubernetes/commit/862b945e5ab33d7e15f9a3a624c53eb0371627b0
Should I create another PR?

2019-07-17 13:41 UTC, NicolasT commented
> @NicolasT `etcd` version was bumped in 1.13, not 1.14: [kubernetes/kubernetes@862b945](https://github.com/kubernetes/kubernetes/commit/862b945e5ab33d7e15f9a3a624c53eb0371627b0)
> Should I create another PR?
> 
> There is also: https://github.com/kubernetes/kubernetes/blob/v1.14.4/cmd/kubeadm/app/constants/constants.go#L398-L403
> 
> ```go
> 	// SupportedEtcdVersion lists officially supported etcd versions with corresponding Kubernetes releases
> 	SupportedEtcdVersion = map[uint8]string{
> 		12: "3.2.24",
> 		13: "3.2.24",
> 		14: "3.3.10",
> 	}
> ```

From the second part, it appears 3.3.10 is supported by K8s 1.14, and K8s 1.12/1.13 use etcd 3.2.24. Your first link may seem to contradict this, saying the etcd version was updated to 3.3.10 for kubeadm 1.13, but this seems like a mistake in the commit message to me: according to Github, the relevant commit is only part of `v1.14.0-alpha.1` up to `v1.16.0-alpha.0`, i.e. K8s 1.14.

So, we'll want to properly deploy (and upgrade to) etcd 3.3.10 in MetalK8s 2.3, no?

2019-07-17 14:34 UTC, thomasdanan reviewed
@gdemonet  did you test node expansion with this new version of k8s ? not working for me but maybe related to my env ... forget about it, I was using the wrong version (2.0.0 instead of 2.2) for metalk8s when adding the node ...

2019-07-17 15:00 UTC, TeddyAndrieux commented on buildchain/buildchain/image.py
> +        version='3.3.10',
You need to change it in the manifest also :)

2019-07-17 15:02 UTC, NicolasT commented
/me throws in #640

2019-07-17 15:38 UTC, thomasdanan submitted a review, later dismissed
actually, you probably need to update metalk8s version since in what I deployed it is still 2.2

2019-07-17 15:38 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @jbertran

* @nootal

* @cmonfort

* @lucieleonard

* @alxf

* @carlito-scality

* @alexandre-allard-scality

* @teddyandrieux

* @slaperche-scality

* @thomasdanan

* @zempashi

* @nicolast

* @sayf-eddine-scality

* @monpote

* @gdemonet

* @tcarmet





The following reviewers are expecting changes from the author, or must review again:

* @thomasdanan

* @nicolast

2019-07-17 16:00 UTC, gdemonet commented
> /me throws in #640

Will do in a future PR ;)

2019-07-17 16:03 UTC, NicolasT commented
@thomasdanan is right, oversight. The `VERSION` file needs to be bumped as well, ideally before any other commits.

2019-07-17 16:05 UTC, gdemonet commented
@thomasdanan  @NicolasT `VERSION` file updated
@TeddyAndrieux `metalk8s.kubernetes.etcd.installed` updated

2019-07-17 16:15 UTC, NicolasT approved these changes
LGTM if CI agrees.

Actually, it may be worth to add a test as well, which validates (`kubectl version` or similar) the version of K8s that's running is the one we expect... May be worth another ticket, or done in scope of this PR.

2019-07-17 16:15 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @jbertran

* @nootal

* @cmonfort

* @lucieleonard

* @alxf

* @carlito-scality

* @alexandre-allard-scality

* @teddyandrieux

* @slaperche-scality

* @thomasdanan

* @zempashi

* @nicolast

* @sayf-eddine-scality

* @monpote

* @gdemonet

* @tcarmet





The following reviewers are expecting changes from the author, or must review again:

* @thomasdanan

2019-07-17 16:34 UTC, gdemonet commented
> LGTM if CI agrees.
> 
> Actually, it may be worth to add a test as well, which validates (`kubectl version` or similar) the version of K8s that's running is the one we expect... May be worth another ticket, or done in scope of this PR.

Good idea, I'll do it in this PR

2019-07-18 08:29 UTC, TeddyAndrieux commented
> > LGTM if CI agrees.
> > Actually, it may be worth to add a test as well, which validates (`kubectl version` or similar) the version of K8s that's running is the one we expect... May be worth another ticket, or done in scope of this PR.
> 
> Good idea, I'll do it in this PR

For me this test should be done on every branches so you can't do it in this PR.

2019-07-18 09:43 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @jbertran

* @nootal

* @cmonfort

* @lucieleonard

* @alxf

* @carlito-scality

* @alexandre-allard-scality

* @teddyandrieux

* @slaperche-scality

* @thomasdanan

* @zempashi

* @nicolast

* @sayf-eddine-scality

* @monpote

* @gdemonet

* @tcarmet

2019-07-18 11:26 UTC, gdemonet commented
@bert-e approve

2019-07-18 11:26 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/2.3`



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`
* `development/2.0`
* `development/2.1`
* `development/2.2`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2019-07-18 11:58 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/2.3`



The following branches have **NOT** changed:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`
* `development/2.0`
* `development/2.1`
* `development/2.2`



Please check the status of the associated issue None.

Goodbye gdemonet.

2019-07-18 11:58 UTC, merged