split the volume size field into two
scality/metalk8s pull request #1492
Opened 2019-08-01 10:14 UTC by ChengYanJin

**Component**: ui, storage

**Context**:  We would like to split the volume size into two. One is input for the positive integer, the other is select for the unit.

**Summary**: For the input field, we check if it's the positive integer. And users can select the unit from the dropdown list.

**Acceptance criteria**: 
![image](https://user-images.githubusercontent.com/18453133/62285154-57d04e80-b455-11e9-9d21-418b19de41ef.png)

See: #1459

2019-08-01 10:14 UTC, bert-e commented
# Hello chengyanjin,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/metalk8s/bert-e/doc/user).





*Status report is not available.*

2019-08-01 10:14 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @jbertran

* @nootal

* @cmonfort

* @lucieleonard

* @alxf

* @carlito-scality

* @alexandre-allard-scality

* @teddyandrieux

* @slaperche-scality

* @thomasdanan

* @zempashi

* @nicolast

* @sayf-eddine-scality

* @monpote

* @gdemonet

* @tcarmet

2019-08-01 10:52 UTC, slaperche-scality requested changes

2019-08-01 10:52 UTC, slaperche-scality commented on ui/src/services/utils.js
> +  { label: 'ki', value: 'Ki' },
`ki` => `KiB`

I know that I told you that it was a small `k`, but actually it's more complicated:
- a small `k` for [kilobyte](https://en.wikipedia.org/wiki/Kilobyte) (`kB`) 
- a big `K` for [kibibyte](https://en.wikipedia.org/wiki/Kibibyte) (`KiB`)

2019-08-01 10:52 UTC, slaperche-scality commented on ui/src/services/utils.js
> +export const sizeUnits = [
I would add the `B` of byte for the labels, so: `KiB`, `MiB`, …

Also, I would add `{ label: 'B', value: '' }` as one may want to specify the size in bytes directly.

2019-08-01 10:52 UTC, slaperche-scality commented on ui/src/translations/en.json
> +  "volume_size_error": "The size must be a postive integer."
`postive` => `positive`

2019-08-01 10:52 UTC, slaperche-scality commented on ui/src/containers/CreateVolume.js
> +        .integer(intl.messages.volume_size_error)
This is way more readable than a regex :+1: 

That being said, it's buggy :disappointed: 

If you input a "big" number, say 2 GiB as bytes (which is pretty small actually), e.g. `2147483648`, you have the error `The size must be a postive integer.` which is pretty weird from a user point of view (it is a positive integer).

I guess we wouldn't have the problem with the good ol’ regex :stuck_out_tongue:

2019-08-01 10:52 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @jbertran

* @nootal

* @cmonfort

* @lucieleonard

* @alxf

* @carlito-scality

* @alexandre-allard-scality

* @teddyandrieux

* @slaperche-scality

* @thomasdanan

* @zempashi

* @nicolast

* @sayf-eddine-scality

* @monpote

* @gdemonet

* @tcarmet





The following reviewers are expecting changes from the author, or must review again:

* @slaperche-scality

2019-08-01 20:44 UTC, slaperche-scality reviewed
Works fine :smiley: 

Two remarks though:

1. Not in the scope of this PR but I realized that we're not checking if the volume name is unique.
2. I have the error message `sizeInput is a required field` in English, even in French (and `sizeInput` may not be very clear to the user). I guess it's an error message generated by `Yup`, I don't know if we can override it (if yes, we should do it).

2019-08-01 20:44 UTC, slaperche-scality commented on ui/src/containers/CreateVolume.js
> +        .matches(/^[1-9][0-9]*$/, intl.messages.volume_size_error)
It would be nice to explain in the commit message why we went back to the regex

2019-08-01 20:44 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @cmonfort

* @jbertran

* @tcarmet

* @carlito-scality

* @slaperche-scality

* @alexandre-allard-scality

* @zempashi

* @teddyandrieux

* @sayf-eddine-scality

* @nootal

* @nicolast

* @lucieleonard

* @gdemonet

* @monpote

* @thomasdanan





The following reviewers are expecting changes from the author, or must review again:

* @slaperche-scality

2019-08-02 09:26 UTC, carlito-scality commented
Select Input style should be improved to be consistent with other inputs but can be managed later.

2019-08-02 14:31 UTC, slaperche-scality submitted a review, later dismissed

2019-08-02 14:32 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @cmonfort

* @jbertran

* @tcarmet

* @carlito-scality

* @slaperche-scality

* @alexandre-allard-scality

* @zempashi

* @teddyandrieux

* @sayf-eddine-scality

* @nootal

* @nicolast

* @lucieleonard

* @gdemonet

* @monpote

* @thomasdanan

2019-08-02 14:36 UTC, ChengYanJin commented
@bert-e approve

2019-08-02 14:48 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @cmonfort

* @jbertran

* @tcarmet

* @carlito-scality

* @slaperche-scality

* @alexandre-allard-scality

* @zempashi

* @teddyandrieux

* @sayf-eddine-scality

* @nootal

* @nicolast

* @lucieleonard

* @gdemonet

* @monpote

* @thomasdanan










*The following options are set:* **approve**

2019-08-02 14:49 UTC, MonPote approved these changes

2019-08-02 15:35 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/2.4`



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`
* `development/2.0`
* `development/2.1`
* `development/2.2`
* `development/2.3`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2019-08-02 15:35 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/2.4`



The following branches have **NOT** changed:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`
* `development/2.0`
* `development/2.1`
* `development/2.2`
* `development/2.3`



Please check the status of the associated issue None.

Goodbye chengyanjin.

2019-08-02 15:35 UTC, merged