Use XXXX_ca_b64 for an encoded cert
scality/metalk8s pull request #1629
Opened 2019-09-05 13:18 UTC by sayf-eddine-scality

Instead of XXXX_ca_server

Fixes: #890

**Component**:

**Context**: 

**Summary**:

**Acceptance criteria**: 

---

Closes: #ISSUE_NUMBER

2019-09-05 13:18 UTC, bert-e commented
# Hello sayf-eddine-scality,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/metalk8s/bert-e/doc/user).





*Status report is not available.*

2019-09-05 13:19 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `improvement/890-review-mine-names` into
`development/2.0`
* [w/2.1/improvement/890-review-mine-names](https://github.com/scality/metalk8s/compare/development/2.1...w/2.1/improvement/890-review-mine-names) will be merged into `development/2.1` 
* [w/2.2/improvement/890-review-mine-names](https://github.com/scality/metalk8s/compare/development/2.2...w/2.2/improvement/890-review-mine-names) will be merged into `development/2.2` 
* [w/2.3/improvement/890-review-mine-names](https://github.com/scality/metalk8s/compare/development/2.3...w/2.3/improvement/890-review-mine-names) will be merged into `development/2.3` 
* [w/2.4/improvement/890-review-mine-names](https://github.com/scality/metalk8s/compare/development/2.4...w/2.4/improvement/890-review-mine-names) will be merged into `development/2.4` 



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`




You can set option `create_pull_requests` if you need me to create
**integration pull requests** in addition to integration branches, with:

```
@bert-e create_pull_requests
```

2019-09-05 13:19 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @teddyandrieux

* @monpote

* @jbertran

* @sayf-eddine-scality

* @nicolast

* @cmonfort

* @slaperche-scality

* @thomasdanan

* @zempashi

* @lucieleonard

* @gdemonet

* @carlito-scality

* @nootal

* @alexandre-allard-scality

2019-09-05 13:20 UTC, TeddyAndrieux commented on salt/metalk8s/kubernetes/ca/kubernetes/advertised.sls
> +{%- set ca_server = salt['mine.get'](pillar['metalk8s']['ca']['minion'], 'kubernetes_root_ca_b64') %}
I think it's make sense to also rename this `ca_server` variable here

2019-09-05 13:21 UTC, slaperche-scality requested changes

2019-09-05 13:21 UTC, slaperche-scality commented on pillar/metalk8s/roles/ca.sls
> +  kubernetes_root_ca_b64:
The commit message doesn't explain WHY we do the renaming.

2019-09-05 13:21 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @teddyandrieux

* @monpote

* @jbertran

* @sayf-eddine-scality

* @nicolast

* @cmonfort

* @slaperche-scality

* @thomasdanan

* @zempashi

* @lucieleonard

* @gdemonet

* @carlito-scality

* @nootal

* @alexandre-allard-scality





The following reviewers are expecting changes from the author, or must review again:

* @slaperche-scality

2019-09-05 13:34 UTC, bert-e commented
# History mismatch



Merge commit #081fcfa10b915ac0bb6fdc9677ea725f826a33bb on the integration branch
`w/2.1/improvement/890-review-mine-names` is merging a branch which is neither the current
branch `improvement/890-review-mine-names` nor the development branch
`development/2.1`.

It is likely due to a rebase of the branch `improvement/890-review-mine-names` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**

2019-09-05 13:34 UTC, sayf-eddine-scality commented
/reset

2019-09-05 13:34 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.

2019-09-05 13:35 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `improvement/890-review-mine-names` into
`development/2.0`
* [w/2.1/improvement/890-review-mine-names](https://github.com/scality/metalk8s/compare/development/2.1...w/2.1/improvement/890-review-mine-names) will be merged into `development/2.1` 
* [w/2.2/improvement/890-review-mine-names](https://github.com/scality/metalk8s/compare/development/2.2...w/2.2/improvement/890-review-mine-names) will be merged into `development/2.2` 
* [w/2.3/improvement/890-review-mine-names](https://github.com/scality/metalk8s/compare/development/2.3...w/2.3/improvement/890-review-mine-names) will be merged into `development/2.3` 
* [w/2.4/improvement/890-review-mine-names](https://github.com/scality/metalk8s/compare/development/2.4...w/2.4/improvement/890-review-mine-names) will be merged into `development/2.4` 



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`




You can set option `create_pull_requests` if you need me to create
**integration pull requests** in addition to integration branches, with:

```
@bert-e create_pull_requests
```

2019-09-05 13:35 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @teddyandrieux

* @monpote

* @jbertran

* @sayf-eddine-scality

* @nicolast

* @cmonfort

* @slaperche-scality

* @thomasdanan

* @zempashi

* @lucieleonard

* @gdemonet

* @carlito-scality

* @nootal

* @alexandre-allard-scality





The following reviewers are expecting changes from the author, or must review again:

* @slaperche-scality

2019-09-05 13:36 UTC, sayf-eddine-scality commented
/approve

2019-09-05 13:36 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @teddyandrieux

* @monpote

* @jbertran

* @sayf-eddine-scality

* @nicolast

* @cmonfort

* @slaperche-scality

* @thomasdanan

* @zempashi

* @lucieleonard

* @gdemonet

* @carlito-scality

* @nootal

* @alexandre-allard-scality





The following reviewers are expecting changes from the author, or must review again:

* @slaperche-scality







*The following options are set:* **approve**

2019-09-05 13:36 UTC, slaperche-scality approved these changes

2019-09-05 13:39 UTC, TeddyAndrieux approved these changes
LGTM

2019-09-05 14:07 UTC, bert-e commented
# Build failed



The build for [commit](https://github.com/scality/metalk8s/commit/35c5e1de6ddf8f7a85305886e3747ee75dbfd993) did not succeed in branch w/2.3/improvement/890-review-mine-names.




*The following options are set:* **approve**

2019-09-05 14:11 UTC, bert-e commented
# Build failed



The build for [commit](https://github.com/scality/metalk8s/commit/4b82eb855688c9dda2afa0661d49777cc3f82552) did not succeed in branch w/2.1/improvement/890-review-mine-names.




*The following options are set:* **approve**

2019-09-05 15:44 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/2.0`

* :heavy_check_mark: `development/2.1`

* :heavy_check_mark: `development/2.2`

* :heavy_check_mark: `development/2.3`

* :heavy_check_mark: `development/2.4`



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2019-09-06 06:22 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/2.0`

* :heavy_check_mark: `development/2.1`

* :heavy_check_mark: `development/2.2`

* :heavy_check_mark: `development/2.3`

* :heavy_check_mark: `development/2.4`



The following branches have **NOT** changed:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`



Please check the status of the associated issue None.

Goodbye sayf-eddine-scality.

2019-09-06 06:22 UTC, merged