ui/bug: fix the bug when there is no PV && add unit test for isVolumeDeletable
scality/metalk8s pull request #1689
Opened 2019-09-13 14:52 UTC by ChengYanJin

**Component**: ui

**Context**: 
When the volume is failed, if there is no PV found, the volume is not deletable.

**Summary**:
Fix the bug.
Add a unit test for `isVolumeDeletable` function in NodeVolumes. 
There are in total of 17 cases with the different combinations of volume and PV.

**Acceptance criteria**: 
Pass all the 17 cases

Closes: #1673

2019-09-13 14:53 UTC, bert-e commented
# Hello chengyanjin,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/metalk8s/bert-e/doc/user).





*Status report is not available.*

2019-09-13 14:53 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @teddyandrieux

* @monpote

* @jbertran

* @sayf-eddine-scality

* @nicolast

* @cmonfort

* @slaperche-scality

* @thomasdanan

* @zempashi

* @lucieleonard

* @gdemonet

* @carlito-scality

* @nootal

* @alexandre-allard-scality

2019-09-13 14:59 UTC, carlito-scality requested changes

2019-09-13 14:59 UTC, carlito-scality commented on ui/src/containers/NodeVolumesUtils.js
> +export const isVolumeDeletable = (rowData, persistentVolumes) => {
Where do you use it?

2019-09-13 14:59 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @teddyandrieux

* @monpote

* @jbertran

* @sayf-eddine-scality

* @nicolast

* @cmonfort

* @slaperche-scality

* @thomasdanan

* @zempashi

* @lucieleonard

* @gdemonet

* @carlito-scality

* @nootal

* @alexandre-allard-scality





The following reviewers are expecting changes from the author, or must review again:

* @carlito-scality

2019-09-13 15:00 UTC, carlito-scality commented on ui/src/containers/NodeVolumesUtils.js
> +export const isVolumeDeletable = (rowData, persistentVolumes) => {
As discuss before, please put it in 'services' folder instead of 'container'.

2019-09-13 15:04 UTC, slaperche-scality reviewed
I think we could have 2 commits here:
- one for the bugfix
- one for the tests

Also, I don't know much about JS tests frameworks, but maybe there is some way to have less boilerplate here.

2019-09-13 15:04 UTC, slaperche-scality commented on ui/src/containers/NodeVolumes.js
> +  const isVolumeDeletable = (rowData, persistentVolumes) => {
Why do we need this change?

Before we were already using `persistentVolumes` l.136, it wasn't working?

2019-09-13 15:04 UTC, slaperche-scality commented on ui/src/containers/NodeVolumesUtils.js
> +export const isVolumeDeletable = (rowData, persistentVolumes) => {
This seems copied from `ui/src/containers/NodeVolumes.js`, is it normal to keep two versions of the same code?

If the goal is to make the function usable in the test, I guess `ui/src/containers/NodeVolumes.js` should use this version as well (so that the code tested is the one used for real).

2019-09-13 15:04 UTC, slaperche-scality commented on ui/src/containers/NodeVolumesUtils.test.js
> +const testcase1 = {
We probably could have more meaningful name that `testcaseX`, `testcaseY`, …

- `testcase1` => `testcaseVolumeWithoutStatus`
- `testcase2` => `testcaseVolumePending`
- `testcase3` => `testcaseVolumeTerminating`
- `testcase4` => `testcaseVolumeFailedWithoutPv`
- `testcase5` => `testcaseVolumeFailedWithPvFailed`
- […]
- `testcase11` => `testcaseVolumeAvailableWithPvFailed`
- […]
- `testcase17` => testcaseVolumeAvailableWithoutPv

2019-09-16 11:58 UTC, MonPote approved these changes

2019-09-16 12:41 UTC, carlito-scality approved these changes

2019-09-16 12:41 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @teddyandrieux

* @monpote

* @jbertran

* @sayf-eddine-scality

* @nicolast

* @cmonfort

* @slaperche-scality

* @thomasdanan

* @zempashi

* @lucieleonard

* @gdemonet

* @carlito-scality

* @nootal

* @alexandre-allard-scality

2019-09-16 12:59 UTC, ChengYanJin commented
@bert-e approve

2019-09-16 12:59 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/2.4`



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`
* `development/2.0`
* `development/2.1`
* `development/2.2`
* `development/2.3`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2019-09-16 13:47 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/2.4`



The following branches have **NOT** changed:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`
* `development/2.0`
* `development/2.1`
* `development/2.2`
* `development/2.3`



Please check the status of the associated issue None.

Goodbye chengyanjin.

2019-09-16 13:47 UTC, merged