Migrate Select component to MetalK8S
scality/metalk8s pull request #1745
Opened 2019-09-20 15:09 UTC by ChengYanJin

**Component**: ui

**Context**: 
We would like to migrate the Select component to MetalK8S.

**Summary**:

**Acceptance criteria**: 
![Screenshot 2019-09-20 at 17 08 58](https://user-images.githubusercontent.com/18453133/65337917-615e7300-dbc9-11e9-98b3-e9176c605350.png)

2019-09-20 15:15 UTC, carlito-scality requested changes

2019-09-20 15:15 UTC, carlito-scality commented on ui/src/containers/CreateVolume.js
> +                    value={optionsStorageClasses[0]}
It should be based on values.storageClass even if now we have only one value

2019-09-20 15:15 UTC, carlito-scality commented on ui/src/containers/CreateVolume.js
> -                    placeholder={intl.messages.select_a_storageClass}
Leave placeholder here

2019-09-20 15:15 UTC, carlito-scality commented on ui/src/containers/CreateVolume.js
> -                    placeholder={intl.messages.select_a_type}
Leave placeholder here

2019-09-20 15:15 UTC, carlito-scality commented on ui/src/containers/CreateVolume.js
> +    font-size: 14px;
use core-ui theme font-size

2019-09-20 15:44 UTC, slaperche-scality commented
minor nitpick on the PR description:

> Context:  We would like to migrate the Select component to MetalK8S.

Would be nice to add "why" we want to migrate?
Also isn't it migrating Select component to `core-ui`?

2019-09-22 12:02 UTC, ChengYanJin commented
wrong branch name. Going to recreate a PR

2019-09-22 12:02 UTC, closed without merging