Update sphinxcontrib-plantuml
scality/metalk8s pull request #1892
Opened 2019-10-10 18:02 UTC by slaperche-scality

**Component**:

docs

**Context**: 

The build of the doc is flaky, and the real error is hidden by a bug in `sphinxcontrib-plantuml`.

**Summary**:

Update doc depedencies
Bump required minimal version for `sphinxcontrib-plantuml`

**Acceptance criteria**: 

Doc build is still working, no visible change right now (but if we do get a build failure, we should have the real exception logged)

---

See: #1872

2019-10-10 18:02 UTC, bert-e commented
# Hello slaperche-scality,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/metalk8s/bert-e/doc/user).





*Status report is not available.*

2019-10-10 18:02 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @tcarmet

* @jbertran

* @carlito-scality

* @slaperche-scality

* @nicolast

* @teddyandrieux

* @monpote

* @sayf-eddine-scality

* @nootal

* @alexandre-allard-scality

* @gdemonet

* @lucieleonard

* @thomasdanan

* @cmonfort

2019-10-11 07:07 UTC, TeddyAndrieux requested changes
I think this PR should target 2.0

2019-10-11 07:08 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @tcarmet

* @jbertran

* @carlito-scality

* @slaperche-scality

* @nicolast

* @teddyandrieux

* @monpote

* @sayf-eddine-scality

* @nootal

* @alexandre-allard-scality

* @gdemonet

* @lucieleonard

* @thomasdanan

* @cmonfort





The following reviewers are expecting changes from the author, or must review again:

* @teddyandrieux

2019-10-11 07:12 UTC, slaperche-scality commented
The flaky is only present in 2.4 but yeah, it doesn't hurt to update from 2.0.

Will do.

2019-10-11 07:16 UTC, bert-e commented
# Branches have diverged



This pull request's source branch `improvement/1872-bump-sphinx-plantuml-to-have-logged-error` has diverged from
`development/2.4` by more than 50 commits.

To avoid any integration risks, please re-synchronize them using one of the
following solutions:

* Merge `origin/development/2.4` into `improvement/1872-bump-sphinx-plantuml-to-have-logged-error`
* Rebase `improvement/1872-bump-sphinx-plantuml-to-have-logged-error` onto `origin/development/2.4`

Note: If you choose to rebase, you may have to ask me to rebuild
integration branches using the `reset` command.

2019-10-11 07:16 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `improvement/1872-bump-sphinx-plantuml-to-have-logged-error` into
`development/2.0`
* [w/2.1/improvement/1872-bump-sphinx-plantuml-to-have-logged-error](https://github.com/scality/metalk8s/compare/development/2.1...w/2.1/improvement/1872-bump-sphinx-plantuml-to-have-logged-error) will be merged into `development/2.1` 
* [w/2.2/improvement/1872-bump-sphinx-plantuml-to-have-logged-error](https://github.com/scality/metalk8s/compare/development/2.2...w/2.2/improvement/1872-bump-sphinx-plantuml-to-have-logged-error) will be merged into `development/2.2` 
* [w/2.3/improvement/1872-bump-sphinx-plantuml-to-have-logged-error](https://github.com/scality/metalk8s/compare/development/2.3...w/2.3/improvement/1872-bump-sphinx-plantuml-to-have-logged-error) will be merged into `development/2.3` 
* [w/2.4/improvement/1872-bump-sphinx-plantuml-to-have-logged-error](https://github.com/scality/metalk8s/compare/development/2.4...w/2.4/improvement/1872-bump-sphinx-plantuml-to-have-logged-error) will be merged into `development/2.4` 



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`




You can set option `create_pull_requests` if you need me to create
**integration pull requests** in addition to integration branches, with:

```
@bert-e create_pull_requests
```

2019-10-11 07:16 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @tcarmet

* @jbertran

* @carlito-scality

* @slaperche-scality

* @nicolast

* @teddyandrieux

* @monpote

* @sayf-eddine-scality

* @nootal

* @alexandre-allard-scality

* @gdemonet

* @lucieleonard

* @thomasdanan

* @cmonfort





The following reviewers are expecting changes from the author, or must review again:

* @teddyandrieux

2019-10-11 07:18 UTC, TeddyAndrieux approved these changes

2019-10-11 07:18 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @tcarmet

* @jbertran

* @carlito-scality

* @slaperche-scality

* @nicolast

* @teddyandrieux

* @monpote

* @sayf-eddine-scality

* @nootal

* @alexandre-allard-scality

* @gdemonet

* @lucieleonard

* @thomasdanan

* @cmonfort

2019-10-11 09:03 UTC, slaperche-scality commented
/approve

2019-10-11 09:04 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/2.0`

* :heavy_check_mark: `development/2.1`

* :heavy_check_mark: `development/2.2`

* :heavy_check_mark: `development/2.3`

* :heavy_check_mark: `development/2.4`



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2019-10-11 09:04 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/2.0`

* :heavy_check_mark: `development/2.1`

* :heavy_check_mark: `development/2.2`

* :heavy_check_mark: `development/2.3`

* :heavy_check_mark: `development/2.4`



The following branches have **NOT** changed:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`



Please check the status of the associated issue None.

Goodbye slaperche-scality.

2019-10-11 09:04 UTC, merged