Issue #1995, issue #2112: a bit of rewording and some enhancements to…
scality/metalk8s pull request #2152
Opened 2019-12-18 14:22 UTC by lucieleonard

… make the documentation customer-facing.

**Component**:

Documentation

**Context**: 

Need to make the documentation more customer-facing.

**Summary**:

Applied some rewording and enhancements to make the documentation more customer-facing.

**Acceptance criteria**: 

---

Closes: #ISSUE_NUMBER

2019-12-18 14:22 UTC, bert-e commented
# Hello lucieleonard,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/metalk8s/bert-e/doc/user).





*Status report is not available.*

2019-12-18 14:22 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `documentation/installation-fixes` into
`development/2.4`
* [w/2.5/documentation/installation-fixes](https://github.com/scality/metalk8s/compare/development/2.5...w/2.5/documentation/installation-fixes) will be merged into `development/2.5` 



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`
* `development/2.0`
* `development/2.1`
* `development/2.2`
* `development/2.3`




You can set option `create_pull_requests` if you need me to create
**integration pull requests** in addition to integration branches, with:

```
@bert-e create_pull_requests
```

2019-12-18 14:22 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @tcarmet

* @jbertran

* @carlito-scality

* @slaperche-scality

* @nicolast

* @teddyandrieux

* @monpote

* @sayf-eddine-scality

* @nootal

* @alexandre-allard-scality

* @gdemonet

* @lucieleonard

* @thomasdanan

* @cmonfort

2019-12-19 08:17 UTC, slaperche-scality commented on docs/installation/bootstrap.rst
> +SSH Provisioning
One comment about the format of the commit message: we don't put reference to the issue in the title line (we usually use the footer for that).

See [contributions guideline](https://github.com/scality/metalk8s/blob/development/2.4/CONTRIBUTING.md#committing-guidelines) (and/or the [developer doc](https://metal-k8s.readthedocs.io/en/latest/developer/best_practices/commit.html#how-to-write-a-commit-message) for more information).

e.g.:

```
doc: improve wording + minor fix

Improve the documentation to make it customer-facing.

Refs: #1995
Refs: #2112
```

2019-12-19 11:54 UTC, bert-e commented
# Conflict




A conflict has been raised during the update of
integration branch `w/2.5/documentation/installation-fixes` with contents from `documentation/installation-fixes`
and `development/2.5`.

Please resolve the conflict on **the integration branch** (`w/2.5/documentation/installation-fixes`).


Here are the steps to resolve this conflict:

```bash
 $ git fetch
 $ git checkout w/2.5/documentation/installation-fixes
 $ git pull  # or "git reset --hard origin/w/2.5/documentation/installation-fixes"
 $ git merge origin/development/2.5
 $ # <intense conflict resolution>
 $ git commit
 $ git merge origin/documentation/installation-fixes
 $ # <intense conflict resolution>
 $ git commit
 $ git push -u origin w/2.5/documentation/installation-fixes
```

2019-12-19 12:47 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @tcarmet

* @jbertran

* @carlito-scality

* @slaperche-scality

* @nicolast

* @teddyandrieux

* @monpote

* @sayf-eddine-scality

* @nootal

* @alexandre-allard-scality

* @gdemonet

* @lucieleonard

* @thomasdanan

* @cmonfort

2019-12-19 15:34 UTC, wabernat reviewed
Ah... so I need to click *Submit review*...

Live and learn...

2019-12-19 15:34 UTC, wabernat commented on docs/installation/bootstrap.rst
> +   #. First, retrieve the public key from the Bootstrap node.
No need for ordination (First, next, finally, etc.) in ordered lists

2019-12-19 15:34 UTC, wabernat commented on docs/installation/bootstrap.rst
>      In case of virtual network (or any network which enforces source and
"In case of" gets a lot of wear... "For" will often do the same job...

2019-12-19 15:34 UTC, wabernat commented on docs/installation/bootstrap.rst
>  to monitor the system will not be running (the respective :term:`Pods <Pod>`
(their respective...

2019-12-19 15:34 UTC, wabernat commented on docs/installation/bootstrap.rst
> +will remain in **Pending** state), because they require persistent storage to be
in a "pending" state)
or 
will remain pending)

2019-12-19 15:34 UTC, wabernat commented on docs/installation/bootstrap.rst
> +**Running** state.
Make sure all Pods on the bootstrap node are running.

2019-12-19 15:34 UTC, wabernat commented on docs/installation/bootstrap.rst
>     - Mention ``/var/log/metalk8s-bootstrap.log`` and the command-line options
This looks as if someone requested that you mention these things and it was taken down literally.

2019-12-19 15:34 UTC, wabernat commented on docs/installation/bootstrap.rst
>     - Add Salt master/minion logs, and explain how to run a specific state from
Again...

2019-12-19 15:34 UTC, wabernat commented on docs/installation/expansion.rst
>  :ref:`the introduction <quickstart-intro-install-plan>`.
review link name.

2019-12-19 15:34 UTC, wabernat commented on docs/installation/expansion.rst
> +The Bootstrap being already deployed, the other nodes' deployment runs
Once the Bootstrap is deployed,

2019-12-19 15:34 UTC, wabernat commented on docs/installation/expansion.rst
> +The Bootstrap being already deployed, the other nodes' deployment runs
the other nodes will undergo four deployment runs: two for... and two more for

2019-12-19 15:34 UTC, wabernat commented on docs/installation/expansion.rst
> +#. From the Node list page, any yet-to-be-deployed Node click **Deploy**.
From the Node list page, click the **Deploy** button for any Node that has not yet been deployed.

2019-12-19 15:34 UTC, wabernat commented on docs/installation/expansion.rst
> +   Once clicked, the button will change to **Deploying**. Click it again to
the button changes to

(maintain present tense as much as possible)

2019-12-19 15:34 UTC, wabernat commented on docs/installation/expansion.rst
>        - UI should parse these events further
These two lines aren't saying much. Indicative mood, please. I don't know if the second bullet is telling me what the machine does or what someone wants from you.

2019-12-19 15:34 UTC, wabernat commented on docs/installation/expansion.rst
> +#. When complete, click **Back to nodes list**. The new Node should be in a
When deployment is complete, 

(dangling modifier)

2019-12-19 15:34 UTC, wabernat commented on docs/installation/expansion.rst
>  :ref:`this procedure <quickstart-services-salt>`.
check ref.

2019-12-19 15:34 UTC, wabernat commented on docs/installation/expansion.rst
> +Checking the Cluster Health
Checking Cluster Health

2019-12-19 15:34 UTC, wabernat commented on docs/installation/index.rst
> +Installation Guide
Installation (no need for "Guide")

2019-12-19 15:34 UTC, wabernat commented on docs/installation/introduction.rst
>  containers and can be managed by the cluster (control-plane services,
This entire topic belongs in Operation. Installation guides should be task-focused, not concept-focused.

2019-12-19 15:34 UTC, wabernat commented on docs/installation/introduction.rst
> +Control-plane and Workload-plane
No hyphens

2019-12-19 15:34 UTC, wabernat commented on docs/installation/introduction.rst
>  offloaded to other nodes from the workload-plane (without the ``etcd`` taint).
no hyphen

2019-12-19 15:34 UTC, wabernat commented on docs/installation/introduction.rst
>  taints, are applied to a :term:`Node`, only :term:`Pods <Pod>` with the
When a taint or set of taints is applied

2019-12-19 15:34 UTC, wabernat commented on docs/installation/introduction.rst
>    In practice, this role will be used in conjunction with the ``master``
role is used

2019-12-19 15:34 UTC, wabernat commented on docs/installation/introduction.rst
>    and ``etcd`` roles for bootstrapping the control-plane.
no hyphen

2019-12-19 15:34 UTC, wabernat commented on docs/installation/introduction.rst
>  In this guide, the depicted installation procedure is for a medium sized
medium-sized

2019-12-19 15:34 UTC, wabernat commented on docs/installation/services.rst
> +   running,
If you want to make a sentence out of this, add a conjunction. Otherwise, hanging fragments is fine. Init-cap structured list items.

2019-12-19 15:34 UTC, wabernat commented on docs/installation/setup.rst
> +Each machine should be accessible through SSH from the host. As part of the
must be accessible

2019-12-19 15:34 UTC, wabernat commented on docs/installation/setup.rst
> +In order to reach the cluster-provided UIs from the host, the host needs to be
For the host to reach the cluster-provided UIs, it must be able...

2019-12-19 15:34 UTC, wabernat commented on docs/installation/setup.rst
> +For more detail(s), refer to the official RedHat documentation:
Red Hat

2020-01-03 12:42 UTC, bert-e commented
# Conflict




There is a conflict between your branch `documentation/installation-fixes` and the
destination branch `development/2.4`.

Please resolve the conflict on **the feature branch** (`documentation/installation-fixes`).

```bash
 $ git fetch
 $ git checkout origin/documentation/installation-fixes
 $ git merge origin/development/2.4
 $ # <intense conflict resolution>
 $ git commit
 $ git push origin HEAD:documentation/installation-fixes
```

2020-01-13 10:08 UTC, gdemonet requested changes
Some comments, I think there are still some changes requested by @wabernatScality to handle here

2020-01-13 10:08 UTC, gdemonet commented on docs/installation/bootstrap.rst
> +   node. Mount this ISO file at the specific following path:
This is actually not an absolute requirement (or shouldn't be). Our Bootstrap script should be responsible for mounting the ISOs referenced in the `archives` key of the BootstrapConfiguration file. But let's keep it like this for now, I'll open a PR for this specific aspect.

2020-01-13 10:08 UTC, gdemonet commented on docs/installation/bootstrap.rst
> +    For virtual network (or any network which enforces source and
minor:

```suggestion
    For virtual networks (or any network which enforces source and
```

2020-01-13 10:08 UTC, gdemonet commented on docs/installation/bootstrap.rst
>     - Mention ``/var/log/metalk8s-bootstrap.log`` and the command-line options
`todo` blocks are not rendered in the final HTML, so they're here for writers as things left to tackle, in future improvements. No need to worry about them right now.

2020-01-13 10:08 UTC, gdemonet commented on docs/installation/expansion.rst
> +Creating a Node Object
Hum, why the capitalization of `Object`? Because `Node` actually references an exisiting `kind` of K8s object, which is why we special-case it, and that's not the case for `Object`.

2020-01-13 10:08 UTC, gdemonet commented on docs/installation/expansion.rst
>        - UI should parse these events further
It's a `todo`, not user-facing but writer-facing - let's not bother further

2020-01-13 10:08 UTC, gdemonet commented on docs/installation/introduction.rst
>  containers and can be managed by the cluster (control-plane services,
I kind of disagree on this statement. How can one install a product without understanding the concepts needed to configure this installation process?

2020-01-13 10:08 UTC, gdemonet commented on docs/installation/setup.rst
>  applications on your control-plane nodes).
Not sure this kind of recommendation (or the one saying we'll need 4 deployments, in the Expansion doc) is still relevant in a generic Installation guide. Worth revamping after all the other tasks are done (I'll tackle this in #2112).

2020-01-13 10:08 UTC, gdemonet commented on docs/installation/setup.rst
>  able to connect to workload-plane IPs of the machines.
Uh, this was not updated recently... Could you replace `workload-plane` with `control-plane` here please?

2020-01-13 10:08 UTC, bert-e commented
# Branches have diverged



This pull request's source branch `documentation/installation-fixes` has diverged from
`development/2.4` by more than 50 commits.

To avoid any integration risks, please re-synchronize them using one of the
following solutions:

* Merge `origin/development/2.4` into `documentation/installation-fixes`
* Rebase `documentation/installation-fixes` onto `origin/development/2.4`

Note: If you choose to rebase, you may have to ask me to rebuild
integration branches using the `reset` command.

2020-01-14 15:00 UTC, lucieleonard commented on docs/installation/expansion.rst
> +Creating a Node Object
Tech Writing rules for titles (you capitalize nouns and verbs)

2020-01-14 15:04 UTC, lucieleonard commented on docs/installation/introduction.rst
>  containers and can be managed by the cluster (control-plane services,
I would say it belongs to a reference topic. But we don't have any reference for now, and it's better to have it before performing anything to be sure the user sees and understands it beforehand.

2020-01-15 09:15 UTC, gdemonet requested changes
Small change request, otherwise LGTM. And you'll need to rebase on the latest `development/2.4` before we can merge this ;)

2020-01-15 09:15 UTC, gdemonet commented on docs/installation/setup.rst
> +Each machine must be a member of both the control-plane and workload-plane
Weren't we supposed to remove hyphens, per William's recommendation?

```suggestion
Each machine must be a member of both the control plane and workload plane
```

2020-01-15 09:15 UTC, gdemonet commented on docs/installation/setup.rst
Could be nice to suggest a simple way of accessing private networks, I'll open a tracking ticket for this (e.g. setting up a VPN over SSH with `sshuttle`, exposing a public IP to route an AWS VPC...).

2020-01-15 09:59 UTC, bert-e commented
# History mismatch



Merge commit #d2c910f735c14162b68eb640466e8e0ea2066dfa on the integration branch
`w/2.5/documentation/installation-fixes` is merging a branch which is neither the current
branch `documentation/installation-fixes` nor the development branch
`development/2.5`.

It is likely due to a rebase of the branch `documentation/installation-fixes` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**

2020-01-15 10:07 UTC, lucieleonard commented
/reset

2020-01-15 10:07 UTC, bert-e commented
# Lossy reset warning



There seems to be *manual* commits on integration branches (e.g. conflict
resolutions) that will be lost if you chose to *reset*.

**You can use the `force_reset` command if you still want me
to delete those branches.**

2020-01-15 10:08 UTC, bert-e commented
# History mismatch



Merge commit #d2c910f735c14162b68eb640466e8e0ea2066dfa on the integration branch
`w/2.5/documentation/installation-fixes` is merging a branch which is neither the current
branch `documentation/installation-fixes` nor the development branch
`development/2.5`.

It is likely due to a rebase of the branch `documentation/installation-fixes` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**

2020-01-15 10:08 UTC, lucieleonard commented
/force_reset

2020-01-15 10:08 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.

2020-01-15 10:08 UTC, bert-e commented
# Conflict




A conflict has been raised during the creation of
integration branch `w/2.5/documentation/installation-fixes` with contents from `documentation/installation-fixes`
and `development/2.5`.

**I have not created the integration branch.**


Here are the steps to resolve this conflict:

```bash
 $ git fetch
 $ git checkout -B w/2.5/documentation/installation-fixes origin/development/2.5
 $ git merge origin/documentation/installation-fixes
 $ # <intense conflict resolution>
 $ git commit
 $ git push -u origin w/2.5/documentation/installation-fixes
```

2020-01-15 10:19 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @tcarmet

* @jbertran

* @carlito-scality

* @slaperche-scality

* @nicolast

* @teddyandrieux

* @monpote

* @sayf-eddine-scality

* @nootal

* @alexandre-allard-scality

* @gdemonet

* @lucieleonard

* @thomasdanan

* @cmonfort





The following reviewers are expecting changes from the author, or must review again:

* @gdemonet

2020-01-15 10:39 UTC, gdemonet submitted a review, later dismissed

2020-01-15 10:39 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @tcarmet

* @jbertran

* @carlito-scality

* @slaperche-scality

* @nicolast

* @teddyandrieux

* @monpote

* @sayf-eddine-scality

* @nootal

* @alexandre-allard-scality

* @gdemonet

* @lucieleonard

* @thomasdanan

* @cmonfort

2020-01-15 16:17 UTC, bert-e commented
# History mismatch



Merge commit #bfc133d4643f24861b937ebfec7e4878a0128d60 on the integration branch
`w/2.5/documentation/installation-fixes` is merging a branch which is neither the current
branch `documentation/installation-fixes` nor the development branch
`development/2.5`.

It is likely due to a rebase of the branch `documentation/installation-fixes` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**

2020-01-15 16:18 UTC, gdemonet commented
/reset

2020-01-15 16:18 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.

2020-01-15 16:18 UTC, bert-e commented
# Conflict




A conflict has been raised during the creation of
integration branch `w/2.5/documentation/installation-fixes` with contents from `documentation/installation-fixes`
and `development/2.5`.

**I have not created the integration branch.**


Here are the steps to resolve this conflict:

```bash
 $ git fetch
 $ git checkout -B w/2.5/documentation/installation-fixes origin/development/2.5
 $ git merge origin/documentation/installation-fixes
 $ # <intense conflict resolution>
 $ git commit
 $ git push -u origin w/2.5/documentation/installation-fixes
```

2020-01-15 17:05 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @tcarmet

* @jbertran

* @carlito-scality

* @slaperche-scality

* @nicolast

* @teddyandrieux

* @monpote

* @sayf-eddine-scality

* @nootal

* @alexandre-allard-scality

* @gdemonet

* @lucieleonard

* @thomasdanan

* @cmonfort

2020-01-15 17:07 UTC, gdemonet approved these changes

2020-01-16 10:17 UTC, lucieleonard commented
/approve

2020-01-16 10:17 UTC, bert-e commented
# Build failed



The build for [commit](https://github.com/scality/metalk8s/commit/148cd900b564eed82e8d42c7777d414a5bd05f7e) did not succeed in branch w/2.5/documentation/installation-fixes.




*The following options are set:* **approve**

2020-01-16 10:30 UTC, bert-e commented
# Build failed



The build for [commit](https://github.com/scality/metalk8s/commit/b322516b52c56cc5793490928db8428166d4ec76) did not succeed in branch documentation/installation-fixes.




*The following options are set:* **approve**

2020-01-16 15:32 UTC, bert-e commented
# Build failed



The build for [commit](https://github.com/scality/metalk8s/commit/148cd900b564eed82e8d42c7777d414a5bd05f7e) did not succeed in branch w/2.5/documentation/installation-fixes.




*The following options are set:* **approve**

2020-01-16 16:21 UTC, bert-e commented
# Build failed



The build for [commit](https://github.com/scality/metalk8s/commit/b322516b52c56cc5793490928db8428166d4ec76) did not succeed in branch documentation/installation-fixes.




*The following options are set:* **approve**

2020-01-16 18:00 UTC, bert-e commented
# Build failed



The build for [commit](https://github.com/scality/metalk8s/commit/148cd900b564eed82e8d42c7777d414a5bd05f7e) did not succeed in branch w/2.5/documentation/installation-fixes.




*The following options are set:* **approve**

2020-01-16 20:47 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/2.4`

* :heavy_check_mark: `development/2.5`



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`
* `development/2.0`
* `development/2.1`
* `development/2.2`
* `development/2.3`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2020-01-16 20:47 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/2.4`

* :heavy_check_mark: `development/2.5`



The following branches have **NOT** changed:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`
* `development/2.0`
* `development/2.1`
* `development/2.2`
* `development/2.3`



Please check the status of the associated issue None.

Goodbye lucieleonard.

2020-01-16 20:47 UTC, merged