Kibana index vars
scality/metalk8s pull request #233
Opened 2018-08-02 12:55 UTC by alxf

Fix #224

2018-08-02 17:08 UTC, NicolasT commented on roles/cluster_logging/files/kibana/provision-index.sh
> +if [ ! -z "$INDEX_PATTERN" ]; then
Pretty sure this doesn't work with `set -u` :smiley: 

Also, no real reason for this... `logstash-*` is not some 'magically correct' value. Rather have the whole script fail when a required 'config value' is not set.

2018-08-02 17:10 UTC, NicolasT commented on roles/cluster_logging/templates/kibana-index-provisioning-configmap.yml.j2
> +  index.pattern: {{ kibana_index_pattern }}
Not sure it makes sense setting things through the `ConfigMap`. Just set them in `env` in the `Job` template.

2018-08-02 17:10 UTC, NicolasT commented on roles/cluster_logging/templates/kibana-index-provisioning-job.yml.j2
> +             valueFrom:
See above. This seems like a useless indirection.

2018-08-02 18:34 UTC, NicolasT commented
Retarget to `development/1.1`? It's not really a 'bugfix' for 1.0.

2018-08-03 10:18 UTC, Zempashi submitted a review, later dismissed

2018-08-03 17:06 UTC, NicolasT requested changes
Minor change requested, otherwise LGTM

2018-08-03 17:06 UTC, NicolasT commented on ChangeLog.rst
> +:ghissue:`224` - variabilize the kibana index pattern and service name in
`Kibana`

2018-08-03 17:06 UTC, NicolasT commented on docs/architecture/cluster-services.rst
> -.. note:: When accessing Kibana for the first time, an *index pattern* for the
Good call!

2018-08-03 17:34 UTC, NicolasT approved these changes
Maybe consider a squash-merge :)

2018-08-04 00:36 UTC, NicolasT requested changes
I just tried to run this on my existing 1.0.0 cluster, and it fails:

```

TASK [cluster_logging : apply the Kibana job setup] *******************************************************************
ok: [metalk8s-master-01] => (item={u'md5sum': u'ada28baf671387a9477bbe7caaf66458', u'uid': 0, u'owner': u'root', 'diff': [], u'size': 2545, u'group': u'root', '_ansible_item_label': u'kibana-index-provisioning-configmap.yml', 'failed': False, u'state': u'file', u'gid': 0, u'secontext': u'system_u:object_r:etc_t:s0', u'invocation': {u'module_args': {u'directory_mode': None, u'force': True, u'remote_src': None, u'_original_basename': u'kibana-index-provisioning-configmap.yml.j2', u'owner': None, u'follow': False, u'local_follow': None, u'group': None, u'unsafe_writes': None, u'setype': None, u'content': None, u'serole': None, u'dest': u'/etc/kubernetes/addons/kibana/kibana-index-provisioning-configmap.yml', u'selevel': None, u'regexp': None, u'validate': None, u'src': u'/home/centos/.ansible/tmp/ansible-tmp-1533342757.31-192752873956431/source', u'checksum': u'd58990c56f6eb5ccdb01343f659be12d79113e22', u'seuser': None, u'delimiter': None, u'mode': None, u'attributes': None, u'backup': False}}, '_ansible_parsed': True, u'dest': u'/etc/kubernetes/addons/kibana/kibana-index-provisioning-configmap.yml', '_ansible_item_result': True, u'src': u'/home/centos/.ansible/tmp/ansible-tmp-1533342757.31-192752873956431/source', '_ansible_no_log': False, u'checksum': u'd58990c56f6eb5ccdb01343f659be12d79113e22', u'changed': True, 'item': u'kibana-index-provisioning-configmap.yml', u'mode': u'0644', '_ansible_ignore_errors': None}) => {"changed": false, "item": {"changed": true, "checksum": "d58990c56f6eb5ccdb01343f659be12d79113e22", "dest": "/etc/kubernetes/addons/kibana/kibana-index-provisioning-configmap.yml", "diff": [], "failed": false, "gid": 0, "group": "root", "invocation": {"module_args": {"_original_basename": "kibana-index-provisioning-configmap.yml.j2", "attributes": null, "backup": false, "checksum": "d58990c56f6eb5ccdb01343f659be12d79113e22", "content": null, "delimiter": null, "dest": "/etc/kubernetes/addons/kibana/kibana-index-provisioning-configmap.yml", "directory_mode": null, "follow": false, "force": true, "group": null, "local_follow": null, "mode": null, "owner": null, "regexp": null, "remote_src": null, "selevel": null, "serole": null, "setype": null, "seuser": null, "src": "/home/centos/.ansible/tmp/ansible-tmp-1533342757.31-192752873956431/source", "unsafe_writes": null, "validate": null}}, "item": "kibana-index-provisioning-configmap.yml", "md5sum": "ada28baf671387a9477bbe7caaf66458", "mode": "0644", "owner": "root", "secontext": "system_u:object_r:etc_t:s0", "size": 2545, "src": "/home/centos/.ansible/tmp/ansible-tmp-1533342757.31-192752873956431/source", "state": "file", "uid": 0}, "msg": "success: configmap \"kibana-index-provisioning\" configured"}
failed: [metalk8s-master-01] (item={u'md5sum': u'371dce745a372a5fd744abe2318146dd', u'uid': 0, u'owner': u'root', 'diff': [], u'size': 868, u'group': u'root', '_ansible_item_label': u'kibana-index-provisioning-job.yml', 'failed': False, u'state': u'file', u'gid': 0, u'secontext': u'system_u:object_r:etc_t:s0', u'invocation': {u'module_args': {u'directory_mode': None, u'force': True, u'remote_src': None, u'_original_basename': u'kibana-index-provisioning-job.yml.j2', u'owner': None, u'follow': False, u'local_follow': None, u'group': None, u'unsafe_writes': None, u'setype': None, u'content': None, u'serole': None, u'dest': u'/etc/kubernetes/addons/kibana/kibana-index-provisioning-job.yml', u'selevel': None, u'regexp': None, u'validate': None, u'src': u'/home/centos/.ansible/tmp/ansible-tmp-1533342761.62-157363397757258/source', u'checksum': u'665b2c7ca8bd817275bc9e4272e13e6fe2d99514', u'seuser': None, u'delimiter': None, u'mode': None, u'attributes': None, u'backup': False}}, '_ansible_parsed': True, u'dest': u'/etc/kubernetes/addons/kibana/kibana-index-provisioning-job.yml', '_ansible_item_result': True, u'src': u'/home/centos/.ansible/tmp/ansible-tmp-1533342761.62-157363397757258/source', '_ansible_no_log': False, u'checksum': u'665b2c7ca8bd817275bc9e4272e13e6fe2d99514', u'changed': True, 'item': u'kibana-index-provisioning-job.yml', u'mode': u'0644', '_ansible_ignore_errors': None}) => {"changed": false, "item": {"changed": true, "checksum": "665b2c7ca8bd817275bc9e4272e13e6fe2d99514", "dest": "/etc/kubernetes/addons/kibana/kibana-index-provisioning-job.yml", "diff": [], "failed": false, "gid": 0, "group": "root", "invocation": {"module_args": {"_original_basename": "kibana-index-provisioning-job.yml.j2", "attributes": null, "backup": false, "checksum": "665b2c7ca8bd817275bc9e4272e13e6fe2d99514", "content": null, "delimiter": null, "dest": "/etc/kubernetes/addons/kibana/kibana-index-provisioning-job.yml", "directory_mode": null, "follow": false, "force": true, "group": null, "local_follow": null, "mode": null, "owner": null, "regexp": null, "remote_src": null, "selevel": null, "serole": null, "setype": null, "seuser": null, "src": "/home/centos/.ansible/tmp/ansible-tmp-1533342761.62-157363397757258/source", "unsafe_writes": null, "validate": null}}, "item": "kibana-index-provisioning-job.yml", "md5sum": "371dce745a372a5fd744abe2318146dd", "mode": "0644", "owner": "root", "secontext": "system_u:object_r:etc_t:s0", "size": 868, "src": "/home/centos/.ansible/tmp/ansible-tmp-1533342761.62-157363397757258/source", "state": "file", "uid": 0}, "msg": "error running kubectl (/usr/local/bin/kubectl --namespace=kube-ops apply --force --filename=/etc/kubernetes/addons/kibana/kibana-index-provisioning-job.yml) command (rc=1), out='', err='The Job \"kibana-index-provisioning\" is invalid: spec.template: Invalid value: core.PodTemplateSpec{ObjectMeta:v1.ObjectMeta{Name:\"kibana-index-provisioning\", GenerateName:\"\", Namespace:\"\", SelfLink:\"\", UID:\"\", ResourceVersion:\"\", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{\"app\":\"kibana\", \"component\":\"index-provisioning\", \"controller-uid\":\"7bd58465-94c2-11e8-b29e-fa163e143620\", \"heritage\":\"MetalK8s\", \"job-name\":\"kibana-index-provisioning\"}, Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:\"\"}, Spec:core.PodSpec{Volumes:[]core.Volume{core.Volume{Name:\"scripts\", VolumeSource:core.VolumeSource{HostPath:(*core.HostPathVolumeSource)(nil), EmptyDir:(*core.EmptyDirVolumeSource)(nil), GCEPersistentDisk:(*core.GCEPersistentDiskVolumeSource)(nil), AWSElasticBlockStore:(*core.AWSElasticBlockStoreVolumeSource)(nil), GitRepo:(*core.GitRepoVolumeSource)(nil), Secret:(*core.SecretVolumeSource)(nil), NFS:(*core.NFSVolumeSource)(nil), ISCSI:(*core.ISCSIVolumeSource)(nil), Glusterfs:(*core.GlusterfsVolumeSource)(nil), PersistentVolumeClaim:(*core.PersistentVolumeClaimVolumeSource)(nil), RBD:(*core.RBDVolumeSource)(nil), Quobyte:(*core.QuobyteVolumeSource)(nil), FlexVolume:(*core.FlexVolumeSource)(nil), Cinder:(*core.CinderVolumeSource)(nil), CephFS:(*core.CephFSVolumeSource)(nil), Flocker:(*core.FlockerVolumeSource)(nil), DownwardAPI:(*core.DownwardAPIVolumeSource)(nil), FC:(*core.FCVolumeSource)(nil), AzureFile:(*core.AzureFileVolumeSource)(nil), ConfigMap:(*core.ConfigMapVolumeSource)(0xc425caf980), VsphereVolume:(*core.VsphereVirtualDiskVolumeSource)(nil), AzureDisk:(*core.AzureDiskVolumeSource)(nil), PhotonPersistentDisk:(*core.PhotonPersistentDiskVolumeSource)(nil), Projected:(*core.ProjectedVolumeSource)(nil), PortworxVolume:(*core.PortworxVolumeSource)(nil), ScaleIO:(*core.ScaleIOVolumeSource)(nil), StorageOS:(*core.StorageOSVolumeSource)(nil)}}}, InitContainers:[]core.Container(nil), Containers:[]core.Container{core.Container{Name:\"provision-index\", Image:\"appropriate/curl\", Command:[]stri [...]

2018-08-04 00:51 UTC, NicolasT commented
So, https://github.com/scality/metalk8s/pull/233#pullrequestreview-143366361 actually makes sense and hence this PR is blocked for now.

The problem: we're trying to update the `env` part of the `Pod` defined in the `Job`, which is not permitted (it'd be impossible to change the environment variables of a running container!)

The playbook will need to delete the `Job` before continuing. Also, I wish the `Job` would be auto GC'ed after it completes (or some time after).

2018-08-06 08:34 UTC, alxf commented
Hi @NicolasT, seems there is no way to cleanup job on completion, a part putting a mechanism in place to cleanup these resources periodically. So i just cleanup the job with ansible, before spawning it again. Is it a working solution for you ?

2018-08-06 16:10 UTC, NicolasT commented
Yeah, I wish it was possible but it's not :smiley: So the solution you implemented works for me (it'd be required anyway!).

I'll try the current version on my cluster.

2018-08-06 17:35 UTC, NicolasT requested changes
There's a bug... Also, will need to merge in recent changes from target branch.

2018-08-06 17:35 UTC, NicolasT commented on roles/cluster_logging/files/kibana/provision-index.sh
> +if [ ! -z "$INDEX_PATTERN" ]; then
> -z STRING: the length of STRING is zero
> -n STRING: the length of STRING is nonzero

So, it's either `if [ -z "$INDEX_PATTERN" ]` or `if [ ! -n "$INDEX_PATTERN" ]`, not this one :smiley:

2018-08-06 18:24 UTC, NicolasT submitted a review, later dismissed

2018-08-07 18:42 UTC, NicolasT approved these changes

2018-08-08 13:06 UTC, closed without merging