Organize grafana dashboards
scality/metalk8s pull request #249
Opened 2018-08-07 13:16 UTC by alxf

Fix #208, but only the tag part of the ticket.

2018-08-07 19:30 UTC, NicolasT requested changes
Tag changes are suggestions. I think going beyond the name of the service being exposed (which is already part of the dashboard title anyway) is worth it.

2018-08-07 19:30 UTC, NicolasT commented on roles/kube_prometheus/hack/fix-dashboard.py
> +        dashboard['tags'] = []
`dashboard['tags'] = list(set(tag.strip() for tag in tags.split(',')))`

2018-08-07 19:30 UTC, NicolasT commented on roles/kube_prometheus/Makefile
> +files/additional-dashboards/kube-prometheus-etcd-dashboard.yml: TAGS=etcd
`etcd,cluster`

2018-08-07 19:30 UTC, NicolasT commented on roles/kube_prometheus/Makefile
> +files/additional-dashboards/kube-prometheus-elasticsearch-dashboard.yml: TAGS=elasticsearch
`elasticsearch,logging`

2018-08-07 19:30 UTC, NicolasT commented on roles/kube_prometheus/Makefile
> +files/additional-dashboards/kube-prometheus-node-exporter-dashboard.yml: TAGS=nodes
`nodes,cluster`

2018-08-07 19:30 UTC, NicolasT commented on roles/kube_prometheus/Makefile
> +files/additional-dashboards/kube-prometheus-prometheus-dashboard.yml: TAGS=dashboard,prometheus
`prometheus,metrics`

2018-08-07 19:30 UTC, NicolasT commented on roles/kube_prometheus/Makefile
> +files/additional-dashboards/kube-prometheus-calico-dashboard.yml: TAGS=calico
`calico,cluster,networking`

2018-08-07 19:30 UTC, NicolasT commented on roles/kube_prometheus/Makefile
> +files/additional-dashboards/kube-prometheus-calico2-dashboard.yml: TAGS=calico
`calico,cluster,networking`

2018-08-07 19:30 UTC, NicolasT commented on roles/kube_prometheus/Makefile
> +files/additional-dashboards/kube-prometheus-nginx-ingress-dashboard.yml: TAGS=nginx
`nginx,cluster,networking`

2018-08-07 19:30 UTC, NicolasT commented on roles/kube_prometheus/Makefile
> +files/additional-dashboards/%.yml: hack/fix-dashboard.py
Should this also include `Makefile` then? I seem to remember @Zempashi brought this up some time ago as well.

2018-08-08 12:32 UTC, alxf commented
@NicolasT I made all changes, but i need to reopen the pull request for bert-e.

2018-08-08 12:36 UTC, closed without merging