docs: Remove old bootstrap node before restoration
scality/metalk8s pull request #2562
Opened 2020-05-19 14:34 UTC by TeddyAndrieux

**Component**:

bootstrap restore

**Summary**:

- Install kubectl on all master nodes
- Add documentation to delete old bootstrap node before restoration

---

Fixes: #2561

2020-05-19 14:34 UTC, bert-e commented
# Hello teddyandrieux,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/metalk8s/bert-e/doc/user).





*Status report is not available.*

2020-05-19 14:34 UTC, bert-e commented
# Branches have diverged



This pull request's source branch `bugfix/GH-2561-clean-bootstrap-pods-in-restore` has diverged from
`development/2.6` by more than 50 commits.

To avoid any integration risks, please re-synchronize them using one of the
following solutions:

* Merge `origin/development/2.6` into `bugfix/GH-2561-clean-bootstrap-pods-in-restore`
* Rebase `bugfix/GH-2561-clean-bootstrap-pods-in-restore` onto `origin/development/2.6`

Note: If you choose to rebase, you may have to ask me to rebuild
integration branches using the `reset` command.

2020-05-19 14:35 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `bugfix/GH-2561-clean-bootstrap-pods-in-restore` into
`development/2.4`
* [w/2.5/bugfix/GH-2561-clean-bootstrap-pods-in-restore](https://github.com/scality/metalk8s/compare/development/2.5...w/2.5/bugfix/GH-2561-clean-bootstrap-pods-in-restore) will be merged into `development/2.5` 
* [w/2.6/bugfix/GH-2561-clean-bootstrap-pods-in-restore](https://github.com/scality/metalk8s/compare/development/2.6...w/2.6/bugfix/GH-2561-clean-bootstrap-pods-in-restore) will be merged into `development/2.6` 



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`
* `development/2.0`
* `development/2.1`
* `development/2.2`
* `development/2.3`




You can set option `create_pull_requests` if you need me to create
**integration pull requests** in addition to integration branches, with:

```
@bert-e create_pull_requests
```

2020-05-19 14:35 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @nootal

* @alexandre-allard-scality

* @lucieleonard

* @sayf-eddine-scality

* @slaperche-scality

* @nicolast

* @gdemonet

* @carlito-scality

* @thomasdanan

* @jbertran

* @teddyandrieux

* @cmonfort

* @monpote

2020-05-19 15:06 UTC, gdemonet requested changes
Some wording changes, but OK with the idea :ok_hand:

2020-05-19 15:06 UTC, gdemonet commented on docs/operation/bootstrap_backup_restore.rst
> +As MetalK8s do not support multi bootstrap right now, the old bootstrap node
```suggestion
Since multiple bootstrap nodes are not supported for the moment, the old bootstrap Node
```

2020-05-19 15:06 UTC, gdemonet commented on docs/operation/bootstrap_backup_restore.rst
> +need to be removed before performing the restoration. To do so, run the
```suggestion
needs to be removed before performing the restoration. To do so, run the
```

2020-05-19 15:06 UTC, gdemonet commented on docs/operation/bootstrap_backup_restore.rst
> +following commands from a working Node with ``master`` role:
```suggestion
following commands from a working master node:
```

2020-05-19 15:06 UTC, gdemonet commented on docs/operation/bootstrap_backup_restore.rst
> +  kubectl delete node <node_name> --kubeconfig=/etc/kubernetes/admin.conf
In a single command:

```shell
kubectl --kubeconfig=/etc/kubernetes/admin.conf \
    delete nodes --selector="node-role.kubernetes.io/bootstrap" --all
```

2020-05-19 15:06 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @nootal

* @alexandre-allard-scality

* @lucieleonard

* @sayf-eddine-scality

* @slaperche-scality

* @nicolast

* @gdemonet

* @carlito-scality

* @thomasdanan

* @jbertran

* @teddyandrieux

* @cmonfort

* @monpote





The following reviewers are expecting changes from the author, or must review again:

* @gdemonet

2020-05-19 15:11 UTC, TeddyAndrieux commented on docs/operation/bootstrap_backup_restore.rst
> +following commands from a working Node with ``master`` role:
This one was just to match the step just before for etcd

2020-05-19 15:12 UTC, TeddyAndrieux commented on docs/operation/bootstrap_backup_restore.rst
> +  kubectl delete node <node_name> --kubeconfig=/etc/kubernetes/admin.conf
Hmm no, it's bit dangerous to me. I really prefer the user to choose it manually

2020-05-19 15:22 UTC, bert-e commented
# History mismatch



Merge commit #f436758486ae4b45b0183df421b88cfe3386c2ec on the integration branch
`w/2.5/bugfix/GH-2561-clean-bootstrap-pods-in-restore` is merging a branch which is neither the current
branch `bugfix/GH-2561-clean-bootstrap-pods-in-restore` nor the development branch
`development/2.5`.

It is likely due to a rebase of the branch `bugfix/GH-2561-clean-bootstrap-pods-in-restore` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**

2020-05-19 15:23 UTC, TeddyAndrieux commented
/reset

2020-05-19 15:23 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.

2020-05-19 15:24 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `bugfix/GH-2561-clean-bootstrap-pods-in-restore` into
`development/2.4`
* [w/2.5/bugfix/GH-2561-clean-bootstrap-pods-in-restore](https://github.com/scality/metalk8s/compare/development/2.5...w/2.5/bugfix/GH-2561-clean-bootstrap-pods-in-restore) will be merged into `development/2.5` 
* [w/2.6/bugfix/GH-2561-clean-bootstrap-pods-in-restore](https://github.com/scality/metalk8s/compare/development/2.6...w/2.6/bugfix/GH-2561-clean-bootstrap-pods-in-restore) will be merged into `development/2.6` 



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`
* `development/2.0`
* `development/2.1`
* `development/2.2`
* `development/2.3`




You can set option `create_pull_requests` if you need me to create
**integration pull requests** in addition to integration branches, with:

```
@bert-e create_pull_requests
```

2020-05-19 15:24 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @nootal

* @alexandre-allard-scality

* @lucieleonard

* @sayf-eddine-scality

* @slaperche-scality

* @nicolast

* @gdemonet

* @carlito-scality

* @thomasdanan

* @jbertran

* @teddyandrieux

* @cmonfort

* @monpote





The following reviewers are expecting changes from the author, or must review again:

* @gdemonet

2020-05-19 15:25 UTC, gdemonet commented on docs/operation/bootstrap_backup_restore.rst
> +  kubectl delete node <node_name> --kubeconfig=/etc/kubernetes/admin.conf
OK

2020-05-19 15:26 UTC, gdemonet commented on docs/operation/bootstrap_backup_restore.rst
> +following commands from a working Node with ``master`` role:
Given our brand new writing guidelines TechPubs provided, we should change both... But OK for this PR, and we'll do a cleanup of all docs before end of Q2 delivery.

2020-05-19 15:26 UTC, gdemonet approved these changes

2020-05-19 15:26 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @nootal

* @alexandre-allard-scality

* @lucieleonard

* @sayf-eddine-scality

* @slaperche-scality

* @nicolast

* @gdemonet

* @carlito-scality

* @thomasdanan

* @jbertran

* @teddyandrieux

* @cmonfort

* @monpote

2020-05-19 17:27 UTC, TeddyAndrieux commented
/approve

2020-05-19 17:35 UTC, bert-e commented
# Build failed



The build for [commit](https://github.com/scality/metalk8s/commit/5f280c3663de765167e77e298a33b24774b866a3) did not succeed in branch w/2.6/bugfix/GH-2561-clean-bootstrap-pods-in-restore.




*The following options are set:* **approve**

2020-05-19 17:36 UTC, bert-e commented
# Build failed



The build for [commit](https://github.com/scality/metalk8s/commit/ab89db662f774d550265488575aab5ca35e4f6aa) did not succeed in branch bugfix/GH-2561-clean-bootstrap-pods-in-restore.




*The following options are set:* **approve**

2020-05-19 18:06 UTC, bert-e commented
# Build failed



The build for [commit](https://github.com/scality/metalk8s/commit/5f280c3663de765167e77e298a33b24774b866a3) did not succeed in branch w/2.6/bugfix/GH-2561-clean-bootstrap-pods-in-restore.




*The following options are set:* **approve**

2020-05-19 18:14 UTC, bert-e commented
# Build failed



The build for [commit](https://github.com/scality/metalk8s/commit/ab89db662f774d550265488575aab5ca35e4f6aa) did not succeed in branch bugfix/GH-2561-clean-bootstrap-pods-in-restore.




*The following options are set:* **approve**

2020-05-19 21:50 UTC, bert-e commented
# Build failed



The build for [commit](https://github.com/scality/metalk8s/commit/6424cd8a2f2797d8cfdd888385d76ea8f3b00ccb) did not succeed in branch w/2.5/bugfix/GH-2561-clean-bootstrap-pods-in-restore.




*The following options are set:* **approve**

2020-05-20 08:50 UTC, bert-e commented
# Build failed



The build for [commit](https://github.com/scality/metalk8s/commit/5f280c3663de765167e77e298a33b24774b866a3) did not succeed in branch w/2.6/bugfix/GH-2561-clean-bootstrap-pods-in-restore.




*The following options are set:* **approve**

2020-05-20 09:47 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/2.4`

* :heavy_check_mark: `development/2.5`

* :heavy_check_mark: `development/2.6`



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`
* `development/2.0`
* `development/2.1`
* `development/2.2`
* `development/2.3`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2020-05-20 13:13 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/2.4`

* :heavy_check_mark: `development/2.5`

* :heavy_check_mark: `development/2.6`



The following branches have **NOT** changed:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`
* `development/2.0`
* `development/2.1`
* `development/2.2`
* `development/2.3`



Please check the status of the associated issue GH-2561.

Goodbye teddyandrieux.

2020-05-20 13:13 UTC, merged