doc: update CSC doc for basic alerting
scality/metalk8s pull request #2588
Opened 2020-06-03 07:11 UTC by alexandre-allard-scality

Rework a bit the documentation and add:
* how to configure inhibition rules
* how to configure receiver
* how to create new Prometheus rules
* how to customize predefined Prometheus rules

2020-06-03 07:11 UTC, bert-e commented
# Hello alexandre-allard-scality,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/metalk8s/bert-e/doc/user).





*Status report is not available.*

2020-06-03 07:11 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @jbertran

* @tcarmet

* @thomasdanan

* @sayf-eddine-scality

* @lucieleonard

* @monpote

* @carlito-scality

* @cmonfort

* @nicolast

* @slaperche-scality

* @teddyandrieux

* @nootal

* @gdemonet

* @alexandre-allard-scality

2020-06-04 08:00 UTC, thomasdanan submitted a review, later dismissed
just perfect to me ...  All the important use cases are covered
In a later stage we may want to have one dedicated page per service (or at least separate Dex and Prom/AM)
Thanks

2020-06-04 08:00 UTC, thomasdanan commented on docs/operation/cluster_and_service_configuration.rst
> +There is more receivers available (PagerDuty, OpsGenie, HipChat, ...).
```suggestion
There are more receivers available (PagerDuty, OpsGenie, HipChat, ...).
```

2020-06-04 08:00 UTC, thomasdanan commented on docs/operation/cluster_and_service_configuration.rst
> +     saltenv=metalk8s-|version|
can't we have a variable to pick up the version corresponding to the doc? I always struggle when it comes to guessing the right version naming ...

2020-06-04 08:03 UTC, Ebaneck commented on docs/operation/cluster_and_service_configuration.rst
> +     saltenv=metalk8s-|version|
Probably need to use something like
`.. parsed-literal::``

2020-06-04 08:31 UTC, Ebaneck requested changes

2020-06-04 08:31 UTC, Ebaneck commented on docs/operation/cluster_and_service_configuration.rst
> +The Alertmanager handles alerts sent by Prometheus.
Remove `The`

2020-06-04 08:31 UTC, Ebaneck commented on docs/operation/cluster_and_service_configuration.rst
> +other alerts.
`Alert inhibition rules allow making one alert inhibit notifications for some other alerts.`

2020-06-04 08:31 UTC, Ebaneck commented on docs/operation/cluster_and_service_configuration.rst
> +Adding receiver
`Adding receivers` ?

2020-06-04 08:31 UTC, Ebaneck commented on docs/operation/cluster_and_service_configuration.rst
> +Receivers allow to configure where the alert notifications are sent.
`Receivers allow configuring where the alert notifications are sent`

2020-06-04 08:31 UTC, Ebaneck commented on docs/operation/cluster_and_service_configuration.rst
> +applied with Salt.
Any changes made to .... ??

2020-06-04 08:31 UTC, Ebaneck commented on docs/operation/cluster_and_service_configuration.rst
> +ConfigMap in namespace ``metalk8s-monitoring`` must be edited as follow.
s/follow/follows/

2020-06-04 08:31 UTC, Ebaneck commented on docs/operation/cluster_and_service_configuration.rst
> +
s/to define/defining/

2020-06-04 08:31 UTC, bert-e commented
# Branches have diverged



This pull request's source branch `documentation/basic-alerting` has diverged from
`development/2.6` by more than 50 commits.

To avoid any integration risks, please re-synchronize them using one of the
following solutions:

* Merge `origin/development/2.6` into `documentation/basic-alerting`
* Rebase `documentation/basic-alerting` onto `origin/development/2.6`

Note: If you choose to rebase, you may have to ask me to rebuild
integration branches using the `reset` command.

2020-06-04 09:23 UTC, alexandre-allard-scality commented on docs/operation/cluster_and_service_configuration.rst
> +     saltenv=metalk8s-|version|
Done

2020-06-04 09:26 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @jbertran

* @tcarmet

* @thomasdanan

* @sayf-eddine-scality

* @lucieleonard

* @monpote

* @carlito-scality

* @cmonfort

* @nicolast

* @slaperche-scality

* @teddyandrieux

* @nootal

* @gdemonet

* @alexandre-allard-scality





The following reviewers are expecting changes from the author, or must review again:

* @ebaneck

2020-06-04 09:52 UTC, Ebaneck submitted a review, later dismissed
Good for me!

2020-06-04 09:52 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @jbertran

* @tcarmet

* @thomasdanan

* @sayf-eddine-scality

* @lucieleonard

* @monpote

* @carlito-scality

* @cmonfort

* @nicolast

* @slaperche-scality

* @teddyandrieux

* @nootal

* @gdemonet

* @alexandre-allard-scality

2020-06-04 10:05 UTC, alexandre-allard-scality commented
@thomasdanan thanks for the feedback, as you said, I think we may want to have this documentation appears in `operation/cluster_monitoring` and in another dedicated page for Dex, otherwise this page will keep growing with new services.
For now, I've added a link in the `operation/cluster_monitoring`, so that a user will be able to find how to customize/configure its monitoring easily.

2020-06-04 10:07 UTC, alexandre-allard-scality commented
/approve

2020-06-04 10:07 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @jbertran

* @tcarmet

* @thomasdanan

* @sayf-eddine-scality

* @lucieleonard

* @monpote

* @carlito-scality

* @cmonfort

* @nicolast

* @slaperche-scality

* @teddyandrieux

* @nootal

* @gdemonet

* @alexandre-allard-scality










*The following options are set:* **approve**

2020-06-04 10:08 UTC, Ebaneck approved these changes

2020-06-04 10:12 UTC, thomasdanan approved these changes

2020-06-04 12:35 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/2.6`



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`
* `development/2.0`
* `development/2.1`
* `development/2.2`
* `development/2.3`
* `development/2.4`
* `development/2.5`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2020-06-04 12:35 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/2.6`



The following branches have **NOT** changed:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`
* `development/2.0`
* `development/2.1`
* `development/2.2`
* `development/2.3`
* `development/2.4`
* `development/2.5`



Please check the status of the associated issue None.

Goodbye alexandre-allard-scality.

2020-06-04 12:35 UTC, merged