salt: Ensure node exists before marking it as bootstrap
scality/metalk8s pull request #2610
Opened 2020-06-08 17:33 UTC by TeddyAndrieux

**Component**:

'salt'

**Context**: 

#2601 

**Summary**:

In restore script, we configure a new bootstrap node according to a
backup file and just after kubelet installation we try to mark the node
as bootstrap node but kubelet may take some time to register so the
salt state may fail.
This commit adds a state to check that the node exists with a retry logic
in case kubelet not register yet when calling the salt state

---

Fixes: #2601

2020-06-08 17:34 UTC, bert-e commented
# Hello teddyandrieux,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/metalk8s/bert-e/doc/user).





*Status report is not available.*

2020-06-08 17:34 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `bugfix/GH-2601-fix-bootstrap-restore` into
`development/2.4`
* [w/2.5/bugfix/GH-2601-fix-bootstrap-restore](https://github.com/scality/metalk8s/compare/development/2.5...w/2.5/bugfix/GH-2601-fix-bootstrap-restore) will be merged into `development/2.5` 
* [w/2.6/bugfix/GH-2601-fix-bootstrap-restore](https://github.com/scality/metalk8s/compare/development/2.6...w/2.6/bugfix/GH-2601-fix-bootstrap-restore) will be merged into `development/2.6` 



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`
* `development/2.0`
* `development/2.1`
* `development/2.2`
* `development/2.3`




You can set option `create_pull_requests` if you need me to create
**integration pull requests** in addition to integration branches, with:

```
@bert-e create_pull_requests
```

2020-06-08 17:34 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @jbertran

* @tcarmet

* @thomasdanan

* @sayf-eddine-scality

* @lucieleonard

* @monpote

* @carlito-scality

* @cmonfort

* @nicolast

* @slaperche-scality

* @teddyandrieux

* @nootal

* @gdemonet

* @alexandre-allard-scality

2020-06-09 07:26 UTC, gdemonet requested changes
Small change on the helper, otherwise LGTM!

2020-06-09 07:26 UTC, gdemonet commented on salt/_modules/metalk8s_kubernetes.py
> +    return bool(
Any falsy result outside of `None` would be a bug, so let's make this method somewhat more obvious:

```python
return get_object(...) is not None
```

2020-06-09 07:26 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @jbertran

* @tcarmet

* @thomasdanan

* @sayf-eddine-scality

* @lucieleonard

* @monpote

* @carlito-scality

* @cmonfort

* @nicolast

* @slaperche-scality

* @teddyandrieux

* @nootal

* @gdemonet

* @alexandre-allard-scality





The following reviewers are expecting changes from the author, or must review again:

* @gdemonet

2020-06-09 08:07 UTC, bert-e commented
# History mismatch



Merge commit #1bbd182c1fad5f6bc80de147892482ec225b7548 on the integration branch
`w/2.5/bugfix/GH-2601-fix-bootstrap-restore` is merging a branch which is neither the current
branch `bugfix/GH-2601-fix-bootstrap-restore` nor the development branch
`development/2.5`.

It is likely due to a rebase of the branch `bugfix/GH-2601-fix-bootstrap-restore` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**

2020-06-09 08:07 UTC, TeddyAndrieux commented
/reset

2020-06-09 08:07 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.

2020-06-09 08:07 UTC, TeddyAndrieux commented
/approve

2020-06-09 08:07 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `bugfix/GH-2601-fix-bootstrap-restore` into
`development/2.4`
* [w/2.5/bugfix/GH-2601-fix-bootstrap-restore](https://github.com/scality/metalk8s/compare/development/2.5...w/2.5/bugfix/GH-2601-fix-bootstrap-restore) will be merged into `development/2.5` 
* [w/2.6/bugfix/GH-2601-fix-bootstrap-restore](https://github.com/scality/metalk8s/compare/development/2.6...w/2.6/bugfix/GH-2601-fix-bootstrap-restore) will be merged into `development/2.6` 



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`
* `development/2.0`
* `development/2.1`
* `development/2.2`
* `development/2.3`




You can set option `create_pull_requests` if you need me to create
**integration pull requests** in addition to integration branches, with:

```
@bert-e create_pull_requests
```

2020-06-09 08:07 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @jbertran

* @tcarmet

* @thomasdanan

* @sayf-eddine-scality

* @lucieleonard

* @monpote

* @carlito-scality

* @cmonfort

* @nicolast

* @slaperche-scality

* @teddyandrieux

* @nootal

* @gdemonet

* @alexandre-allard-scality





The following reviewers are expecting changes from the author, or must review again:

* @gdemonet

2020-06-09 08:07 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @jbertran

* @tcarmet

* @thomasdanan

* @sayf-eddine-scality

* @lucieleonard

* @monpote

* @carlito-scality

* @cmonfort

* @nicolast

* @slaperche-scality

* @teddyandrieux

* @nootal

* @gdemonet

* @alexandre-allard-scality





The following reviewers are expecting changes from the author, or must review again:

* @gdemonet







*The following options are set:* **approve**

2020-06-09 08:22 UTC, gdemonet submitted a review, later dismissed

2020-06-09 08:22 UTC, bert-e commented
# Build failed



The build for [commit](https://github.com/scality/metalk8s/commit/19de953e234c91d0a0002efc3f0f6a3b456d1cc2) did not succeed in branch bugfix/GH-2601-fix-bootstrap-restore.




*The following options are set:* **approve**

2020-06-09 08:25 UTC, bert-e commented
# History mismatch



Merge commit #19de953e234c91d0a0002efc3f0f6a3b456d1cc2 on the integration branch
`w/2.5/bugfix/GH-2601-fix-bootstrap-restore` is merging a branch which is neither the current
branch `bugfix/GH-2601-fix-bootstrap-restore` nor the development branch
`development/2.5`.

It is likely due to a rebase of the branch `bugfix/GH-2601-fix-bootstrap-restore` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**





*The following options are set:* **approve**

2020-06-09 08:25 UTC, TeddyAndrieux commented
/reset

2020-06-09 08:26 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.






*The following options are set:* **approve**

2020-06-09 08:26 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `bugfix/GH-2601-fix-bootstrap-restore` into
`development/2.4`
* [w/2.5/bugfix/GH-2601-fix-bootstrap-restore](https://github.com/scality/metalk8s/compare/development/2.5...w/2.5/bugfix/GH-2601-fix-bootstrap-restore) will be merged into `development/2.5` 
* [w/2.6/bugfix/GH-2601-fix-bootstrap-restore](https://github.com/scality/metalk8s/compare/development/2.6...w/2.6/bugfix/GH-2601-fix-bootstrap-restore) will be merged into `development/2.6` 



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`
* `development/2.0`
* `development/2.1`
* `development/2.2`
* `development/2.3`




You can set option `create_pull_requests` if you need me to create
**integration pull requests** in addition to integration branches, with:

```
@bert-e create_pull_requests
```







*The following options are set:* **approve**

2020-06-09 08:26 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @jbertran

* @tcarmet

* @thomasdanan

* @sayf-eddine-scality

* @lucieleonard

* @monpote

* @carlito-scality

* @cmonfort

* @nicolast

* @slaperche-scality

* @teddyandrieux

* @nootal

* @gdemonet

* @alexandre-allard-scality










*The following options are set:* **approve**

2020-06-09 08:27 UTC, gdemonet approved these changes

2020-06-09 09:10 UTC, bert-e commented
# Build failed



The build for [commit](https://github.com/scality/metalk8s/commit/7aceefdc9cf3da3677cf9c14142c77868af56c88) did not succeed in branch w/2.5/bugfix/GH-2601-fix-bootstrap-restore.




*The following options are set:* **approve**

2020-06-09 09:45 UTC, bert-e commented
# Build failed



The build for [commit](https://github.com/scality/metalk8s/commit/56e0ee4550f038f5cd1526cb615f1dfa9f4b3daf) did not succeed in branch w/2.6/bugfix/GH-2601-fix-bootstrap-restore.




*The following options are set:* **approve**

2020-06-09 12:45 UTC, alexandre-allard approved these changes

2020-06-09 13:22 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/2.4`

* :heavy_check_mark: `development/2.5`

* :heavy_check_mark: `development/2.6`



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`
* `development/2.0`
* `development/2.1`
* `development/2.2`
* `development/2.3`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2020-06-09 13:22 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/2.4`

* :heavy_check_mark: `development/2.5`

* :heavy_check_mark: `development/2.6`



The following branches have **NOT** changed:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`
* `development/2.0`
* `development/2.1`
* `development/2.2`
* `development/2.3`



Please check the status of the associated issue GH-2601.

Goodbye teddyandrieux.

2020-06-09 13:22 UTC, merged