ui/volumes: Replace Prometheus alerts by AlertManager
scality/metalk8s pull request #2815
Opened 2020-09-28 15:44 UTC by alexis-ld

**Component**: ui, volumes, monitoring

**Context**: 

Currently the alerts from the volumes page come from the Prometheus API. We want to switch to use AlertManager's API instead.

**Summary**:

The AlertManager service was already implemented. I added a few Redux actions to replicate the current refresh behavior we had with Prometheus.

**Acceptance criteria**: 

* Alerts on the volume page are retrieved from AlertManager's API
* Alerts are displayed properly

---

Closes: #2793

2020-09-28 15:44 UTC, bert-e commented
# Hello alexis-ld,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/metalk8s/bert-e/doc/user).





*Status report is not available.*

2020-09-28 15:44 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @tcarmet

* @nicolast

* @lucieleonard

* @alexandre-allard-scality

* @monpote

* @slaperche-scality

* @teddyandrieux

* @cmonfort

* @thomasdanan

* @carlito-scality

* @jbertran

* @sayf-eddine-scality

* @gdemonet

* @nootal

2020-09-29 16:32 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `improvement/2793-alertmanager-api` into
`development/2.6`
* [w/2.7/improvement/2793-alertmanager-api](https://github.com/scality/metalk8s/compare/development/2.7...w/2.7/improvement/2793-alertmanager-api) will be merged into `development/2.7` 



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`
* `development/2.0`
* `development/2.1`
* `development/2.2`
* `development/2.3`
* `development/2.4`
* `development/2.5`




You can set option `create_pull_requests` if you need me to create
**integration pull requests** in addition to integration branches, with:

```
@bert-e create_pull_requests
```

2020-09-29 16:32 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @tcarmet

* @nicolast

* @lucieleonard

* @alexandre-allard-scality

* @monpote

* @slaperche-scality

* @teddyandrieux

* @cmonfort

* @thomasdanan

* @carlito-scality

* @jbertran

* @sayf-eddine-scality

* @gdemonet

* @nootal

2020-09-29 19:16 UTC, ChengYanJin requested changes
Hello @alexis-ld,

Thanks for working on this, there is one thing you may miss.
We actually compute the `Health` in the volume list table base on the alerts.

So we need to update  **getAlerts** Selector in getVolumeListData() too. 
Suggest change:
`const getAlerts = (state) => state?.app?.alerts;`

Thank you!

2020-09-29 19:16 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @tcarmet

* @nicolast

* @lucieleonard

* @alexandre-allard-scality

* @monpote

* @slaperche-scality

* @teddyandrieux

* @cmonfort

* @thomasdanan

* @carlito-scality

* @jbertran

* @sayf-eddine-scality

* @gdemonet

* @nootal





The following reviewers are expecting changes from the author, or must review again:

* @chengyanjin

2020-10-01 11:21 UTC, bert-e commented
# History mismatch



Merge commit #552c5825d60816001e13c7837005d762a199a62b on the integration branch
`w/2.7/improvement/2793-alertmanager-api` is merging a branch which is neither the current
branch `improvement/2793-alertmanager-api` nor the development branch
`development/2.7`.

It is likely due to a rebase of the branch `improvement/2793-alertmanager-api` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**

2020-10-01 11:22 UTC, alexis-ld commented
@ChengYanJin Indeed, I missed that :) thank you for the feedback.

Updated and squashed.

2020-10-01 12:40 UTC, ChengYanJin commented on ui/src/services/NodeVolumesUtils.js
> +const getAlerts = (state) => state?.app?.alerts;
Sorry my mistake. 
```suggestion
const getAlerts = (state) => state?.app?.alerts?.list;
```

2020-10-01 13:06 UTC, ChengYanJin requested changes
Hello @alexis-ld ,

One last change then we are good to go! 
Thank you!

2020-10-01 13:06 UTC, ChengYanJin commented on ui/src/services/NodeVolumesUtils.js
> +const getAlerts = (state) => state?.app?.alerts;
Hello @alexis-ld ,

Sorry, we still miss one thing that I forgot last time. 
We actually have a unit test for `getVolumeListData` function. It returns the data used by Volume Table. 
We may want to update the `stateApp` that used by the unit test.

```javascript
const stateApp = {
  app: {
    nodes: {...},
    pods: {...},
    volumes: {...},
    monitoring: {...},
    // we may want to add this.
    alerts: { list : [] }, 
}
```

I would suggest you run the unit test `npm run test` to see if the new changes will break the test or not.
Thank you!

2020-10-02 13:01 UTC, alexis-ld commented
@ChengYanJin Adapted tests and squashed commits. :)

2020-10-02 14:10 UTC, ChengYanJin approved these changes
LGTM!

2020-10-02 14:57 UTC, thomasdanan approved these changes

2020-10-02 15:08 UTC, thomasdanan commented
/reset

2020-10-02 15:08 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.

2020-10-02 15:08 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `improvement/2793-alertmanager-api` into
`development/2.6`
* [w/2.7/improvement/2793-alertmanager-api](https://github.com/scality/metalk8s/compare/development/2.7...w/2.7/improvement/2793-alertmanager-api) will be merged into `development/2.7` 



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`
* `development/2.0`
* `development/2.1`
* `development/2.2`
* `development/2.3`
* `development/2.4`
* `development/2.5`




You can set option `create_pull_requests` if you need me to create
**integration pull requests** in addition to integration branches, with:

```
@bert-e create_pull_requests
```

2020-10-02 15:08 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @tcarmet

* @nicolast

* @lucieleonard

* @alexandre-allard-scality

* @monpote

* @slaperche-scality

* @teddyandrieux

* @cmonfort

* @thomasdanan

* @carlito-scality

* @jbertran

* @sayf-eddine-scality

* @gdemonet

* @nootal

2020-10-02 15:09 UTC, alexis-ld commented
/approve

2020-10-02 16:09 UTC, bert-e commented
# Build failed



The build for [commit](https://github.com/scality/metalk8s/commit/4f9e638f0e2ad27de9a53c59317e0ff6f1f8187f) did not succeed in branch w/2.7/improvement/2793-alertmanager-api.




*The following options are set:* **approve**

2020-10-05 08:15 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/2.6`

* :heavy_check_mark: `development/2.7`



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`
* `development/2.0`
* `development/2.1`
* `development/2.2`
* `development/2.3`
* `development/2.4`
* `development/2.5`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2020-10-05 09:20 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/2.6`

* :heavy_check_mark: `development/2.7`



The following branches have **NOT** changed:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`
* `development/2.0`
* `development/2.1`
* `development/2.2`
* `development/2.3`
* `development/2.4`
* `development/2.5`



Please check the status of the associated issue None.

Goodbye alexis-ld.

2020-10-05 09:20 UTC, merged