[UI] Add node overview tab in new node page
scality/metalk8s pull request #2834
Opened 2020-10-06 12:57 UTC by ChengYanJin

**Component**: ui, nodes

**Context**: 

**Summary**:
- There is an alert filter component missing. 
- The format of the creation time does not update yet. We need to first upgrade the react-intl to V3+ to bring the [FormattedDateParts](https://formatjs.io/docs/react-intl/components/#formatteddateparts) API available. Since there are a lot of breaking changes, will do it in another PR.

**Acceptance criteria**: 
![image](https://user-images.githubusercontent.com/18453133/95203635-503bd080-07e3-11eb-8b02-2dcdb6315f9e.png)

---

Closes: #2774

2020-10-06 12:57 UTC, bert-e commented
# Hello chengyanjin,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/metalk8s/bert-e/doc/user).





*Status report is not available.*

2020-10-06 12:57 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `improvement/2774-add-node-detail-in-the-health-tab` into
`development/2.6`
* [w/2.7/improvement/2774-add-node-detail-in-the-health-tab](https://github.com/scality/metalk8s/compare/development/2.7...w/2.7/improvement/2774-add-node-detail-in-the-health-tab) will be merged into `development/2.7` 



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`
* `development/2.0`
* `development/2.1`
* `development/2.2`
* `development/2.3`
* `development/2.4`
* `development/2.5`




You can set option `create_pull_requests` if you need me to create
**integration pull requests** in addition to integration branches, with:

```
@bert-e create_pull_requests
```

2020-10-06 12:57 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @tcarmet

* @nicolast

* @lucieleonard

* @alexandre-allard-scality

* @monpote

* @slaperche-scality

* @teddyandrieux

* @cmonfort

* @thomasdanan

* @carlito-scality

* @jbertran

* @sayf-eddine-scality

* @gdemonet

* @nootal

2020-10-07 08:08 UTC, thomasdanan requested changes
Hello @ChengYanJin, here are few general comments:

When selecting a tab, I see it should be in a "light" gray (compare to the other tabs which should be dark)
The background of the tab content is not as per it is in miro.
When the left nav bar is expanded, the separation between the left zone and the sight zone can be improved.

All the rest is perfect

2020-10-07 08:08 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @tcarmet

* @nicolast

* @lucieleonard

* @alexandre-allard-scality

* @monpote

* @slaperche-scality

* @teddyandrieux

* @cmonfort

* @thomasdanan

* @carlito-scality

* @jbertran

* @sayf-eddine-scality

* @gdemonet

* @nootal





The following reviewers are expecting changes from the author, or must review again:

* @thomasdanan

2020-10-08 09:27 UTC, bert-e commented
# History mismatch



Merge commit #6513591417362736a6faf1ef761fe035033a47b8 on the integration branch
`w/2.7/improvement/2774-add-node-detail-in-the-health-tab` is merging a branch which is neither the current
branch `improvement/2774-add-node-detail-in-the-health-tab` nor the development branch
`development/2.7`.

It is likely due to a rebase of the branch `improvement/2774-add-node-detail-in-the-health-tab` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**

2020-10-09 14:21 UTC, bert-e commented
# History mismatch



Merge commit #0e17ec4359401054309e13028ee488a10fde3ebd on the integration branch
`w/2.7/improvement/2774-add-node-detail-in-the-health-tab` is merging a branch which is neither the current
branch `improvement/2774-add-node-detail-in-the-health-tab` nor the development branch
`development/2.7`.

It is likely due to a rebase of the branch `improvement/2774-add-node-detail-in-the-health-tab` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**

2020-10-12 12:07 UTC, thomasdanan submitted a review, later dismissed

2020-10-12 13:56 UTC, bert-e commented
# History mismatch



Merge commit #d6b9ca14bd037fc1c39481fbb2144b862fc61a22 on the integration branch
`w/2.7/improvement/2774-add-node-detail-in-the-health-tab` is merging a branch which is neither the current
branch `improvement/2774-add-node-detail-in-the-health-tab` nor the development branch
`development/2.7`.

It is likely due to a rebase of the branch `improvement/2774-add-node-detail-in-the-health-tab` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**

2020-10-12 21:12 UTC, MonPote requested changes
I have some `CORS` issue on my ptf so I didn't have the opportunity to test correctly this PR.
I've some comments on React Router, please have a look at it :)

2020-10-12 21:12 UTC, MonPote commented on ui/src/containers/NodePageRSP.js
> +            path={`/newNodes/${selectedNodeName}/overview`}
I think you should do something like this (nested route) instead of hardcoded.
https://reactrouter.com/web/example/nesting
That way, when you will get ride of the old /nodes, you don't need to change a single line code except.
```diff
- <PrivateRoute path="/newNodes" component={NodePage} />
+ <PrivateRoute path="/nodes" component={NodePage} />
```

In your case, it should be something like this :
```js
let { path, url } = useRouteMatch();
<Route
  path={`${path}/overview`}
  render={() => (
     <NodePageOverviewTab
       selectedNodeName={selectedNodeName}
       nodeTableData={nodeTableData}
       nodes={nodes}
       volumes={volumes}
       pods={pods}
    />
  )}
/>
```

2020-10-12 21:12 UTC, MonPote commented on ui/src/components/NodeListTable.js
> +              <StatusText textColor={statusColor}>
You should have a key field (because of the map).
I wonder why react didn't show you a warning.

2020-10-12 21:12 UTC, MonPote commented on ui/src/containers/NodePageRSP.js
> +      onClick: () => history.push(`/newNodes/${selectedNodeName}/overview`),
See next comment.

2020-10-13 08:49 UTC, ChengYanJin commented on ui/src/containers/NodePageRSP.js
> +            path={`/newNodes/${selectedNodeName}/overview`}
Indeed! That's a smart move!

2020-10-13 09:22 UTC, gdemonet commented on ui/src/containers/NodePageRSP.js
> +            path={`/newNodes/${selectedNodeName}/overview`}
cf. #2838 :wink:

2020-10-14 13:58 UTC, MonPote submitted a review, later dismissed

2020-10-14 21:06 UTC, MonPote approved these changes

2020-10-15 09:25 UTC, ChengYanJin commented
/approve

2020-10-15 09:25 UTC, bert-e commented
# History mismatch



Merge commit #d6b9ca14bd037fc1c39481fbb2144b862fc61a22 on the integration branch
`w/2.7/improvement/2774-add-node-detail-in-the-health-tab` is merging a branch which is neither the current
branch `improvement/2774-add-node-detail-in-the-health-tab` nor the development branch
`development/2.7`.

It is likely due to a rebase of the branch `improvement/2774-add-node-detail-in-the-health-tab` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**





*The following options are set:* **approve**

2020-10-15 09:29 UTC, ChengYanJin commented
/reset

2020-10-15 09:29 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.






*The following options are set:* **approve**

2020-10-15 09:29 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `improvement/2774-add-node-detail-in-the-health-tab` into
`development/2.6`
* [w/2.7/improvement/2774-add-node-detail-in-the-health-tab](https://github.com/scality/metalk8s/compare/development/2.7...w/2.7/improvement/2774-add-node-detail-in-the-health-tab) will be merged into `development/2.7` 



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`
* `development/2.0`
* `development/2.1`
* `development/2.2`
* `development/2.3`
* `development/2.4`
* `development/2.5`




You can set option `create_pull_requests` if you need me to create
**integration pull requests** in addition to integration branches, with:

```
@bert-e create_pull_requests
```







*The following options are set:* **approve**

2020-10-15 11:15 UTC, bert-e commented
# Build failed



The build for [commit](https://github.com/scality/metalk8s/commit/4961c94e3aef8b8813bded3eebad7ab06d16b650) did not succeed in branch w/2.7/improvement/2774-add-node-detail-in-the-health-tab.




*The following options are set:* **approve**

2020-10-16 07:44 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/2.6`

* :heavy_check_mark: `development/2.7`



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`
* `development/2.0`
* `development/2.1`
* `development/2.2`
* `development/2.3`
* `development/2.4`
* `development/2.5`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2020-10-16 09:16 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/2.6`

* :heavy_check_mark: `development/2.7`



The following branches have **NOT** changed:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`
* `development/2.0`
* `development/2.1`
* `development/2.2`
* `development/2.3`
* `development/2.4`
* `development/2.5`



Please check the status of the associated issue None.

Goodbye chengyanjin.

2020-10-16 09:16 UTC, merged