[UI] Fix the vulnerable package
scality/metalk8s pull request #2863
Opened 2020-10-15 12:52 UTC by ChengYanJin

**Component**: ui, dependency

**Context**: 
There appears to be a high severity CVE in the serialize-javascript dependency of the UI, at least in the version that's currently locked. Would be good to bump that.

**Summary**:
- NPM Audit to automatically find and fix security vulnerabilities in npm dependencies.
- Manually upgrade the **compression-webpack-plugin** to the latest major version.

**Acceptance criteria**: 
Should fix the vulnerable package. And the UI should work as before.

2020-10-15 12:53 UTC, bert-e commented
# Hello chengyanjin,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/metalk8s/bert-e/doc/user).





*Status report is not available.*

2020-10-15 12:53 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `improvement/fix-the-vulnerable-package` into
`development/2.6`
* [w/2.7/improvement/fix-the-vulnerable-package](https://github.com/scality/metalk8s/compare/development/2.7...w/2.7/improvement/fix-the-vulnerable-package) will be merged into `development/2.7` 



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`
* `development/2.0`
* `development/2.1`
* `development/2.2`
* `development/2.3`
* `development/2.4`
* `development/2.5`




You can set option `create_pull_requests` if you need me to create
**integration pull requests** in addition to integration branches, with:

```
@bert-e create_pull_requests
```

2020-10-15 12:53 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @tcarmet

* @nicolast

* @lucieleonard

* @alexandre-allard-scality

* @monpote

* @slaperche-scality

* @teddyandrieux

* @cmonfort

* @thomasdanan

* @carlito-scality

* @jbertran

* @sayf-eddine-scality

* @gdemonet

* @nootal

2020-10-19 08:02 UTC, gdemonet requested changes
It would have been cleaner to get one commit for the `npm audit`, and another one for the manual update of `compression-webpack-plugin` + `serialize-javascript`. Also, in the commit message "fix the vulnerable package" is not really explicit: which package? what vulnerability?
Last comment about the commits: do not split updates to `package.json` and `package.lock`, they ought to **always** be in sync in the Git history.

2020-10-19 08:02 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @tcarmet

* @nicolast

* @lucieleonard

* @alexandre-allard-scality

* @monpote

* @slaperche-scality

* @teddyandrieux

* @cmonfort

* @thomasdanan

* @carlito-scality

* @jbertran

* @sayf-eddine-scality

* @gdemonet

* @nootal





The following reviewers are expecting changes from the author, or must review again:

* @gdemonet

2020-10-19 08:15 UTC, slaperche-scality commented
> Also, in the commit message "fix the vulnerable package" is not really explicit: which package? what vulnerability?

This is especially important for the security-related commit, we should provide a link to the CVE or equivalent in the commit message.

2020-10-20 13:04 UTC, bert-e commented
# History mismatch



Merge commit #68ffd829cc4ecbcfc12790ec86c1ddbb98031a2e on the integration branch
`w/2.7/improvement/fix-the-vulnerable-package` is merging a branch which is neither the current
branch `improvement/fix-the-vulnerable-package` nor the development branch
`development/2.7`.

It is likely due to a rebase of the branch `improvement/fix-the-vulnerable-package` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**

2020-10-20 13:06 UTC, ChengYanJin commented
/reset

2020-10-20 13:07 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.

2020-10-20 13:07 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `improvement/fix-the-vulnerable-package` into
`development/2.6`
* [w/2.7/improvement/fix-the-vulnerable-package](https://github.com/scality/metalk8s/compare/development/2.7...w/2.7/improvement/fix-the-vulnerable-package) will be merged into `development/2.7` 



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`
* `development/2.0`
* `development/2.1`
* `development/2.2`
* `development/2.3`
* `development/2.4`
* `development/2.5`




You can set option `create_pull_requests` if you need me to create
**integration pull requests** in addition to integration branches, with:

```
@bert-e create_pull_requests
```

2020-10-20 13:07 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @tcarmet

* @nicolast

* @lucieleonard

* @alexandre-allard-scality

* @monpote

* @slaperche-scality

* @teddyandrieux

* @cmonfort

* @thomasdanan

* @carlito-scality

* @jbertran

* @sayf-eddine-scality

* @gdemonet

* @nootal





The following reviewers are expecting changes from the author, or must review again:

* @gdemonet

2020-10-21 07:09 UTC, gdemonet requested changes
Almost perfect :)

Please add a link to the CVE affecting `serialize-javascript` in the relevant commit (you can find details [here](https://github.com/scality/metalk8s/network/alert/ui/package-lock.json/serialize-javascript/open))
While you're at it, I realized there are two other packages affected by security issues:
- [`object-path`](https://github.com/scality/metalk8s/network/alert/ui/package-lock.json/object-path/open)
- [`node-fetch`](https://github.com/scality/metalk8s/network/alert/ui/package-lock.json/object-path/open)

Would you mind fixing those as well in this PR? Thanks!

2020-10-21 09:28 UTC, bert-e commented
# History mismatch



Merge commit #43a021506992c678c09f490e6b4f17b03d8449a1 on the integration branch
`w/2.7/improvement/fix-the-vulnerable-package` is merging a branch which is neither the current
branch `improvement/fix-the-vulnerable-package` nor the development branch
`development/2.7`.

It is likely due to a rebase of the branch `improvement/fix-the-vulnerable-package` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**

2020-10-21 09:46 UTC, ChengYanJin commented
Hello @gdemonet,

Fixed the high severity alert caused by `object-path` too.

When I tried to fix the low severity alert cased by `node-path`, I noticed that it is the sub dependency of `@kubernetes/client-node`

The version we're using is `0.10.2`, should we consider to bump the version of @kubernetes/client-node too?
Please see the [release node ](https://github.com/kubernetes-client/javascript/releases)

2020-10-21 15:06 UTC, gdemonet approved these changes

2020-10-21 15:21 UTC, ChengYanJin commented
/approve

2020-10-21 15:21 UTC, bert-e commented
# History mismatch



Merge commit #43a021506992c678c09f490e6b4f17b03d8449a1 on the integration branch
`w/2.7/improvement/fix-the-vulnerable-package` is merging a branch which is neither the current
branch `improvement/fix-the-vulnerable-package` nor the development branch
`development/2.7`.

It is likely due to a rebase of the branch `improvement/fix-the-vulnerable-package` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**





*The following options are set:* **approve**

2020-10-21 15:21 UTC, ChengYanJin commented
/reset

2020-10-21 15:22 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.






*The following options are set:* **approve**

2020-10-21 15:22 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `improvement/fix-the-vulnerable-package` into
`development/2.6`
* [w/2.7/improvement/fix-the-vulnerable-package](https://github.com/scality/metalk8s/compare/development/2.7...w/2.7/improvement/fix-the-vulnerable-package) will be merged into `development/2.7` 



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`
* `development/2.0`
* `development/2.1`
* `development/2.2`
* `development/2.3`
* `development/2.4`
* `development/2.5`




You can set option `create_pull_requests` if you need me to create
**integration pull requests** in addition to integration branches, with:

```
@bert-e create_pull_requests
```







*The following options are set:* **approve**

2020-10-21 16:43 UTC, bert-e commented
# Build failed



The build for [commit](https://github.com/scality/metalk8s/commit/e0f37b1f2efe4ab959f024099745f662b5cfbb48) did not succeed in branch w/2.7/improvement/fix-the-vulnerable-package.




*The following options are set:* **approve**

2020-10-21 20:40 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/2.6`

* :heavy_check_mark: `development/2.7`



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`
* `development/2.0`
* `development/2.1`
* `development/2.2`
* `development/2.3`
* `development/2.4`
* `development/2.5`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2020-10-23 09:30 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/2.6`

* :heavy_check_mark: `development/2.7`



The following branches have **NOT** changed:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`
* `development/2.0`
* `development/2.1`
* `development/2.2`
* `development/2.3`
* `development/2.4`
* `development/2.5`



Please check the status of the associated issue None.

Goodbye chengyanjin.

2020-10-23 09:31 UTC, merged