Prometheus retention customization
scality/metalk8s pull request #2968
Opened 2020-12-09 12:02 UTC by alexandre-allard-scality

**Component**: salt, monitoring

**Context**: See #2953

**Summary**:

**Acceptance criteria**: 

---

Closes: #2953

2020-12-09 12:02 UTC, bert-e commented
# Hello alexandre-allard-scality,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/metalk8s/bert-e/doc/user).





*Status report is not available.*

2020-12-09 12:02 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @jbertran

* @chengyanjin

* @slaperche-scality

* @thomasdanan

* @lucieleonard

* @gdemonet

* @teddyandrieux

* @nootal

* @monpote

* @tcarmet

* @sayf-eddine-scality

* @cmonfort

* @nicolast

* @carlito-scality

* @alexandre-allard-scality

2020-12-09 12:04 UTC, alexandre-allard-scality commented on salt/metalk8s/addons/prometheus-operator/deployed/chart.sls
> +        - --collector.diskstats.ignored-devices=^(ram|fd)\\d+$
Ignore this line as this comes from the Prometheus stack version bump (I forgot to re-render after having changed the values in `charts/kube-prometheus-stack.yaml`)

2020-12-09 12:05 UTC, alexandre-allard-scality commented
Do we want a changelog entry for this kind of stuff ?

2020-12-10 12:38 UTC, gdemonet requested changes
Mostly about user-facing information. This PR would also need a changelog entry, since we're adding a feature.

2020-12-10 12:38 UTC, gdemonet commented on docs/operation/cluster_and_service_configuration.rst
> +This functionality can be actived:
From #2953:

> If we do so, we need to warn the user in the documentation that actually Prometheus does not take in account the WAL size, so the required size is greater than `retentionSize` (add at least 10% to be safe).

So we're missing a warning :wink:

2020-12-10 12:38 UTC, gdemonet commented on salt/metalk8s/addons/prometheus-operator/config/prometheus.yaml
> +    retention_size: 0
Since this file is `literal-include`d in our docs, would make sense to add a comment here saying that `0` means size-based retention is disabled.

2020-12-10 12:38 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @jbertran

* @chengyanjin

* @slaperche-scality

* @thomasdanan

* @lucieleonard

* @gdemonet

* @teddyandrieux

* @nootal

* @monpote

* @tcarmet

* @sayf-eddine-scality

* @cmonfort

* @nicolast

* @carlito-scality

* @alexandre-allard-scality





The following reviewers are expecting changes from the author, or must review again:

* @gdemonet

2020-12-14 09:27 UTC, gdemonet submitted a review, later dismissed

2020-12-14 09:27 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @jbertran

* @chengyanjin

* @slaperche-scality

* @thomasdanan

* @lucieleonard

* @gdemonet

* @teddyandrieux

* @nootal

* @monpote

* @tcarmet

* @sayf-eddine-scality

* @cmonfort

* @nicolast

* @carlito-scality

* @alexandre-allard-scality

2020-12-15 20:29 UTC, alexandre-allard-scality commented
/approve

2020-12-15 20:29 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @jbertran

* @chengyanjin

* @slaperche-scality

* @thomasdanan

* @lucieleonard

* @gdemonet

* @teddyandrieux

* @nootal

* @monpote

* @tcarmet

* @sayf-eddine-scality

* @cmonfort

* @nicolast

* @carlito-scality

* @alexandre-allard-scality










*The following options are set:* **approve**

2020-12-16 08:45 UTC, gdemonet approved these changes

2020-12-16 08:46 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/2.7`



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`
* `development/2.0`
* `development/2.1`
* `development/2.2`
* `development/2.3`
* `development/2.4`
* `development/2.5`
* `development/2.6`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2020-12-16 18:38 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/2.7`



The following branches have **NOT** changed:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`
* `development/2.0`
* `development/2.1`
* `development/2.2`
* `development/2.3`
* `development/2.4`
* `development/2.5`
* `development/2.6`



Please check the status of the associated issue None.

Goodbye alexandre-allard-scality.

2020-12-16 18:38 UTC, merged