Alerts without message annotation no detail in UI
scality/metalk8s pull request #3038
Opened 2021-01-14 13:48 UTC by ChengYanJin

originally from https://github.com/scality/metalk8s/pull/3030

> Component:
> 
> ui, tests
> 
> Context:
> #2994
> 
> Summary:
> Changes made to display alert message on UI when prometheus alerts annotation have any of description, summary or message field. Currently blank alert message shown for many of prometheus alerts in metalk8s UI.
>

2021-01-14 13:48 UTC, bert-e commented
# Hello chengyanjin,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/metalk8s/bert-e/doc/user).





*Status report is not available.*

2021-01-14 13:48 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `bugfix/alerts-without-message-annotation-no-detail-in-ui` into
`development/2.7`
* [w/2.8/bugfix/alerts-without-message-annotation-no-detail-in-ui](https://github.com/scality/metalk8s/compare/development/2.8...w/2.8/bugfix/alerts-without-message-annotation-no-detail-in-ui) will be merged into `development/2.8` 



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`
* `development/2.0`
* `development/2.1`
* `development/2.2`
* `development/2.3`
* `development/2.4`
* `development/2.5`
* `development/2.6`




You can set option `create_pull_requests` if you need me to create
**integration pull requests** in addition to integration branches, with:

```
@bert-e create_pull_requests
```

2021-01-14 13:49 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @jbertran

* @chengyanjin

* @slaperche-scality

* @thomasdanan

* @lucieleonard

* @gdemonet

* @teddyandrieux

* @nootal

* @monpote

* @tcarmet

* @sayf-eddine-scality

* @cmonfort

* @nicolast

* @carlito-scality

* @alexandre-allard-scality

2021-01-14 13:51 UTC, JBWatenbergScality approved these changes, later dismissed

2021-01-14 14:53 UTC, bert-e commented
# History mismatch



Merge commit #ed4844b80bfd1914a1b27ce7dfda3fb712033a4a on the integration branch
`w/2.8/bugfix/alerts-without-message-annotation-no-detail-in-ui` is merging a branch which is neither the current
branch `bugfix/alerts-without-message-annotation-no-detail-in-ui` nor the development branch
`development/2.8`.

It is likely due to a rebase of the branch `bugfix/alerts-without-message-annotation-no-detail-in-ui` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**

2021-01-14 16:42 UTC, ChengYanJin commented
/reset

2021-01-14 16:43 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.

2021-01-14 16:43 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `bugfix/alerts-without-message-annotation-no-detail-in-ui` into
`development/2.7`
* [w/2.8/bugfix/alerts-without-message-annotation-no-detail-in-ui](https://github.com/scality/metalk8s/compare/development/2.8...w/2.8/bugfix/alerts-without-message-annotation-no-detail-in-ui) will be merged into `development/2.8` 



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`
* `development/2.0`
* `development/2.1`
* `development/2.2`
* `development/2.3`
* `development/2.4`
* `development/2.5`
* `development/2.6`




You can set option `create_pull_requests` if you need me to create
**integration pull requests** in addition to integration branches, with:

```
@bert-e create_pull_requests
```

2021-01-14 16:43 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @jbertran

* @chengyanjin

* @slaperche-scality

* @thomasdanan

* @lucieleonard

* @gdemonet

* @teddyandrieux

* @nootal

* @monpote

* @tcarmet

* @sayf-eddine-scality

* @cmonfort

* @nicolast

* @carlito-scality

* @alexandre-allard-scality

2021-01-14 22:23 UTC, NicolasT commented
May want to have a

Closes: #2994 
Closes: #3030

in the description of this PR.

2021-01-15 08:04 UTC, gdemonet requested changes

2021-01-15 08:04 UTC, gdemonet commented on tests/post/steps/test_monitoring.py
> +                    rule['annotations'].get('description')
If we update this test, we should likely also update the tool which generates the list of alerts we're comparing with: https://github.com/scality/metalk8s/blob/development/2.7/tools/rule_extractor/rule_extractor.py#L127-L136

2021-01-15 08:04 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @jbertran

* @chengyanjin

* @slaperche-scality

* @thomasdanan

* @lucieleonard

* @gdemonet

* @teddyandrieux

* @nootal

* @monpote

* @tcarmet

* @sayf-eddine-scality

* @cmonfort

* @nicolast

* @carlito-scality

* @alexandre-allard-scality





The following reviewers are expecting changes from the author, or must review again:

* @gdemonet

2021-01-15 08:04 UTC, gdemonet commented on tests/post/steps/test_monitoring.py
> +                    rule['annotations'].get('description')
(and maybe re-run the tool)

2021-01-15 12:23 UTC, bert-e commented
# History mismatch



Merge commit #7805c96f550ca9071c434464cf9f7685c904f9e9 on the integration branch
`w/2.8/bugfix/alerts-without-message-annotation-no-detail-in-ui` is merging a branch which is neither the current
branch `bugfix/alerts-without-message-annotation-no-detail-in-ui` nor the development branch
`development/2.8`.

It is likely due to a rebase of the branch `bugfix/alerts-without-message-annotation-no-detail-in-ui` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**

2021-01-15 12:50 UTC, gdemonet commented
/reset

2021-01-15 12:50 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.

2021-01-15 12:50 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `bugfix/alerts-without-message-annotation-no-detail-in-ui` into
`development/2.7`
* [w/2.8/bugfix/alerts-without-message-annotation-no-detail-in-ui](https://github.com/scality/metalk8s/compare/development/2.8...w/2.8/bugfix/alerts-without-message-annotation-no-detail-in-ui) will be merged into `development/2.8` 



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`
* `development/2.0`
* `development/2.1`
* `development/2.2`
* `development/2.3`
* `development/2.4`
* `development/2.5`
* `development/2.6`




You can set option `create_pull_requests` if you need me to create
**integration pull requests** in addition to integration branches, with:

```
@bert-e create_pull_requests
```

2021-01-15 12:50 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @jbertran

* @chengyanjin

* @slaperche-scality

* @thomasdanan

* @lucieleonard

* @gdemonet

* @teddyandrieux

* @nootal

* @monpote

* @tcarmet

* @sayf-eddine-scality

* @cmonfort

* @nicolast

* @carlito-scality

* @alexandre-allard-scality





The following reviewers are expecting changes from the author, or must review again:

* @gdemonet

2021-01-15 12:51 UTC, gdemonet commented on tests/post/steps/test_monitoring.py
> +                    rule['annotations'].get('description')
Done

2021-01-15 12:51 UTC, gdemonet approved these changes

2021-01-15 12:52 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @jbertran

* @chengyanjin

* @slaperche-scality

* @thomasdanan

* @lucieleonard

* @gdemonet

* @teddyandrieux

* @nootal

* @monpote

* @tcarmet

* @sayf-eddine-scality

* @cmonfort

* @nicolast

* @carlito-scality

* @alexandre-allard-scality

2021-01-15 16:42 UTC, ChengYanJin commented
/approve

2021-01-15 16:51 UTC, bert-e commented
# Build failed



The build for [commit](https://github.com/scality/metalk8s/commit/2d69b7fb58635e0d7bb95e6dd7821175ec0046c3) did not succeed in branch bugfix/alerts-without-message-annotation-no-detail-in-ui.




*The following options are set:* **approve**

2021-01-16 18:18 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/2.7`

* :heavy_check_mark: `development/2.8`



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`
* `development/2.0`
* `development/2.1`
* `development/2.2`
* `development/2.3`
* `development/2.4`
* `development/2.5`
* `development/2.6`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2021-01-17 17:32 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/2.7`

* :heavy_check_mark: `development/2.8`



The following branches have **NOT** changed:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`
* `development/2.0`
* `development/2.1`
* `development/2.2`
* `development/2.3`
* `development/2.4`
* `development/2.5`
* `development/2.6`



Please check the status of the associated issue None.

Goodbye chengyanjin.

2021-01-17 17:32 UTC, merged