Enable persistent logs by default
scality/metalk8s pull request #305
Opened 2018-08-31 13:16 UTC by Zempashi

Fixes: #303

2018-08-31 13:16 UTC, bert-e commented
# Hello Zempashi,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get
information on this process.





*Status report is not available.*

2018-08-31 13:16 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `feature/enable_persistent_logs` into
`development/1.0`
* [w/1.1/feature/enable_persistent_logs](https://github.com/scality/metalk8s/compare/development/1.1...w/1.1/feature/enable_persistent_logs) will be merged into `development/1.1` (pull request #306)





*Follow* integration pull requests if you would like to be notified of
build statuses by email.

2018-08-31 13:16 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:



* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @ssalaues

* @NicolasT

* @thomasdanan

* @ballot-scality

* @anurag4DSB

* @Zempashi

* @alxf

2018-08-31 13:18 UTC, bert-e commented
# History mismatch



Merge commit #823d8cd2d400f8d036fcadfd94bc1043f4eb6fb0 on the integration branch
`w/1.1/feature/enable_persistent_logs` is merging a branch which is neither the current
branch `feature/enable_persistent_logs` nor the development branch
`development/1.1`.

It is likely due to a rebase of the branch `feature/enable_persistent_logs` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**

2018-08-31 13:20 UTC, ballot-scality submitted a review, later dismissed
LGTM

2018-08-31 13:37 UTC, NicolasT requested changes

2018-08-31 13:37 UTC, NicolasT commented on roles/prepare_os/tasks/persistent_logs.yml
> +    - "persistent_logs_dir_test.stat.isdir == False"
Consider
```
- not persistent_logs_dir_test.stat.isdir
- persistent_logs|bool
```

2018-08-31 13:37 UTC, NicolasT commented on roles/prepare_os/tasks/persistent_logs.yml
> +      MetalK8s will not act to fix this. Please move or remove directory
`act to fix` => `attempt to fix`
`remove directory` => `remove the directory`

2018-08-31 13:37 UTC, NicolasT commented on roles/prepare_os/tasks/persistent_logs.yml
> +      yourself.
`manually`

2018-08-31 13:37 UTC, NicolasT commented on roles/prepare_os/tasks/persistent_logs.yml
> +   - "persistent_logs_dir_test.stat.isdir == True"
Consider
```
- persistent_logs_dir_test.stat.isdir
- not (persistent_logs|bool)
```

2018-08-31 15:41 UTC, Zempashi commented
@bert-e reset

2018-08-31 15:41 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.

2018-08-31 15:41 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `feature/enable_persistent_logs` into
`development/1.0`
* [w/1.1/feature/enable_persistent_logs](https://github.com/scality/metalk8s/compare/development/1.1...w/1.1/feature/enable_persistent_logs) will be merged into `development/1.1` (pull request #307)





*Follow* integration pull requests if you would like to be notified of
build statuses by email.

2018-08-31 15:41 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:



* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @ssalaues

* @NicolasT

* @thomasdanan

* @ballot-scality

* @anurag4DSB

* @Zempashi

* @alxf

2018-09-03 09:08 UTC, ballot-scality approved these changes

2018-09-03 09:08 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/1.0`

* :heavy_check_mark: `development/1.1`




There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of Release Engineering will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of Release Engineering now.

2018-09-03 09:41 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/1.0`

* :heavy_check_mark: `development/1.1`




Please check the status of the associated issue None.

Goodbye Zempashi.

2018-09-03 09:41 UTC, merged