Introduce variables to control helm behaviour. New 'wait' option
scality/metalk8s pull request #309
Opened 2018-09-03 09:32 UTC by Zempashi

2018-09-03 09:32 UTC, bert-e commented
# Hello Zempashi,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get
information on this process.





*Status report is not available.*

2018-09-03 09:32 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:



* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @ssalaues

* @NicolasT

* @thomasdanan

* @ballot-scality

* @anurag4DSB

* @Zempashi

* @alxf

2018-09-05 09:47 UTC, NicolasT requested changes
This is a user-observable change, so needs a changelog entry.

2018-09-05 14:33 UTC, alxf approved these changes

2018-09-05 14:33 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/1.1`



The following branches will **NOT** be impacted:

* `development/1.0`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of Release Engineering will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of Release Engineering now.

2018-09-05 15:08 UTC, NicolasT approved these changes

2018-09-05 17:36 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/1.1`



The following branches have **NOT** changed:

* `development/1.0`



Please check the status of the associated issue None.

Goodbye Zempashi.

2018-09-05 17:36 UTC, merged