salt: Use csc framework for UI configuration
scality/metalk8s pull request #3181
Opened 2021-03-09 11:03 UTC by JBWatenbergScality

**Component**:

'salt'

**Context**: 

UI configuration can be patched in order to match a specific environment constraints. 
Before this PR any upgrade of metalk8s would revert those patches.

**Summary**:

Introducing CSC framework for ui configuration management allows deploying upgrade using a configmap merge approach in order to avoid losing config patches.   

**Work in progress**:

 ~~- [x] Add JSON support to CSC framework~~
 - [x] Use CSC framework similar to things that we achieved for other services (such as Dex) for metalk8s UI and shell-ui
 - [x] Add a section to document development guide mentioning the ability to configure menu options, role mapping and theme (https://metal-k8s.readthedocs.io/en/latest/developer/architecture/configurations.html#available-settings)
 - [x] Add a detailed section to operation documentation about how to customise menu options, role mapping and theme (https://metal-k8s.readthedocs.io/en/latest/operation/cluster_and_service_configuration.html)

**Acceptance criteria**: 

After an upgrade on a platform where UI configmap were patched, updated configmaps should preserved the overrides in place before the upgrade.

Closes: #3175

2021-03-09 13:08 UTC, gdemonet commented on salt/_modules/metalk8s_service_configuration.py
> +from typing import Literal
That's only available to Python 3.8, right? And buildchain is running with 3.6 in CI, no?

2021-03-12 09:22 UTC, JBWatenbergScality commented
@bert-e after_pull_request=3154

2021-03-15 17:08 UTC, gdemonet commented on salt/metalk8s/addons/ui/deployed/ui-configuration.sls
> +metalk8s-theme ConfigMap already exist:
```suggestion
metalk8s-shell-ui-config ConfigMap already exist:
```

:wink:

2021-03-15 18:27 UTC, bert-e commented
# Hello jbwatenbergscality,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/metalk8s/bert-e/doc/user).





*Status report is not available.*

2021-03-15 18:27 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @thomasdanan

* @alexandre-allard-scality

* @jbwatenbergscality

* @gdemonet

* @lucieleonard

* @chengyanjin

* @teddyandrieux

* @nicolast










*The following options are set:* **after_pull_request**

2021-03-17 14:36 UTC, gdemonet requested changes
Mostly docs changes, and renaming for `apiVersion` and `kind`.

2021-03-17 14:36 UTC, gdemonet commented on docs/developer/architecture/configurations.rst
> +- Changing the path on which the metalk8s ui is deployed
```suggestion
- Changing the path on which the MetalK8s UI is deployed
```

2021-03-17 14:36 UTC, gdemonet commented on docs/developer/architecture/configurations.rst
> +- Adapting UI theme to custom colors
```suggestion
- Customizing the UI theme
```

2021-03-17 14:36 UTC, gdemonet commented on docs/operation/cluster_and_service_configuration.rst
> +Metalk8s UI simplifies metalk8s cluster management and monitoring in a
```suggestion
MetalK8s UI simplifies management and monitoring of a MetalK8s cluster from a
```

2021-03-17 14:36 UTC, gdemonet commented on docs/operation/cluster_and_service_configuration.rst
> +The default configuration values for Metalk8s UI are specified below:
```suggestion
The default configuration values for MetalK8s UI are specified below:
```

2021-03-17 14:36 UTC, gdemonet commented on docs/operation/cluster_and_service_configuration.rst
> +Metalk8s allows to overrides theme color to enable customisation of the UI.
```suggestion
You can override theme colors used by MetalK8s UI.
```

2021-03-17 14:36 UTC, gdemonet commented on docs/operation/cluster_and_service_configuration.rst
> +The default theme for Metalk8s UI are specified below:
```suggestion
The default theme for MetalK8s UI are specified below:
```

2021-03-17 14:36 UTC, gdemonet commented on docs/operation/cluster_and_service_configuration.rst
> +
Since we start documenting configuration of the "Shell UI", it'd make sense to introduce it to the user with more context (what's its role/purpose, how is it deployed, ...). To do in another ticket/PR I guess (the need to re-configure MetalK8s for using another OIDC provider has already been raised by the community, see https://github.com/scality/metalk8s/discussions/3097).

2021-03-17 14:36 UTC, gdemonet commented on docs/operation/cluster_and_service_configuration.rst
> +It includes authentication through OIDC and menu items management.
```suggestion
MetalK8s Shell UI provides a common set of features to MetalK8s UI and
any other UI (both control and workload plane) configured to include the
Shell UI component(s).
Features exposed include:
- user authentication using an OIDC provider
- navigation menu items, displayed according to user groups (retrieved from OIDC)
```

2021-03-17 14:36 UTC, gdemonet commented on docs/operation/cluster_and_service_configuration.rst
> +Changing the path on which Metalk8s UI is served
```suggestion
Changing the MetalK8s UI Ingress Path
```

2021-03-17 14:36 UTC, gdemonet commented on docs/operation/cluster_and_service_configuration.rst
> +customise the path on which Metalk8s UI is deployed.
```suggestion
In order to expose another UI at the root path of the control plane,
in place of MetalK8s UI, you need to change the Ingress path from
which MetalK8s UI is served.
```

2021-03-17 14:36 UTC, gdemonet commented on salt/metalk8s/addons/ui/config/metalk8s-ui-config.yaml
> +apiVersion: addons.metalk8s.scality.com
I know other such ConfigMaps in our repo use this format, but an apiVersion should follow the `<domain>/<version>` format:

```suggestion
apiVersion: addons.metalk8s.scality.com/v1alpha1
```

2021-03-17 14:36 UTC, gdemonet commented on salt/metalk8s/addons/ui/config/metalk8s-ui-config.yaml
> +kind: Metalk8sUIConfig
```suggestion
kind: MetalK8sUIConfig
```

or even:

```suggestion
kind: UIConfig
```

2021-03-17 14:36 UTC, gdemonet commented on docs/operation/cluster_and_service_configuration.rst
> +ConfigMap must be edited as follows :
```suggestion
For example, to serve MetalK8s UI at **/platform** instead of **/**, follow
these steps:

#. Change the value of ``spec.basePath`` in the ConfigMap:
```

2021-03-17 14:36 UTC, gdemonet commented on docs/operation/cluster_and_service_configuration.rst
> +You would then need to apply your changes by running :
```suggestion
#. Apply your changes by running:
```

2021-03-17 14:36 UTC, gdemonet commented on docs/operation/cluster_and_service_configuration.rst
> +Metalk8s UI Theme Configuration Customization
```suggestion
MetalK8s UI Theme Customization
```

2021-03-17 14:36 UTC, gdemonet commented on docs/operation/cluster_and_service_configuration.rst
> +Once the theme edited, you would need to apply your changes by running :
```suggestion
Once the theme is edited, apply your changes by running:
```

2021-03-17 14:36 UTC, gdemonet commented on docs/operation/cluster_and_service_configuration.rst
> +Metalk8s Shell UI Configuration Customization
```suggestion
MetalK8s Shell UI Configuration Customization
```

(those titles... :vomiting_face: can't wait for #2739!)

2021-03-17 14:36 UTC, gdemonet commented on docs/operation/cluster_and_service_configuration.rst
> +                        metalk8s-shell-ui-config
Since we repeat this command in each section below, let's remove it from here:

```suggestion
``metalk8s-ui`` under the key ``data.config\.yaml``.
```

2021-03-17 14:36 UTC, gdemonet commented on docs/operation/cluster_and_service_configuration.rst
> +Changing UI OIDC configuration
```suggestion
Changing UI OIDC Configuration
```

2021-03-17 14:36 UTC, gdemonet commented on docs/operation/cluster_and_service_configuration.rst
> +UI configuration.
```suggestion
In order to adapt the OIDC configuration (e.g. the provider URL or the client ID)
used by the UI shareable navigation bar (called Shell UI), you need to modify
its ConfigMap.
```

2021-03-17 14:36 UTC, gdemonet commented on docs/operation/cluster_and_service_configuration.rst
> +metalk8s-ui by default you have to follow these steps:
```suggestion
For example, in order to replace the default client ID with "ui",
follow these steps:
```

2021-03-17 14:36 UTC, gdemonet commented on docs/operation/cluster_and_service_configuration.rst
> +#. Edit the configmap
```suggestion
#. Edit the ConfigMap:
```

2021-03-17 14:36 UTC, gdemonet commented on docs/operation/cluster_and_service_configuration.rst
> +#. Add the following entry
```suggestion
#. Add the following entry:
```

2021-03-17 14:36 UTC, gdemonet commented on docs/operation/cluster_and_service_configuration.rst
> +#. Apply your changes by running :
```suggestion
#. Apply your changes by running:
```

2021-03-17 14:36 UTC, gdemonet commented on docs/operation/cluster_and_service_configuration.rst
> +the OIDC provider url through the "providerUrl" attribute.
```suggestion
the OIDC provider URL through the "providerUrl" attribute.
```

2021-03-17 14:36 UTC, gdemonet commented on docs/operation/cluster_and_service_configuration.rst
> +Changing UI menu entries
```suggestion
Changing UI Menu Entries
```

2021-03-17 14:36 UTC, gdemonet commented on docs/operation/cluster_and_service_configuration.rst
> +You can edit UI menu entries by following these steps :
```suggestion
To change the UI navigation menu entries, follow these steps:
```

2021-03-17 14:36 UTC, gdemonet commented on docs/operation/cluster_and_service_configuration.rst
> +#. Edit the configmap
```suggestion
#. Edit the ConfigMap:
```

2021-03-17 14:36 UTC, gdemonet commented on docs/operation/cluster_and_service_configuration.rst
> +in the main menu pointing to scality website :
```suggestion
#. Edit the ``options`` field. As an example, we add an entry to
   the ``main`` section (there is also a ``subLogin`` section):
```

2021-03-17 14:36 UTC, gdemonet commented on docs/operation/cluster_and_service_configuration.rst
> +#. Apply your changes by running :
```suggestion
#. Apply your changes by running:
```

2021-03-17 14:36 UTC, gdemonet commented on salt/_modules/metalk8s_service_configuration.py
> +    format: SupportedFormats = SupportedFormats.YAML,
New arguments deserve an update to the function docstring :wink:

2021-03-17 14:36 UTC, gdemonet commented on salt/metalk8s/addons/ui/config/metalk8s-ui-config.yaml
> +  uiBasePath: /
Since we're describing the "UI configuration", I think `basePath` could be enough.

2021-03-17 14:36 UTC, gdemonet commented on salt/metalk8s/addons/ui/config/metalk8s-shell-ui-config.yaml.j2
> +kind: Metalk8sShellUIConfig
We're already in the `addons.metalk8s.scality.com` API group, so I think this is enough:

```suggestion
kind: ShellUIConfig
```

2021-03-17 14:36 UTC, gdemonet commented on salt/metalk8s/addons/ui/config/metalk8s-theme.yaml.in
> +kind: Metalk8sTheme
To be consistent:

```suggestion
kind: ThemeConfig
```

2021-03-17 14:36 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @thomasdanan

* @alexandre-allard-scality

* @jbwatenbergscality

* @gdemonet

* @lucieleonard

* @chengyanjin

* @teddyandrieux

* @nicolast





The following reviewers are expecting changes from the author, or must review again:

* @gdemonet







*The following options are set:* **after_pull_request**

2021-03-17 16:02 UTC, JBWatenbergScality commented on salt/_modules/metalk8s_service_configuration.py
> +    format: SupportedFormats = SupportedFormats.YAML,
In the end we don't need anymore to merge json baserd config map so I decided to drop the first commit

2021-03-17 16:17 UTC, JBWatenbergScality commented on docs/operation/cluster_and_service_configuration.rst
> +
I've opened #3207 to track this

2021-03-19 12:16 UTC, gdemonet requested changes
Some apiVersion/kind updates were not propagated

2021-03-19 12:16 UTC, gdemonet commented on salt/metalk8s/addons/ui/config/metalk8s-theme.yaml.in
> +apiVersion: addons.metalk8s.scality.com
```suggestion
apiVersion: addons.metalk8s.scality.com/v1alpha1
```

2021-03-19 12:16 UTC, gdemonet commented on salt/metalk8s/addons/ui/config/metalk8s-shell-ui-config.yaml.j2
> +apiVersion: addons.metalk8s.scality.com
```suggestion
apiVersion: addons.metalk8s.scality.com/v1alpha1
```

2021-03-19 12:16 UTC, gdemonet commented on salt/metalk8s/addons/ui/deployed/ui-configuration.sls
> +            apiVersion: addons.metalk8s.scality.com
```suggestion
            apiVersion: addons.metalk8s.scality.com/v1alpha1
```

2021-03-19 12:16 UTC, gdemonet commented on salt/metalk8s/addons/ui/deployed/ui-configuration.sls
> +            kind: Metalk8sUIConfig
```suggestion
            kind: UIConfig
```

2021-03-19 12:16 UTC, gdemonet commented on salt/metalk8s/addons/ui/deployed/ui-configuration.sls
> +            apiVersion: addons.metalk8s.scality.com
```suggestion
            apiVersion: addons.metalk8s.scality.com/v1alpha1
```

2021-03-19 12:16 UTC, gdemonet commented on salt/metalk8s/addons/ui/deployed/ui-configuration.sls
> +            kind: Metalk8sTheme
```suggestion
            kind: ThemeConfig
```

2021-03-19 12:16 UTC, gdemonet commented on salt/metalk8s/addons/ui/deployed/ui-configuration.sls
> +            apiVersion: addons.metalk8s.scality.com
```suggestion
            apiVersion: addons.metalk8s.scality.com/v1alpha1
```

2021-03-19 12:16 UTC, gdemonet commented on salt/metalk8s/addons/ui/deployed/ui-configuration.sls
> +            kind: Metalk8sShellUIConfig
```suggestion
            kind: ShellUIConfig
```

2021-03-19 12:16 UTC, gdemonet commented on docs/operation/cluster_and_service_configuration.rst
> +        kind: Metalk8sShellUIConfig
```suggestion
        kind: ShellUIConfig
```

2021-03-19 12:16 UTC, gdemonet commented on docs/operation/cluster_and_service_configuration.rst
> +        apiVersion: addons.metalk8s.scality.com
```suggestion
        apiVersion: addons.metalk8s.scality.com/v1alpha1
```

2021-03-19 12:16 UTC, gdemonet commented on docs/operation/cluster_and_service_configuration.rst
> +        kind: Metalk8sShellUIConfig
```suggestion
        kind: ShellUIConfig
```

2021-03-19 12:16 UTC, gdemonet commented on docs/operation/cluster_and_service_configuration.rst
> +        apiVersion: addons.metalk8s.scality.com
```suggestion
        apiVersion: addons.metalk8s.scality.com/v1alpha1
```

2021-03-19 12:16 UTC, gdemonet commented on docs/operation/cluster_and_service_configuration.rst
> +        kind: Metalk8sUIConfig
```suggestion
        kind: UIConfig
```

2021-03-19 12:16 UTC, gdemonet commented on docs/operation/cluster_and_service_configuration.rst
> +        apiVersion: addons.metalk8s.scality.com
```suggestion
        apiVersion: addons.metalk8s.scality.com/v1alpha1
```

2021-03-22 10:02 UTC, gdemonet approved these changes
Feel free to ignore if you have a green build, but if you don't and need to rebuild, please fix those headers :)

2021-03-22 10:02 UTC, gdemonet commented on docs/operation/cluster_and_service_configuration.rst
> +""""""""""""""""""""""""""""""""""""""""""""""""
It's not "critical" but still a bit ugly :stuck_out_tongue_winking_eye:

```suggestion
Changing the MetalK8s UI Ingress Path
"""""""""""""""""""""""""""""""""""""
```

2021-03-22 10:02 UTC, gdemonet commented on docs/operation/cluster_and_service_configuration.rst
> +~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```suggestion
MetalK8s UI Theme Customization
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

2021-03-22 10:02 UTC, gdemonet commented on docs/operation/cluster_and_service_configuration.rst
> +
Extra empty line, to remove

2021-03-22 10:02 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @thomasdanan

* @alexandre-allard-scality

* @jbwatenbergscality

* @gdemonet

* @lucieleonard

* @chengyanjin

* @teddyandrieux

* @nicolast










*The following options are set:* **after_pull_request**

2021-03-22 12:04 UTC, JBWatenbergScality commented
/approve

2021-03-22 12:04 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/2.9`



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`
* `development/2.0`
* `development/2.1`
* `development/2.2`
* `development/2.3`
* `development/2.4`
* `development/2.5`
* `development/2.6`
* `development/2.7`
* `development/2.8`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve, after_pull_request**

2021-03-22 12:14 UTC, JBWatenbergScality commented on docs/operation/cluster_and_service_configuration.rst
> +""""""""""""""""""""""""""""""""""""""""""""""""
I took care of it in https://github.com/scality/metalk8s/pull/3196

2021-03-22 13:51 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/2.9`



The following branches have **NOT** changed:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`
* `development/2.0`
* `development/2.1`
* `development/2.2`
* `development/2.3`
* `development/2.4`
* `development/2.5`
* `development/2.6`
* `development/2.7`
* `development/2.8`



Please check the status of the associated issue None.

Goodbye jbwatenbergscality.

2021-03-22 13:51 UTC, merged