Update Button to ButtonV2
scality/metalk8s pull request #3462
Opened 2021-07-23 15:33 UTC by theocerutti

2021-07-23 15:33 UTC, bert-e commented
# Hello theocerutti,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/metalk8s/bert-e/doc/user).





*Status report is not available.*

2021-07-23 15:33 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @nicolast

* @teddyandrieux

* @alexandre-allard-scality

* @jbwatenbergscality

* @lucieleonard

* @chengyanjin

* @gdemonet

* @thomasdanan

2021-07-26 13:19 UTC, ChengYanJin requested changes
I have a few small comments, thanks for taking care of them.

2021-07-26 13:19 UTC, ChengYanJin commented on ui/package.json
> +    "@scality/core-ui": "github:scality/core-ui.git#v0.19.3",
Please bump the core-ui version in Shell UI as well, because it is required to use the same version.

2021-07-26 13:19 UTC, ChengYanJin commented on ui/src/components/VolumeMetricsTab.js
> +              size="large"
same as the next comment.

2021-07-26 13:19 UTC, ChengYanJin commented on ui/src/containers/NodePageMetricsTab.js
> +          size="large"
It's not related to this PR.
I understand here you want to make sure the button and the dropdown have the same size.
IMO, the issue will be handled by select/dropdown component, anyways, manually set the size of the dropdown won't solve the issue for all the screens. 
hence I suggest we remove it.

2021-07-26 13:19 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @nicolast

* @teddyandrieux

* @alexandre-allard-scality

* @jbwatenbergscality

* @lucieleonard

* @chengyanjin

* @gdemonet

* @thomasdanan





The following reviewers are expecting changes from the author, or must review again:

* @chengyanjin

2021-07-26 13:29 UTC, ChengYanJin commented on ui/src/components/VolumeOverviewTab.js
>          <DeleteButton
we should remove the style for `DeleteButton`.

2021-08-04 06:16 UTC, ChengYanJin approved these changes, later dismissed

2021-08-04 06:16 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @nicolast

* @teddyandrieux

* @alexandre-allard-scality

* @jbwatenbergscality

* @lucieleonard

* @chengyanjin

* @gdemonet

* @thomasdanan

2021-08-04 07:22 UTC, ChengYanJin approved these changes
LGTM!

2021-08-04 07:28 UTC, theocerutti commented
@bert-e approve

2021-08-04 08:34 UTC, bert-e commented
# Build failed



The build for [commit](https://github.com/scality/metalk8s/commit/9ae6c7d3edca9e5158df6b2095a06035ed00a280) did not succeed in branch improvement/replace-button-v2.




*The following options are set:* **approve**

2021-08-04 15:27 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/2.11`



The following branches will **NOT** be impacted:

* `development/2.0`
* `development/2.1`
* `development/2.10`
* `development/2.2`
* `development/2.3`
* `development/2.4`
* `development/2.5`
* `development/2.6`
* `development/2.7`
* `development/2.8`
* `development/2.9`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2021-08-04 17:28 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/2.11`



The following branches have **NOT** changed:

* `development/2.0`
* `development/2.1`
* `development/2.10`
* `development/2.2`
* `development/2.3`
* `development/2.4`
* `development/2.5`
* `development/2.6`
* `development/2.7`
* `development/2.8`
* `development/2.9`



Please check the status of the associated issue None.

Goodbye theocerutti.

2021-08-04 17:28 UTC, merged