charts,salt,build: Bump NGINX Ingress chart to v4.0.1
scality/metalk8s pull request #3518
Opened 2021-09-01 15:15 UTC by TeddyAndrieux

In order to support the newer Kubernetes version 1.22 we need to bump
the version of NGINX Ingress.

2021-09-01 15:15 UTC, bert-e commented
# Hello teddyandrieux,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/metalk8s/bert-e/doc/user).





*Status report is not available.*

2021-09-01 15:15 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @lucieleonard

* @teddyandrieux

* @thomasdanan

* @nicolast

* @chengyanjin

* @jbwatenbergscality

* @gdemonet

* @alexandre-allard-scality

2021-09-02 15:34 UTC, gdemonet requested changes, later dismissed

2021-09-02 15:34 UTC, gdemonet commented on CHANGELOG.md
> +  nginx-ingress-controller image has been bump accordingly to v1.0.0
```suggestion
  nginx-ingress-controller image has been bumped accordingly to v1.0.0
```

2021-09-02 15:34 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @lucieleonard

* @teddyandrieux

* @thomasdanan

* @nicolast

* @chengyanjin

* @jbwatenbergscality

* @gdemonet

* @alexandre-allard-scality





The following reviewers are expecting changes from the author, or must review again:

* @gdemonet

2021-09-03 06:45 UTC, TeddyAndrieux commented
/approve

2021-09-03 06:45 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @lucieleonard

* @teddyandrieux

* @thomasdanan

* @nicolast

* @chengyanjin

* @jbwatenbergscality

* @gdemonet

* @alexandre-allard-scality





The following reviewers are expecting changes from the author, or must review again:

* @gdemonet







*The following options are set:* **approve**

2021-09-03 07:18 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @lucieleonard

* @teddyandrieux

* @thomasdanan

* @nicolast

* @chengyanjin

* @jbwatenbergscality

* @gdemonet

* @alexandre-allard-scality










*The following options are set:* **approve**

2021-09-03 07:31 UTC, sayf-eddine-scality approved these changes

2021-09-03 07:31 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/2.11`



The following branches will **NOT** be impacted:

* `development/2.0`
* `development/2.1`
* `development/2.10`
* `development/2.2`
* `development/2.3`
* `development/2.4`
* `development/2.5`
* `development/2.6`
* `development/2.7`
* `development/2.8`
* `development/2.9`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2021-09-03 07:31 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/2.11`



The following branches have **NOT** changed:

* `development/2.0`
* `development/2.1`
* `development/2.10`
* `development/2.2`
* `development/2.3`
* `development/2.4`
* `development/2.5`
* `development/2.6`
* `development/2.7`
* `development/2.8`
* `development/2.9`



Please check the status of the associated issue None.

Goodbye teddyandrieux.

2021-09-03 07:31 UTC, merged