Bugfix/UI configuration missing loki endpoint and alert grouping missing discovery labels
scality/metalk8s pull request #3559
Opened 2021-10-07 12:31 UTC by JBWatenbergScality

**Component**:

salt, alert-group

2021-10-07 12:32 UTC, bert-e commented
# Hello jbwatenbergscality,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/metalk8s/bert-e/doc/user).





*Status report is not available.*

2021-10-07 12:32 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @alexandre-allard-scality

* @thomasdanan

* @gdemonet

* @chengyanjin

* @nicolast

* @jbwatenbergscality

* @teddyandrieux

* @lucieleonard

2021-10-07 12:45 UTC, gdemonet requested changes

2021-10-07 12:45 UTC, gdemonet commented on tools/lib-alert-tree/lib_alert_tree/cli.py
> +def generate_cli(roots, prometheus_rule_labels={"metalk8s.scality.com/monitor": ""}):
Let's not make this part of the lib, but rather part of the `metalk8s` module.

Here, simply use (`None` is already the default value for `PrometheusRule.labels`):

```python
def generate_cli(roots, prometheus_rule_labels=None):
```

And in `tools/lib-alert-tree/metalk8s/__main__.py`:

```python
main = generate_cli(
    roots={"cluster-degraded": CLUSTER_WARNING, "cluster-at-risk": CLUSTER_CRITICAL},
    prometheus_rule_labels={"metalk8s.scality.com/monitor": ""},
)
```

2021-10-07 12:45 UTC, gdemonet commented on tools/lib-alert-tree/tests/test_cli.py
> +        == textwrap.dedent(
Only the `metadata.labels` section changes, would be sufficient to check:

```python
output_lines = output.splitlines()
meta_lineno = output_lines.index("metadata:")
assert output_lines[meta_lineno:meta_line + 4] == [
    "metadata:",
    "  labels:",
    "    hello: world",
    "  name: test.rules",  # Just checking that we don't have other labels after ours
]
```

2021-10-07 12:45 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @alexandre-allard-scality

* @thomasdanan

* @gdemonet

* @chengyanjin

* @nicolast

* @jbwatenbergscality

* @teddyandrieux

* @lucieleonard





The following reviewers are expecting changes from the author, or must review again:

* @gdemonet

2021-10-07 12:52 UTC, gdemonet commented
Oh, and can you also add a mention about this in the docs? `docs/developer/tools/lib-alert-tree/examples/example.py` (and corresponding labels in `example_rule.yaml`)

2021-10-07 12:57 UTC, JBWatenbergScality commented
> Oh, and can you also add a mention about this in the docs? `docs/developer/tools/lib-alert-tree/examples/example.py` (and corresponding labels in `example_rule.yaml`)

Done 👍

2021-10-07 13:02 UTC, gdemonet submitted a review, later dismissed

2021-10-07 13:02 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @alexandre-allard-scality

* @thomasdanan

* @gdemonet

* @chengyanjin

* @nicolast

* @jbwatenbergscality

* @teddyandrieux

* @lucieleonard

2021-10-13 08:18 UTC, JBWatenbergScality commented
/approve

2021-10-13 14:05 UTC, gdemonet approved these changes

2021-10-13 14:05 UTC, gdemonet commented on tools/rule_extractor/alerting_rules.json
> +    "name": "ClusterAtRisk",
Good catch! I'm surprised this didn't cause test failures in my PR :confused: 

---

_Edit: OK, they weren't selected by our prometheus-operator since we didn't set the right label :facepalm:_

2021-10-13 14:06 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/2.11`



The following branches will **NOT** be impacted:

* `development/2.0`
* `development/2.1`
* `development/2.10`
* `development/2.2`
* `development/2.3`
* `development/2.4`
* `development/2.5`
* `development/2.6`
* `development/2.7`
* `development/2.8`
* `development/2.9`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2021-10-14 07:57 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/2.11`



The following branches have **NOT** changed:

* `development/2.0`
* `development/2.1`
* `development/2.10`
* `development/2.2`
* `development/2.3`
* `development/2.4`
* `development/2.5`
* `development/2.6`
* `development/2.7`
* `development/2.8`
* `development/2.9`



Please check the status of the associated issue None.

Goodbye jbwatenbergscality.

2021-10-14 07:57 UTC, merged