fix(CircleStatus): Fix rendering issue for CircleStatus
scality/metalk8s pull request #3576
Opened 2021-10-25 11:59 UTC by hug33k

This PR fixes rendering issue for CircleStatus by avoiding non-necessary re-renders

**Component**:

`CircleStatus`, `StatusIcon`

**Context**: 

When `Icons` from Core-UI are implemented into `CircleStatus` component, they may re-render periodically even when an update was not required (e.g.: Status not changing).

**Summary**:

By adding a prop update verification into `CircleStatus`, component will now only re-render when status is changing, in order to avoid non-necessary re-renders.

Also, `StatusIcon` component is now in a dedicated file since it is now no longer used by `CircleStatus`.

**Acceptance criteria**: 

Health icons in Core-UI ([See related PR](https://github.com/scality/core-ui/pull/378)) should be merged and available first, in order to have access to the icons used by `CircleStatus`.

---

See: ARTESCA-2152

2021-10-26 11:20 UTC, JBWatenbergScality requested changes

2021-10-26 11:20 UTC, JBWatenbergScality commented on ui/src/components/CircleStatus.js
> +
Couldn't we just refactor this to a function component and check if we still have the refresh issue ? If so I think we can play with the component key instead of hacking around with the shouldComponentUpdate lifecycle.

2021-10-26 11:20 UTC, JBWatenbergScality commented on ui/src/components/StatusIcon.js
> +    console.log(theme);
```suggestion
```

2021-10-27 11:10 UTC, hug33k commented
@JBWatenbergScality I updated support for `aria-label` in `CircleStatus` and also tests related to that prop

2021-10-27 16:12 UTC, ChengYanJin commented
hello @hug33k,
The name of the branch is not valid..
You'll have to name it `bugfix/circle-status-rendering-issue` and create another pull request.

2021-10-28 08:05 UTC, closed without merging