backport pep8 fixes specific for new validate_storage.py
scality/metalk8s pull request #360
Opened 2018-09-12 20:20 UTC by Zempashi

2018-09-12 20:20 UTC, bert-e commented
# Hello Zempashi,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get
information on this process.





*Status report is not available.*

2018-09-12 20:20 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `bugfix/pep8_fix_1.0` into
`development/1.0`
* [w/1.1/bugfix/pep8_fix_1.0](https://github.com/scality/metalk8s/compare/development/1.1...w/1.1/bugfix/pep8_fix_1.0) will be merged into `development/1.1` (pull request #361)





*Follow* integration pull requests if you would like to be notified of
build statuses by email.

2018-09-12 20:20 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:



* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @Zempashi

* @NicolasT

* @ssalaues

* @thomasdanan

* @anurag4DSB

* @ballot-scality

* @alxf

2018-09-12 20:25 UTC, NicolasT requested changes

2018-09-12 20:25 UTC, NicolasT commented on roles/setup_lvm_vg/action_plugins/validate_storage.py
> +    Check that the devices specified in metalk8S_lvm_drives_<vg name>
This shouldn't have a capital `S`.

2018-09-12 20:25 UTC, NicolasT commented on roles/setup_lvm_vg/action_plugins/validate_storage.py
> +    '''Check presence and usage of any disk defined in metalk8S_lvm_drives_*
This shouldn't have a capital `S`.

2018-09-13 09:16 UTC, Zempashi commented
change done directly in #347

2018-09-13 09:16 UTC, closed without merging