Add file to help debug etcd
scality/metalk8s pull request #420
Opened 2018-10-03 15:13 UTC by Zempashi

I create the file only if I detect etcd files. The other possibility is to add the file no matter what. but only doing export PATH=$(PATH):/usr/local/bin => it seems a bit overkill to create the file just for that

2018-10-03 15:13 UTC, bert-e commented
# Hello Zempashi,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get
information on this process.





*Status report is not available.*

2018-10-03 15:13 UTC, bert-e commented
# Branches have diverged



This pull request's source branch `feature/debugging_helper_sourceable_file` has diverged from
`development/1.1` by more than 50 commits.

To avoid any integration risks, please re-synchronize them using one of the
following solutions:

* Merge `origin/development/1.1` into `feature/debugging_helper_sourceable_file`
* Rebase `feature/debugging_helper_sourceable_file` onto `origin/development/1.1`

Note: If you choose to rebase, you may have to ask me to rebuild
integration branches using the `reset` command.

2018-10-03 15:33 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:



* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @ssalaues

* @alxf

* @ballot-scality

* @Zempashi

* @NicolasT

* @anurag4DSB

* @thomasdanan

2018-10-04 09:24 UTC, NicolasT commented on playbooks/kubespray-post.yml
> +- hosts: etcd:k8s-cluster
`etcd:kube-master` should be sufficient, no?

2018-10-04 09:24 UTC, NicolasT commented on roles/debug_env_file/tasks/main.yml
> +- name: 'test if etcd are present'
'etcd client certificates'?

2018-10-04 09:25 UTC, NicolasT commented on roles/debug_env_file/templates/metalk8s.env.sh.j2
> +export PATH=$PATH:/usr/local/bin
FWIW, strictly speaking this is not POXIX sh compatible, should be

```
PATH=$PATH:/usr/local/bin; export PATH
```
etc

2018-10-04 09:26 UTC, NicolasT commented on roles/debug_env_file/templates/metalk8s.env.sh.j2
> +export ETCDCTL_ENDPOINTS='https://127.0.0.1:2379'
This will only work on nodes in the `etcd` group, not in the `kube-master` (or `k8s-cluster`, see comment above) group.

2018-10-04 09:27 UTC, NicolasT commented
May want to add a blurb in some documentation for this, otherwise people won't know this feature exists nor how to use it.

Where do you think this should go @lucieleonard ?

2018-10-04 11:16 UTC, Zempashi commented on playbooks/kubespray-post.yml
> +- hosts: etcd:k8s-cluster
Indeed, calicoctl seem not requiring any configuration (except /usr/local/bin in the PATH)

2018-10-04 11:18 UTC, Zempashi commented on playbooks/kubespray-post.yml
> +- hosts: etcd:k8s-cluster
If etcd is the only target, we can also remove the test and target etcd.

2018-10-04 12:22 UTC, NicolasT commented on playbooks/kubespray-post.yml
> +- hosts: etcd:k8s-cluster
Nah, I think one may want to query etcd from a kube-master node. My point was mainly that on kube-node nodes, there are no etcd client certificates present so no use in running the role on those.

2018-10-11 12:40 UTC, ballot-scality submitted a review, later dismissed
LGTM

2018-10-11 21:39 UTC, NicolasT commented
> May want to add a blurb in some documentation for this, otherwise people won't know this feature exists nor how to use it.

2018-10-11 21:40 UTC, NicolasT requested changes
May want to add a blurb in some documentation for this, otherwise people won't know this feature exists nor how to use it.

2018-10-12 09:44 UTC, bert-e commented
# Build failed



The build for [commit](https://github.com/scality/metalk8s/commit/cfac0bd02c2edef5dd04109216dd9723f2b978ab) did not succeed in branch feature/debugging_helper_sourceable_file.

2018-10-12 13:07 UTC, NicolasT commented
@bert-e wait

2018-10-12 13:07 UTC, NicolasT commented
I'm on the documentation topic.

2018-10-12 13:49 UTC, NicolasT commented
Changing the path. Would like to have @lucieleonard go over the docs changes once done.

2018-10-12 13:55 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:



* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @alxf

* @thomasdanan

* @ssalaues

* @lucieleonard

* @ballot-scality

* @Zempashi

* @NicolasT

* @anurag4DSB

2018-10-12 13:55 UTC, NicolasT commented
@bert-e help

2018-10-12 13:55 UTC, bert-e commented
# Help page



The following options and commands are available at this time.

## Options ##


name   | description  | privileged
------ | ------------ | ------------
:arrow_right: **bypass_leader_approval** | Bypass the pull request leaders' approval |  :star: 
:arrow_right: **no_octopus** | Prevent Wall-E from doing any octopus merge and use multiple consecutive merge instead | 
:arrow_right: **bypass_build_status** | Bypass the build and test status |  :star: 
:arrow_right: **bypass_peer_approval** | Bypass the pull request peers' approval |  :star: 
:arrow_right: **bypass_author_approval** | Bypass the pull request author's approval |  :star: 
:arrow_right: **create_pull_requests** | Allow the creation of integration pull requests. | 
:arrow_right: **wait** | Instruct Bert-E not to run until further notice. | 
:arrow_right: **bypass_jira_check** | Bypass the Jira issue check |  :star: 
:arrow_right: **bypass_commit_size** | Bypass the check on the size of the changeset ```TBA``` |  :star: 
:arrow_right: **bypass_incompatible_branch** | Bypass the check on the source branch prefix |  :star: 
:arrow_right: **unanimity** | Change review acceptance criteria from `one reviewer at least` to `all reviewers` | 
:arrow_right: **after_pull_request** | Wait for the given pull request id to be merged before continuing with the current one. | 



## Commands ##


name   | description  | privileged
------ | ------------ | ------------
:arrow_right: **clear** | Remove all comments from Bert-E from the history ```TBA``` | 
:arrow_right: **build** | Re-start a fresh build ```TBA``` | 
:arrow_right: **help** | Print Bert-E's manual in the pull request. | 
:arrow_right: **retry** | Re-start a fresh build ```TBA``` | 
:arrow_right: **reset** | Try to remove integration branches unless there are commits on them which do not appear on the source branch. | 
:arrow_right: **force_reset** | Delete integration branches & pull requests, and restart merge process from the beginning. | 
:arrow_right: **status** | Print Bert-E's current status in the pull request ```TBA``` |

2018-10-12 13:55 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:



* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @alxf

* @thomasdanan

* @ssalaues

* @lucieleonard

* @ballot-scality

* @Zempashi

* @NicolasT

* @anurag4DSB

2018-10-12 14:26 UTC, lucieleonard commented on docs/operations-guide/managing-etcd.rst
> +:program:`etcd` cluster.
For more information about :command:`etcdctl` and how to interact with an :program:`etcd` cluster, refer to <https://github.com/etcd-io/etcd/blob/master/Documentation/dev-guide/interacting_v3.md>`_

2018-10-15 09:01 UTC, NicolasT commented on docs/operations-guide/managing-etcd.rst
> +:program:`etcd` cluster.
Do we really want to show long URLs as text in the docs? :thinking:

2018-10-15 09:20 UTC, lucieleonard commented on docs/operations-guide/managing-etcd.rst
> +:program:`etcd` cluster.
No sure.
"... refer to etcd-io's documentation" with the link :-)

2018-10-15 13:04 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:



* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @alxf

* @thomasdanan

* @NicolasT

* @ssalaues

* @anurag4DSB

* @Zempashi

* @lucieleonard

* @ballot-scality

2018-10-15 13:13 UTC, NicolasT submitted a review, later dismissed

2018-10-19 11:45 UTC, bert-e commented
# Build failed



The build for [commit](https://github.com/scality/metalk8s/commit/4be40b67d3a85b2236429d0021a9db6c5a258624) did not succeed in branch feature/debugging_helper_sourceable_file.

2018-11-26 14:13 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `feature/debugging_helper_sourceable_file` into
`development/1.1`
* [w/1.2/feature/debugging_helper_sourceable_file](https://github.com/scality/metalk8s/compare/development/1.2...w/1.2/feature/debugging_helper_sourceable_file) will be merged into `development/1.2` (pull request #502)



The following branches will **NOT** be impacted:

* `development/1.0`




*Follow* integration pull requests if you would like to be notified of
build statuses by email.

2018-11-26 14:13 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @thomasdanan

* @anurag4dsb

* @nicolast

* @ssalaues

* @ballot-scality

* @zempashi

* @lucieleonard

2018-11-30 09:11 UTC, bert-e commented
# History mismatch



Merge commit #c2148d670f8b331f3152ea499eb3d562594a56a1 on the integration branch
`w/1.2/feature/debugging_helper_sourceable_file` is merging a branch which is neither the current
branch `feature/debugging_helper_sourceable_file` nor the development branch
`development/1.2`.

It is likely due to a rebase of the branch `feature/debugging_helper_sourceable_file` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**

2018-11-30 09:12 UTC, Zempashi commented
@bert-e reset

2018-11-30 09:12 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.

2018-11-30 09:12 UTC, bert-e commented
# Conflict




There is a conflict between your branch `feature/debugging_helper_sourceable_file` and the
destination branch `development/1.1`.

Please resolve the conflict on **the feature branch** (`feature/debugging_helper_sourceable_file`).

```bash
 $ git fetch
 $ git checkout origin/feature/debugging_helper_sourceable_file
 $ git merge origin/development/1.1
 $ # <intense conflict resolution>
 $ git commit
 $ git push origin HEAD:feature/debugging_helper_sourceable_file
```

2019-12-17 22:19 UTC, closed without merging