Deploy etcd exporter
scality/metalk8s pull request #80
Opened 2018-06-20 14:26 UTC by Zempashi

2018-06-20 14:47 UTC, NicolasT commented on roles/etcd_prometheus_exporter_cert/tasks/gen_cert.yml
> +- name: 'create tempfile to get certificates'
A bit odd to use a tempfile here, but use a different method in the step above?

2018-06-20 14:48 UTC, NicolasT commented on roles/etcd_prometheus_exporter_cert/tasks/gen_cert.yml
> +  register: etcd_exporter_cert_temp
This is not used? Is the step necessary?

2018-06-20 14:50 UTC, NicolasT commented on roles/etcd_prometheus_exporter_cert/tasks/gen_cert.yml
> +    content: '{{ gen_etcd_exporter_csr.stdout }}'
`gen_etcd_exporter_cert`, no?

2018-06-22 13:57 UTC, NicolasT requested changes
Some spelling cleanups, some questions.

2018-06-22 13:57 UTC, NicolasT commented on roles/etcd_prometheus_exporter_cert/defaults/main.yml
> +etcd_exporter_key: '{{ etcd_cert_dir }}/etcd-exporter-key.pem'
`etcd_cert_dir` is set in another role. Is that best practice in Ansible?

2018-06-22 13:57 UTC, NicolasT commented on roles/etcd_prometheus_exporter_cert/tasks/gen_cert.yml
> +    creates: '{{ etcd_exporter_key }}'
Does this result in this being done only once? We don't want to re-generate the cert on every invocation of the playbook, right?

2018-06-22 13:57 UTC, NicolasT commented on roles/etcd_prometheus_exporter_cert/tasks/gen_cert.yml
> +  register: csr_on_etd_node
`etcd` instead of `etd`?

2018-06-22 13:57 UTC, NicolasT commented on roles/etcd_prometheus_exporter_cert/tasks/gen_cert.yml
> +  delegate_to: '{{ groups.etcd|first }}'
... and hope it's still the same... Sometimes I'm wondering whether certs shouldn't be all generated on e.g. the host from which Ansible runs, then copy them over wherever they're required. But that goes back to the whole cert handling discussion :)

2018-06-22 13:57 UTC, NicolasT commented on roles/etcd_prometheus_exporter_cert/tasks/gen_cert.yml
> +    dest: '{{ etcd_exporter_cert }}'
I'm confused. This generates `{{ etcd_exporter_cert }}`, and so does `copy cert on master node` below as well?

2018-06-22 13:57 UTC, NicolasT commented on roles/etcd_prometheus_exporter_cert/tasks/gen_cert.yml
> +    content: '{{ etcd_exporter_cert_content.content|b64decode }}'
Why `b64encode`? I know this is required when putting the cert etc. in a YAML manifest when creating the `Secret`, but why encode in a PEM-file which one doesn't expect to be encoded in any way? This makes it more difficult to use the cert with `curl` or similar to troubleshoot things.

2018-06-22 13:57 UTC, NicolasT commented on roles/etcd_prometheus_exporter_cert/tasks/main.yml
> +- name: 'create tempfile for etcd-exporteer auth secret'
`exporter`

2018-06-22 13:57 UTC, NicolasT commented on roles/etcd_prometheus_exporter_cert/tasks/main.yml
> +    dest: '{{ kube_etcd_exporter_auth.path|default("<check_mode_tempfile>") }}'
What does this line do, exactly?

2018-06-22 13:57 UTC, NicolasT commented on roles/etcd_prometheus_exporter_cert/tasks/main.yml
> +    filename: '{{ kube_etcd_exporter_auth.path|default }}'
This is not exactly the same as how the path is constructed above, which seems fishy?

2018-06-22 13:57 UTC, NicolasT commented on roles/etcd_prometheus_exporter_cert/tasks/main.yml
> +- name: 'remove uneeded tempfile'
`unneeded`

2018-06-22 13:57 UTC, NicolasT commented on roles/etcd_prometheus_exporter_cert/tasks/main.yml
> +- name: 'export sosme vars for later roles'
`some`

2018-06-22 13:57 UTC, NicolasT commented on roles/etcd_prometheus_exporter_cert/templates/etcd_exporter_secret.yml.j2
> +  tls.crt: '{{ etcd_exporter_cert_content.content }}'
These should be base64 encoded, right?

2018-06-22 13:57 UTC, NicolasT commented on roles/etcd_prometheus_exporter_cert/templates/etcd_exporter_secret.yml.j2
> +  namespace: '{{ kube_prometheus_namespace }}'
No need to put a `namespace`, we pass it to `kubectl` above.

2018-06-26 12:09 UTC, Zempashi commented on roles/etcd_prometheus_exporter_cert/tasks/gen_cert.yml
> +    content: '{{ gen_etcd_exporter_csr.stdout }}'
oh right

2018-06-26 12:09 UTC, Zempashi commented on roles/etcd_prometheus_exporter_cert/defaults/main.yml
> +etcd_exporter_key: '{{ etcd_cert_dir }}/etcd-exporter-key.pem'
I forget to move it from kube_prometheus (which is run is the same play). The real info is in kubespray role but this one install etcd (which I don't want do to here). So I duplicate the info

2018-06-26 12:09 UTC, Zempashi commented on roles/etcd_prometheus_exporter_cert/tasks/gen_cert.yml
> +    creates: '{{ etcd_exporter_key }}'
Yes, the `creates` tell that the command should create the file, and should not be run if the file is already here.

2018-06-26 12:09 UTC, Zempashi commented on roles/etcd_prometheus_exporter_cert/tasks/gen_cert.yml
> +  register: csr_on_etd_node
I will remove this debug and the register (thinking twice, it's not interesting anymore)

2018-06-26 12:09 UTC, Zempashi commented on roles/etcd_prometheus_exporter_cert/tasks/gen_cert.yml
> +  delegate_to: '{{ groups.etcd|first }}'
Yes groups are ordered server (so it's safe). For generating everything locally, why not (but don't see many playbooks that do it this way)

2018-06-26 12:09 UTC, Zempashi commented on roles/etcd_prometheus_exporter_cert/tasks/gen_cert.yml
> +    dest: '{{ etcd_exporter_cert }}'
Indeed ...(what's wrong with me ?)

2018-06-26 12:09 UTC, Zempashi commented on roles/etcd_prometheus_exporter_cert/tasks/gen_cert.yml
> +    content: '{{ etcd_exporter_cert_content.content|b64decode }}'
https://docs.ansible.com/ansible/2.4/slurp_module.html store result in base64 in ansible var

2018-06-26 12:09 UTC, Zempashi commented on roles/etcd_prometheus_exporter_cert/tasks/main.yml
> +    dest: '{{ kube_etcd_exporter_auth.path|default("<check_mode_tempfile>") }}'
in checkmode ansible will not execute tempfile, so the path argument will not exist and then result into an exception for the template task. I add a default so that template can execute normaly.

2018-06-26 12:09 UTC, Zempashi commented on roles/etcd_prometheus_exporter_cert/tasks/main.yml
> +    filename: '{{ kube_etcd_exporter_auth.path|default }}'
but filename is not a mandatory argument for kube module so None is ok.

2018-06-26 12:09 UTC, Zempashi commented on roles/etcd_prometheus_exporter_cert/templates/etcd_exporter_secret.yml.j2
> +  tls.crt: '{{ etcd_exporter_cert_content.content }}'
It is already already (see comment above about `slurp`)

2018-06-26 12:10 UTC, Zempashi commented
rah I'm not used to "commiting the comment transaction" of github. Sorry for  the delay

2018-06-26 12:22 UTC, NicolasT commented on roles/etcd_prometheus_exporter_cert/tasks/gen_cert.yml
> +    dest: '/tmp/ansible.{{ lookup("password", "/dev/null chars=ascii_letters length=8") }}'
This file seems not to be deleted.

2018-06-27 11:24 UTC, Zempashi commented on roles/etcd_prometheus_exporter_cert/tasks/gen_cert.yml
> +    dest: '/tmp/ansible.{{ lookup("password", "/dev/null chars=ascii_letters length=8") }}'
done

2018-06-27 12:23 UTC, NicolasT commented
You'll need to merge `development/0.1` in your branch because of the CI changes.

2018-06-27 12:24 UTC, NicolasT commented on roles/etcd_prometheus_exporter_cert/tasks/gen_cert.yml
> +    gen_etcd_exporter_key is changed or not etcd_exporter_cert_file.stat.exists
This could, at some point in time, become an issue when the cert expires, I guess :)

2018-06-27 12:33 UTC, NicolasT submitted a review, later dismissed

2018-06-28 11:59 UTC, NicolasT approved these changes

2018-06-28 14:22 UTC, merged