Remove command from SALT_MASTER_CALL 'macro'
scality/metalk8s pull request #831
Opened 2019-03-22 13:15 UTC by cmonfort

Refs: #829

2019-03-22 13:57 UTC, bert-e commented
# Hello cmonfort,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/metalk8s/bert-e/doc/user).





*Status report is not available.*

2019-03-22 13:57 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `improvement/829-change-salt-master-call` into
`development/2.0`
* [w/2.1/improvement/829-change-salt-master-call](https://github.com/scality/metalk8s/compare/development/2.1...w/2.1/improvement/829-change-salt-master-call) will be merged into `development/2.1` 
* [w/2.2/improvement/829-change-salt-master-call](https://github.com/scality/metalk8s/compare/development/2.2...w/2.2/improvement/829-change-salt-master-call) will be merged into `development/2.2` 



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`




You can set option `create_pull_requests` if you need me to create
**integration pull requests** in addition to integration branches, with:

```
@bert-e create_pull_requests
```

2019-03-22 13:57 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @cmonfort

* @alexandre-allard-scality

* @gdemonet

* @slaperche-scality

* @ramanduh

* @ballot-scality

* @teddyandrieux

* @tcarmet

* @lucieleonard

* @zempashi

* @sayf-eddine-scality

* @carlito-scality

* @jbertran

* @thomasdanan

* @monpote

* @nootal

* @nicolast

* @alxf

2019-03-22 18:03 UTC, NicolasT submitted a review, later dismissed

2019-03-25 07:58 UTC, alexandre-allard submitted a review, later dismissed

2019-03-25 07:59 UTC, bert-e commented
# Conflict




There is a conflict between your branch `improvement/829-change-salt-master-call` and the
destination branch `development/2.0`.

Please resolve the conflict on **the feature branch** (`improvement/829-change-salt-master-call`).

```bash
 $ git fetch
 $ git checkout origin/improvement/829-change-salt-master-call
 $ git merge origin/development/2.0
 $ # <intense conflict resolution>
 $ git commit
 $ git push origin HEAD:improvement/829-change-salt-master-call
```

2019-03-25 08:10 UTC, slaperche-scality requested changes
Please explain why this change in the commit message.

Link to the issue is nice, but useless when you're working offline or if Github is down.

2019-03-26 15:58 UTC, bert-e commented
# History mismatch



Merge commit #1fb9b131de74d4843e96d957bac203a8315aa999 on the integration branch
`w/2.1/improvement/829-change-salt-master-call` is merging a branch which is neither the current
branch `improvement/829-change-salt-master-call` nor the development branch
`development/2.1`.

It is likely due to a rebase of the branch `improvement/829-change-salt-master-call` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**

2019-03-26 16:05 UTC, cmonfort commented
@bert-e approve

2019-03-26 16:05 UTC, bert-e commented
# History mismatch



Merge commit #1fb9b131de74d4843e96d957bac203a8315aa999 on the integration branch
`w/2.1/improvement/829-change-salt-master-call` is merging a branch which is neither the current
branch `improvement/829-change-salt-master-call` nor the development branch
`development/2.1`.

It is likely due to a rebase of the branch `improvement/829-change-salt-master-call` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**





*The following options are set:* **approve**

2019-03-26 16:06 UTC, cmonfort commented
@bert-e reset

2019-03-26 16:06 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.






*The following options are set:* **approve**

2019-03-26 16:06 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `improvement/829-change-salt-master-call` into
`development/2.0`
* [w/2.1/improvement/829-change-salt-master-call](https://github.com/scality/metalk8s/compare/development/2.1...w/2.1/improvement/829-change-salt-master-call) will be merged into `development/2.1` 
* [w/2.2/improvement/829-change-salt-master-call](https://github.com/scality/metalk8s/compare/development/2.2...w/2.2/improvement/829-change-salt-master-call) will be merged into `development/2.2` 



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`




You can set option `create_pull_requests` if you need me to create
**integration pull requests** in addition to integration branches, with:

```
@bert-e create_pull_requests
```







*The following options are set:* **approve**

2019-03-26 16:06 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @cmonfort

* @alexandre-allard-scality

* @gdemonet

* @slaperche-scality

* @ramanduh

* @ballot-scality

* @teddyandrieux

* @tcarmet

* @lucieleonard

* @zempashi

* @sayf-eddine-scality

* @carlito-scality

* @jbertran

* @thomasdanan

* @monpote

* @nootal

* @nicolast

* @alxf





The following reviewers are expecting changes from the author, or must review again:

* @slaperche-scality







*The following options are set:* **approve**

2019-03-26 19:47 UTC, slaperche-scality submitted a review, later dismissed

2019-03-26 19:47 UTC, bert-e commented
# Build failed



The build for [commit](https://github.com/scality/metalk8s/commit/eba25f5a1240eb70bbbbf645f1edaf1b58c46aa7) did not succeed in branch improvement/829-change-salt-master-call.




*The following options are set:* **approve**

2019-03-26 20:46 UTC, bert-e commented
# History mismatch



Merge commit #eba25f5a1240eb70bbbbf645f1edaf1b58c46aa7 on the integration branch
`w/2.1/improvement/829-change-salt-master-call` is merging a branch which is neither the current
branch `improvement/829-change-salt-master-call` nor the development branch
`development/2.1`.

It is likely due to a rebase of the branch `improvement/829-change-salt-master-call` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**





*The following options are set:* **approve**

2019-03-26 20:46 UTC, nootal commented
@bert-e reset

2019-03-26 20:46 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.






*The following options are set:* **approve**

2019-03-26 20:46 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `improvement/829-change-salt-master-call` into
`development/2.0`
* [w/2.1/improvement/829-change-salt-master-call](https://github.com/scality/metalk8s/compare/development/2.1...w/2.1/improvement/829-change-salt-master-call) will be merged into `development/2.1` 
* [w/2.2/improvement/829-change-salt-master-call](https://github.com/scality/metalk8s/compare/development/2.2...w/2.2/improvement/829-change-salt-master-call) will be merged into `development/2.2` 



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`




You can set option `create_pull_requests` if you need me to create
**integration pull requests** in addition to integration branches, with:

```
@bert-e create_pull_requests
```







*The following options are set:* **approve**

2019-03-26 20:46 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer





Peer approvals *must* include at least 1 approval from the following list:

* @cmonfort

* @alexandre-allard-scality

* @gdemonet

* @slaperche-scality

* @ramanduh

* @ballot-scality

* @teddyandrieux

* @tcarmet

* @lucieleonard

* @zempashi

* @sayf-eddine-scality

* @carlito-scality

* @jbertran

* @thomasdanan

* @monpote

* @nootal

* @nicolast

* @alxf










*The following options are set:* **approve**

2019-03-26 21:23 UTC, charlesprost approved these changes

2019-03-26 21:23 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/2.0`

* :heavy_check_mark: `development/2.1`

* :heavy_check_mark: `development/2.2`



The following branches will **NOT** be impacted:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2019-03-26 21:51 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/2.0`

* :heavy_check_mark: `development/2.1`

* :heavy_check_mark: `development/2.2`



The following branches have **NOT** changed:

* `development/1.0`
* `development/1.1`
* `development/1.2`
* `development/1.3`



Please check the status of the associated issue None.

Goodbye cmonfort.

2019-03-26 21:51 UTC, merged